/* TrailScope module: colors.js — generated by JS modularization build. */
const UPHILL_GRADIENT_COLORS = [
    '#58d400',
    '#8ad502',
    '#bdd604',
    '#deab04',
    '#ef5602',
    '#ff0000'
];
const DOWNHILL_GRADIENT_COLORS = [
    '#58d400',
    '#58cb66',
    '#57c2cc',
    '#46bbfc',
    '#23b6f6',
    '#00b0f0'
];
const elevationColorBreakpoints = UPHILL_GRADIENT_COLORS;
const MAX_GRADIENT = 50;


