/* TrailScope module: coords.js — generated by JS modularization build. */
        let useGCJ02Display = false;
        const PI = Math.PI;
        const AXIS = 6378245.0;
        const EE = 0.00669342162296594323;
        function outOfChina(lat, lon) {
            return lon < 72.004 || lon > 137.8347 || lat < 0.8293 || lat > 55.8271;
        }
        function transformLat(x, y) {
            let ret = -100 + 2 * x + 3 * y + 0.2 * y * y + 0.1 * x * y + 0.2 * Math.sqrt(Math.abs(x));
            ret += (20 * Math.sin(6 * x * PI) + 20 * Math.sin(2 * x * PI)) * 2 / 3;
            ret += (20 * Math.sin(y * PI) + 40 * Math.sin(y / 3 * PI)) * 2 / 3;
            ret += (160 * Math.sin(y / 12 * PI) + 320 * Math.sin(y * PI / 30)) * 2 / 3;
            return ret;
        }
        function transformLon(x, y) {
            let ret = 300 + x + 2 * y + 0.1 * x * x + 0.1 * x * y + 0.1 * Math.sqrt(Math.abs(x));
            ret += (20 * Math.sin(6 * x * PI) + 20 * Math.sin(2 * x * PI)) * 2 / 3;
            ret += (20 * Math.sin(x * PI) + 40 * Math.sin(x / 3 * PI)) * 2 / 3;
            ret += (150 * Math.sin(x / 12 * PI) + 300 * Math.sin(x / 30 * PI)) * 2 / 3;
            return ret;
        }
        function delta(lat, lon) {
            let dLat = transformLat(lon - 105, lat - 35);
            let dLon = transformLon(lon - 105, lat - 35);
            const radLat = lat / 180 * PI;
            let magic = Math.sin(radLat);
            magic = 1 - EE * magic * magic;
            const sqrtMagic = Math.sqrt(magic);
            dLat = (dLat * 180) / ((AXIS * (1 - EE)) / (magic * sqrtMagic) * PI);
            dLon = (dLon * 180) / (AXIS / sqrtMagic * Math.cos(radLat) * PI);
            return [dLat, dLon];
        }
        function wgs84ToGcj02(lat, lon) {
            if (outOfChina(lat, lon)) return [lat, lon];
            const d = delta(lat, lon);
            return [lat + d[0], lon + d[1]];
        }
        function gcj02ToWgs84(lat, lon) {
            if (outOfChina(lat, lon)) return [lat, lon];
            let wLat = lat,
                wLon = lon;
            for (let i = 0; i < 20; i++) {
                const g = wgs84ToGcj02(wLat, wLon);
                const dLat = g[0] - lat;
                const dLon = g[1] - lon;
                wLat -= dLat;
                wLon -= dLon;
                if (Math.abs(dLat) + Math.abs(dLon) < 1e-10) break;
            }
            return [wLat, wLon];
        }
        function displayLatLng(p) {
            return useGCJ02Display ? wgs84ToGcj02(p.lat, p.lon) : [p.lat, p.lon];
        }
        function displayWaypointLatLng(p) {
            return useGCJ02Display ? wgs84ToGcj02(p.lat, p.lon) : [p.lat, p.lon];
        }
