/* TrailScope module: device.js — generated by JS modularization build. */
function detectDevice() {
    const ua = navigator.userAgent || '';
    const platform = navigator.platform || '';

    const isHarmony = ua.indexOf('HarmonyOS') !== -1;
    const isHarmonyPC = isHarmony && ua.indexOf('Mobile') === -1;
    const isHarmonyMobile = isHarmony && ua.indexOf('Mobile') !== -1;

    const isWindows = platform.indexOf('Win') !== -1 || ua.indexOf('Windows') !== -1;
    const isMac = platform.indexOf('Mac') !== -1 || ua.indexOf('Macintosh') !== -1;
    const isLinux = platform.indexOf('Linux') !== -1 || ua.indexOf('Linux') !== -1;

    const isAndroid = ua.indexOf('Android') !== -1;
    const isIOS = ua.indexOf('iPhone') !== -1 || ua.indexOf('iPad') !== -1 || ua.indexOf('iPod') !== -1;

    const isDesktop = isWindows || isMac || isLinux || isHarmonyPC;
    const isMobile = isAndroid || isIOS || isHarmonyMobile;

    if (!isDesktop && !isMobile) {
        return window.innerWidth < 768 ? 'mobile' : 'desktop';
    }

    return isMobile ? 'mobile' : 'desktop';
}
const DEVICE_TYPE = detectDevice();
const IS_MOBILE = DEVICE_TYPE === 'mobile';

// ★★★ 视口方向判断：全屏模式下区分手机横竖屏（旋转屏幕时每次重新读取） ★★★
function isPortraitViewport() {
    return window.innerHeight > window.innerWidth;
}


