/* TrailScope module: elevation.js — generated by JS modularization build. */
const ElevationCalculator = {
    THRESHOLD: 4,
    computeTotal(points, mode) {
        if (mode === 'raw') {
            return this._computeRaw(points);
        } else {
            return this._computeSmooth(points);
        }
    },
    computeSegment(points, startIdx, endIdx, mode) {
        if (mode === 'raw') {
            let ascent = 0;
            let descent = 0;
            for (let i = startIdx + 1; i <= endIdx; i++) {
                const diff = points[i].ele - points[i - 1].ele;
                if (diff > 0) ascent += diff;
                else descent += Math.abs(diff);
            }
            return { ascent, descent };
        }

        let ascent = 0;
        let descent = 0;
        let residual = 0;
        for (let i = startIdx + 1; i <= endIdx; i++) {
            residual += points[i].ele - points[i - 1].ele;
            if (residual > this.THRESHOLD) {
                ascent += residual;
                residual = 0;
            } else if (residual < -this.THRESHOLD) {
                descent += Math.abs(residual);
                residual = 0;
            }
        }
        return { ascent, descent };
    },
    _computeRaw(pts) {
        let ascent = 0,
            descent = 0;
        for (let i = 1; i < pts.length; i++) {
            const diff = pts[i].ele - pts[i - 1].ele;
            if (diff > 0) ascent += diff;
            else descent += Math.abs(diff);
        }
        return { ascent, descent };
    },
    _computeSmooth(pts) {
        let ascent = 0,
            descent = 0;
        let residual = 0;
        for (let i = 1; i < pts.length; i++) {
            residual += (pts[i].ele - pts[i - 1].ele);
            if (residual > this.THRESHOLD) {
                ascent += residual;
                residual = 0;
            } else if (residual < -this.THRESHOLD) {
                descent += Math.abs(residual);
                residual = 0;
            }
        }
        return { ascent, descent };
    }
};
function setElevationMode(mode) {
    if (mode === 'raw' || mode === 'smooth') {
        elevationMode = mode;
        document.getElementById('rawElevBtn').classList.toggle('active', mode === 'raw');
        document.getElementById('smoothElevBtn').classList.toggle('active', mode === 'smooth');
        if (trackData) {
            recalculateElevations();
            updateUI();
            drawChart();
            if (hoveredPointIdx >= 0) {
                updateMapCurrentPoint(hoveredPointIdx);
            }
            if (activeSegmentIdx >= 0) {
                const segments = analyzeSegments(trackData, segmentMode);
                if (activeSegmentIdx < segments.length) {
                    showMapSegmentInfo(activeSegmentIdx, segments);
                }
            }
        }
    }
}
function recalculateElevations() {
    if (!trackData) return;
    const points = trackData.points;
    const mode = elevationMode;
    const total = ElevationCalculator.computeTotal(points, mode);
    trackData.totalAscent = total.ascent;
    trackData.totalDescent = total.descent;
    const totalHorizontalDistance = trackData.totalHorizontalDistance || 0;
    trackData.avgGradient = totalHorizontalDistance > 0 ? (trackData.totalAscent / (totalHorizontalDistance * 1000)) *
        100 : 0;
}


