/* TrailScope module: gpx-math.js — generated by JS modularization build. */
function haversine(lat1, lon1, lat2, lon2) {
    const R = 6371;
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
        Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
        Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return R * c;
}
function calculate3DDistance(lat1, lon1, ele1, lat2, lon2, ele2) {
    const horizontalDist = haversine(lat1, lon1, lat2, lon2) * 1000;
    const elevDiff = ele2 - ele1;
    return Math.sqrt(horizontalDist * horizontalDist + elevDiff * elevDiff) / 1000;
}
function findNearestPointIndex(points, lat, lon) {
    let minDist = Infinity;
    let nearestIdx = 0;

    for (let i = 0; i < points.length; i++) {
        const dist = Math.pow(points[i].lat - lat, 2) + Math.pow(points[i].lon - lon, 2);
        if (dist < minDist) {
            minDist = dist;
            nearestIdx = i;
        }
    }

    return nearestIdx;
}


