/* TrailScope module: map-common.js — generated by JS modularization build. */
function hideWaypointInfoOverlay() {
    if (selectedWaypointMarker) {
        selectedWaypointMarker.closePopup();
        selectedWaypointMarker = null;
    }
    isWaypointInfoPinned = false;
}
function clearRenderedTrackLayers() {
    if (leafletMap) {
        trackLayers.forEach(layer => leafletMap.removeLayer(layer));
        waypointMarkers.forEach(marker => leafletMap.removeLayer(marker));
        segmentHighlightLayers.forEach(layer => leafletMap.removeLayer(layer));
        if (currentMarker) leafletMap.removeLayer(currentMarker);
    }
    trackLayers = [];
    waypointMarkers = [];
    segmentHighlightLayers = [];
    currentMarker = null;
    currentMarkerPointIdx = -1;
}
let fullscreenFollowGeometry = null;
function invalidateFullscreenFollowGeometry() {
    fullscreenFollowGeometry = null;
}
function getFullscreenFollowGeometry(mapSize) {
    const cachedProfile = fullscreenFollowGeometry?.profile;
    if (fullscreenFollowGeometry && cachedProfile?.isConnected &&
        fullscreenFollowGeometry.mapWidth === mapSize.x &&
        fullscreenFollowGeometry.mapHeight === mapSize.y) {
        return fullscreenFollowGeometry;
    }

    const profile = cachedProfile?.isConnected ? cachedProfile : document.querySelector('.fullscreen-profile');
    if (!profile) return null;

    const mapRect = leafletMap.getContainer().getBoundingClientRect();
    const profileRect = profile.getBoundingClientRect();
    const visibleMapHeight = Math.max(0, Math.min(mapSize.y, profileRect.top - mapRect.top));
    const insetY = Math.min(80, Math.max(28, mapSize.y * 0.16));
    const desiredY = visibleMapHeight > insetY * 2 ? visibleMapHeight / 2 : mapSize.y / 2;
    fullscreenFollowGeometry = {
        mapWidth: mapSize.x,
        mapHeight: mapSize.y,
        profile,
        desiredY
    };
    return fullscreenFollowGeometry;
}

function keepMapPointVisible(displayPos) {
    if (!mapLinkageEnabled || !leafletMap) return;

    const mapSize = leafletMap.getSize();
    if (!mapSize || mapSize.x <= 0 || mapSize.y <= 0) return;

    const markerPoint = leafletMap.latLngToContainerPoint(displayPos);

    const isFullscreenChart = !!fullscreenFollowGeometry ||
        document.getElementById('mapContainer')?.classList.contains('map-fullscreen-chart');
    if (isFullscreenChart) {
        const geometry = getFullscreenFollowGeometry(mapSize);
        const desiredY = geometry ? geometry.desiredY : mapSize.y / 2;
        const targetX = mapSize.x / 2;
        const offsetX = markerPoint.x - targetX;
        const offsetY = markerPoint.y - desiredY;

        // panBy uses the same final container-point delta as panTo + the vertical
        // compensation, but avoids a second Leaflet view update for every hit.
        if (Math.abs(offsetX) > 0.5 || Math.abs(offsetY) > 0.5) {
            if (Math.abs(offsetX) <= mapSize.x && Math.abs(offsetY) <= mapSize.y) {
                leafletMap.panBy([offsetX, offsetY], { animate: false });
            } else {
                // Keep Leaflet's large-offset fallback for points outside the viewport.
                leafletMap.panTo(displayPos, { animate: false });
                if (desiredY !== mapSize.y / 2) {
                    leafletMap.panBy([0, mapSize.y / 2 - desiredY], { animate: false });
                }
            }
        }
        return;
    }

    // Non-fullscreen: always center the current position at the map window center
    // (panBy keeps the same final container-point delta as panTo but avoids a
    // full Leaflet view reset per hit); skip when it is already within 0.5px of
    // the target to avoid a meaningless view update per hit.
    const centerX = mapSize.x / 2;
    const centerY = mapSize.y / 2;
    const offsetX = markerPoint.x - centerX;
    const offsetY = markerPoint.y - centerY;
    if (Math.abs(offsetX) > 0.5 || Math.abs(offsetY) > 0.5) {
        if (Math.abs(offsetX) <= mapSize.x && Math.abs(offsetY) <= mapSize.y) {
            leafletMap.panBy([offsetX, offsetY], { animate: false });
        } else {
            leafletMap.panTo(displayPos, { animate: false });
        }
    }
}

const trackRenderGroupCache = new WeakMap();
function getTrackMapCache(points) {
    let cache = trackRenderGroupCache.get(points);
    if (!cache || cache.pointCount !== points.length) {
        cache = { pointCount: points.length, coordinates: new Map(), variants: new Map() };
        trackRenderGroupCache.set(points, cache);
    }
    return cache;
}
function getTrackDisplayCoordinates(points) {
    const cache = getTrackMapCache(points);
    const coordinateMode = useGCJ02Display ? 'gcj02' : 'wgs84';
    let coordinates = cache.coordinates.get(coordinateMode);
    if (coordinates) return coordinates;

    coordinates = new Array(points.length);
    for (let i = 0; i < points.length; i++) {
        const point = points[i];
        if (coordinateMode === 'gcj02') {
            const display = wgs84ToGcj02(point.lat, point.lon);
            coordinates[i] = L.latLng(display[0], display[1]);
        } else {
            coordinates[i] = L.latLng(point.lat, point.lon);
        }
    }
    cache.coordinates.set(coordinateMode, coordinates);
    return coordinates;
}
function getTrackRenderGroups(points, mode, minElevation, maxElevation) {
    const cache = getTrackMapCache(points);
    const coordinateMode = useGCJ02Display ? 'gcj02' : 'wgs84';
    const cacheKey = `${mode}:${coordinateMode}:${minElevation}:${maxElevation}`;
    const cachedGroups = cache.variants.get(cacheKey);
    if (cachedGroups) {
        cache.variants.delete(cacheKey);
        cache.variants.set(cacheKey, cachedGroups);
        return cachedGroups;
    }

    const coordinates = getTrackDisplayCoordinates(points);
    const renderGroups = new Map();
    let previousBucketKey = null;
    let currentLine = null;
    for (let i = 1; i < points.length; i++) {
        const value = mode === 'elevation'
            ? points[i].ele
            : (points[i].smoothedGradient + points[i - 1].smoothedGradient) / 2;
        const bucket = getTrackRenderColor(mode, value, minElevation, maxElevation);
        let group = renderGroups.get(bucket.key);
        if (!group) {
            group = { color: bucket.color, lines: [] };
            renderGroups.set(bucket.key, group);
        }

        if (bucket.key === previousBucketKey && currentLine) {
            currentLine.push(coordinates[i]);
        } else {
            currentLine = [coordinates[i - 1], coordinates[i]];
            group.lines.push(currentLine);
        }
        previousBucketKey = bucket.key;
    }

    const groups = Array.from(renderGroups.values());
    cache.variants.set(cacheKey, groups);
    while (cache.variants.size > 2) {
        cache.variants.delete(cache.variants.keys().next().value);
    }
    return groups;
}

function fitMapToTrack() {
    if (!trackData || !leafletMap) return;

    const points = trackData.points;
    const coordinates = getTrackDisplayCoordinates(points);
    const bounds = L.latLngBounds(coordinates);
    const fullscreen = document.getElementById('fullscreenProfile');
    const isPortrait = document.getElementById('mapContainer')?.classList?.contains('portrait-mode');
    if (fullscreen && isPortrait) {
        leafletMap.fitBounds(bounds, {
            paddingTopLeft: [30, 30],
            paddingBottomRight: [30, 30]
        });
    } else {
        // 全屏横屏：地图覆盖整个屏幕，底部预留剖面图面板高度，使轨迹完整落在可视区域内
        leafletMap.fitBounds(bounds, {
            paddingTopLeft: [30, 30],
            paddingBottomRight: [30, fullscreen ? Math.round(innerHeight * 0.42) : 30]
        });
    }
}
function mapZoomIn() {
    if (leafletMap) leafletMap.zoomIn();
}
function mapZoomOut() {
    if (leafletMap) leafletMap.zoomOut();
}
function highlightSegmentOnMap(segmentIdx) {
    segmentHighlightLayers.forEach(layer => leafletMap.removeLayer(layer));
    segmentHighlightLayers = [];

    if (segmentIdx < 0 || !trackData) {
        hideMapSegmentInfo();
        return;
    }

    const segments = analyzeSegments(trackData, segmentMode);
    if (segmentIdx >= segments.length) {
        hideMapSegmentInfo();
        return;
    }

    const seg = segments[segmentIdx];
    const points = trackData.points;
    const coordinates = getTrackDisplayCoordinates(points);
    // ★★★ 短段直接引用子数组；长段从 55K 级坐标数组切片是主要复制开销，同样语义下复用原数组引用 ★★★
    const segLatLngs = (seg.endIdx - seg.startIdx <= 1000)
        ? coordinates.slice(seg.startIdx, seg.endIdx + 1)
        : coordinates;

    const highlightLine = L.polyline(segLatLngs, {
        color: '#d4a017',
        weight: 8,
        opacity: 0.5
    }).addTo(leafletMap);

    segmentHighlightLayers.push(highlightLine);

    const startIcon = cachedSegmentStartIcon;
    const endIcon = cachedSegmentEndIcon;

    const startMarker = L.marker(displayLatLng(points[seg.startIdx]), { icon: startIcon })
        .addTo(leafletMap);
    const endMarker = L.marker(displayLatLng(points[seg.endIdx]), { icon: endIcon })
        .addTo(leafletMap);

    segmentHighlightLayers.push(startMarker);
    segmentHighlightLayers.push(endMarker);

    const bounds = L.latLngBounds(segLatLngs);
    leafletMap.fitBounds(bounds, { padding: [50, 50] });

    showMapSegmentInfo(segmentIdx, segments);
}
function showMapSegmentInfo(segmentIdx, segments) {
    const mapSegmentInfo = document.getElementById('mapSegmentInfo');
    mapSegmentInfo.classList.remove('hidden');
    mapSegmentInfo.style.display = 'flex';

    updateMapSegmentLabel(segmentIdx, segments);

    const mapSegmentLabel = document.getElementById('mapSegmentLabel');
    mapSegmentLabel.onmouseenter = function(e) {
        showSegmentTooltip(segmentIdx, e);
    };
    mapSegmentLabel.onmousemove = function(e) {
        moveSegmentTooltip(e);
    };
    mapSegmentLabel.onmouseleave = function() {
        hideSegmentTooltip();
    };
}
function hideMapSegmentInfo() {
    const mapSegmentInfo = document.getElementById('mapSegmentInfo');
    mapSegmentInfo.classList.add('hidden');
    mapSegmentInfo.style.display = 'none';
}
function navigateSegment(direction) {
    if (activeSegmentIdx < 0) return;

    const segments = analyzeSegments(trackData, segmentMode);
    const newIdx = activeSegmentIdx + direction;

    if (newIdx >= 0 && newIdx < segments.length) {
        selectSegment(newIdx);
    }
}
function zoomToSegment(segmentIdx) {
    if (!trackData || segmentIdx < 0) return;

    const segments = analyzeSegments(trackData, segmentMode);
    if (segmentIdx >= segments.length) return;

    const seg = segments[segmentIdx];
    const points = trackData.points;

    if (!seg || seg.startIdx === undefined || seg.endIdx === undefined) return;
    if (seg.startIdx < 0 || seg.endIdx < 0 || seg.startIdx >= points.length || seg.endIdx >= points.length) return;

    const segStartDist = points[seg.startIdx].distance;
    const segEndDist = points[seg.endIdx].distance;
    const segDistance = segEndDist - segStartDist;

    if (segDistance <= 0) return;

    const paddingRatio = 0.8;
    const targetVisibleRange = segDistance / paddingRatio;

    const newZoomLevel = Math.min(trackData.maxZoomLevel, Math.max(1, trackData.totalDistance / targetVisibleRange));

    const segCenterDist = (segStartDist + segEndDist) / 2;
    const newZoomCenter = segCenterDist / trackData.totalDistance;

    zoomLevel = newZoomLevel;
    zoomCenter = Math.max(0, Math.min(1, newZoomCenter));

    updateZoomInfo();
    drawChart();
}


