/* TrailScope module: map-common.js — generated by JS modularization build. */
function hideWaypointInfoOverlay() {
    if (selectedWaypointMarker) {
        selectedWaypointMarker.closePopup();
        selectedWaypointMarker = null;
    }
    isWaypointInfoPinned = false;
}
function keepMapPointVisible(displayPos) {
    if (!mapLinkageEnabled || !leafletMap) return;

    const mapSize = leafletMap.getSize();
    if (!mapSize || mapSize.x <= 0 || mapSize.y <= 0) return;

    const markerPoint = leafletMap.latLngToContainerPoint(displayPos);
    const insetX = Math.min(96, Math.max(32, mapSize.x * 0.16));
    const insetY = Math.min(80, Math.max(28, mapSize.y * 0.16));
    let safeTop = insetY;
    let safeBottom = mapSize.y - insetY;
    let desiredY = mapSize.y / 2;

    const mapContainer = document.getElementById('mapContainer');
    const isFullscreenChart = mapContainer && mapContainer.classList.contains('map-fullscreen-chart');
    if (isFullscreenChart) {
        const profile = document.querySelector('.fullscreen-profile');
        if (profile) {
            const mapRect = leafletMap.getContainer().getBoundingClientRect();
            const profileRect = profile.getBoundingClientRect();
            const visibleMapHeight = Math.max(0, Math.min(mapSize.y, profileRect.top - mapRect.top));
            if (visibleMapHeight > insetY * 2) {
                safeBottom = visibleMapHeight - insetY;
                desiredY = visibleMapHeight / 2;
            }
        }
    }

    const isInsideSafeArea = markerPoint.x >= insetX && markerPoint.x <= mapSize.x - insetX &&
        markerPoint.y >= safeTop && markerPoint.y <= safeBottom;
    if (isInsideSafeArea) return;

    leafletMap.panTo(displayPos, { animate: false });
    if (isFullscreenChart && desiredY !== mapSize.y / 2) {
        leafletMap.panBy([0, mapSize.y / 2 - desiredY], { animate: false });
    }
}

const trackRenderGroupCache = new WeakMap();
function getTrackRenderGroups(points, mode, minElevation, maxElevation) {
    let cache = trackRenderGroupCache.get(points);
    if (!cache || cache.pointCount !== points.length) {
        cache = { pointCount: points.length, variants: new Map() };
        trackRenderGroupCache.set(points, cache);
    }

    const coordinateMode = useGCJ02Display ? 'gcj02' : 'wgs84';
    const cacheKey = `${mode}:${coordinateMode}:${minElevation}:${maxElevation}`;
    const cachedGroups = cache.variants.get(cacheKey);
    if (cachedGroups) return cachedGroups;

    const renderGroups = new Map();
    for (let i = 1; i < points.length; i++) {
        const value = mode === 'elevation'
            ? points[i].ele
            : (points[i].smoothedGradient + points[i - 1].smoothedGradient) / 2;
        const bucket = getTrackRenderColor(mode, value, minElevation, maxElevation);
        let group = renderGroups.get(bucket.key);
        if (!group) {
            group = { color: bucket.color, lines: [] };
            renderGroups.set(bucket.key, group);
        }
        group.lines.push([displayLatLng(points[i - 1]), displayLatLng(points[i])]);
    }

    const groups = Array.from(renderGroups.values());
    cache.variants.set(cacheKey, groups);
    return groups;
}

function fitMapToTrack() {
    if (!trackData || !leafletMap) return;

    const points = trackData.points;
    const bounds = L.latLngBounds(points.map(p => displayLatLng(p)));
    const fullscreen = document.getElementById('fullscreenProfile');
    const isPortrait = document.getElementById('mapContainer')?.classList?.contains('portrait-mode');
    if (fullscreen && isPortrait) {
        leafletMap.fitBounds(bounds, {
            paddingTopLeft: [30, 30],
            paddingBottomRight: [30, 30]
        });
    } else {
        leafletMap.fitBounds(bounds, {
            paddingTopLeft: [30, 30],
            paddingBottomRight: [30, fullscreen ? Math.round(innerHeight * 0.42) : 30]
        });
    }
}
function mapZoomIn() {
    if (leafletMap) leafletMap.zoomIn();
}
function mapZoomOut() {
    if (leafletMap) leafletMap.zoomOut();
}
function highlightSegmentOnMap(segmentIdx) {
    segmentHighlightLayers.forEach(layer => leafletMap.removeLayer(layer));
    segmentHighlightLayers = [];

    if (segmentIdx < 0 || !trackData) {
        hideMapSegmentInfo();
        return;
    }

    const segments = analyzeSegments(trackData, segmentMode);
    if (segmentIdx >= segments.length) {
        hideMapSegmentInfo();
        return;
    }

    const seg = segments[segmentIdx];
    const points = trackData.points;

    const segPoints = points.slice(seg.startIdx, seg.endIdx + 1);
    const segLatLngs = segPoints.map(p => displayLatLng(p));

    const highlightLine = L.polyline(segLatLngs, {
        color: '#d4a017',
        weight: 8,
        opacity: 0.5
    }).addTo(leafletMap);

    segmentHighlightLayers.push(highlightLine);

    const startIcon = L.divIcon({
        className: '',
        html: '<div class="custom-marker" style="background: #d4a017;">S</div>',
        iconSize: [24, 24],
        iconAnchor: [12, 12]
    });

    const endIcon = L.divIcon({
        className: '',
        html: '<div class="custom-marker" style="background: #d4a017;">E</div>',
        iconSize: [24, 24],
        iconAnchor: [12, 12]
    });

    const startMarker = L.marker(displayLatLng(points[seg.startIdx]), { icon: startIcon })
        .addTo(leafletMap);
    const endMarker = L.marker(displayLatLng(points[seg.endIdx]), { icon: endIcon })
        .addTo(leafletMap);

    segmentHighlightLayers.push(startMarker);
    segmentHighlightLayers.push(endMarker);

    const bounds = L.latLngBounds(segLatLngs);
    leafletMap.fitBounds(bounds, { padding: [50, 50] });

    showMapSegmentInfo(segmentIdx, segments);
}
function showMapSegmentInfo(segmentIdx, segments) {
    const mapSegmentInfo = document.getElementById('mapSegmentInfo');
    mapSegmentInfo.classList.remove('hidden');
    mapSegmentInfo.style.display = 'flex';

    updateMapSegmentLabel(segmentIdx, segments);

    const mapSegmentLabel = document.getElementById('mapSegmentLabel');
    mapSegmentLabel.onmouseenter = function(e) {
        showSegmentTooltip(segmentIdx, e);
    };
    mapSegmentLabel.onmousemove = function(e) {
        moveSegmentTooltip(e);
    };
    mapSegmentLabel.onmouseleave = function() {
        hideSegmentTooltip();
    };
}
function hideMapSegmentInfo() {
    const mapSegmentInfo = document.getElementById('mapSegmentInfo');
    mapSegmentInfo.classList.add('hidden');
    mapSegmentInfo.style.display = 'none';
}
function navigateSegment(direction) {
    if (activeSegmentIdx < 0) return;

    const segments = analyzeSegments(trackData, segmentMode);
    const newIdx = activeSegmentIdx + direction;

    if (newIdx >= 0 && newIdx < segments.length) {
        selectSegment(newIdx);
    }
}
function zoomToSegment(segmentIdx) {
    if (!trackData || segmentIdx < 0) return;

    const segments = analyzeSegments(trackData, segmentMode);
    if (segmentIdx >= segments.length) return;

    const seg = segments[segmentIdx];
    const points = trackData.points;

    if (!seg || seg.startIdx === undefined || seg.endIdx === undefined) return;
    if (seg.startIdx < 0 || seg.endIdx < 0 || seg.startIdx >= points.length || seg.endIdx >= points.length) return;

    const segStartDist = points[seg.startIdx].distance;
    const segEndDist = points[seg.endIdx].distance;
    const segDistance = segEndDist - segStartDist;

    if (segDistance <= 0) return;

    const paddingRatio = 0.8;
    const targetVisibleRange = segDistance / paddingRatio;

    const newZoomLevel = Math.min(trackData.maxZoomLevel, Math.max(1, trackData.totalDistance / targetVisibleRange));

    const segCenterDist = (segStartDist + segEndDist) / 2;
    const newZoomCenter = segCenterDist / trackData.totalDistance;

    zoomLevel = newZoomLevel;
    zoomCenter = Math.max(0, Math.min(1, newZoomCenter));

    updateZoomInfo();
    drawChart();
}


