/* TrailScope module: ui-common.js — generated by JS modularization build. */
function closeWaypointInfo() {
    document.getElementById('waypointInfo').classList.add('hidden');
}
function clearHighlight() {
    activeSegmentIdx = -1;
    highlightSegmentOnMap(-1);
    resetZoom();
    updateSegments();
    drawChart();
    document.getElementById('clearHighlightBtn').classList.add('hidden');
    hideMapSegmentInfo();
}
function zoomChart(factor) {
    if (IS_MOBILE) return;
    if (!trackData) return;

    const newZoom = Math.max(1, Math.min(trackData.maxZoomLevel, zoomLevel * factor));
    if (newZoom !== zoomLevel) {
        zoomLevel = newZoom;
        updateZoomInfo();
        drawChart();
    }
}
function resetZoom() {
    if (IS_MOBILE) return;
    if (!trackData) return;

    zoomLevel = 1;
    zoomCenter = 0.5;
    updateZoomInfo();
    drawChart();
}
function updateZoomInfo() {
    const info = document.getElementById('zoomInfo');
    const level = document.getElementById('zoomLevel');

    if (zoomLevel > 1 && !IS_MOBILE) {
        info.classList.remove('hidden');
        level.textContent = Math.round(zoomLevel * 100) + '%';
    } else {
        info.classList.add('hidden');
    }
}
function estimateTime(data) {
    const { totalDistance, totalAscent, totalDescent, points } = data;

    const baseTime = (totalDistance / 5) * 60;
    const ascentTime = (totalAscent / 10);
    const descentTime = (totalDescent / 15);

    let steepDistance = 0;
    for (let i = 1; i < points.length; i++) {
        if (Math.abs(points[i].smoothedGradient) > 15) {
            steepDistance += points[i].distance - points[i - 1].distance;
        }
    }
    const STEEP_PACE_PENALTY = 4;
    const steepAdjust = steepDistance * STEEP_PACE_PENALTY;

    const totalWalkMin = baseTime + ascentTime + descentTime + steepAdjust;
    const restMin = totalWalkMin * 0.15;
    const totalMin = totalWalkMin + restMin;

    return {
        totalHours: totalMin / 60,
        walkHours: totalWalkMin / 60,
        restHours: restMin / 60,
        avgPace: totalMin / totalDistance,
        calories: Math.round(70 * (totalDistance * 0.7 + totalAscent * 0.0106))
    };
}
function changePageSize() {
    const select = document.getElementById('pageSizeSelect');
    pageSize = parseInt(select.value);
    currentPage = 1;
    updateSegments();
}
function goToPage(page) {
    const totalPages = Math.ceil(totalSegments / pageSize);
    if (page >= 1 && page <= totalPages) {
        currentPage = page;
        updateSegments();
    }
}
function prevPage() {
    if (currentPage > 1) {
        currentPage--;
        updateSegments();
    }
}
function nextPage() {
    const totalPages = Math.ceil(totalSegments / pageSize);
    if (currentPage < totalPages) {
        currentPage++;
        updateSegments();
    }
}
function goToLastPage() {
    const totalPages = Math.ceil(totalSegments / pageSize);
    goToPage(totalPages);
}
function setupSegmentNumberTooltips() {
    const segmentNumbers = document.querySelectorAll('.segment-number');
    const tooltip = document.getElementById('segmentTooltip');

    segmentNumbers.forEach(num => {
        num.addEventListener('mouseenter', (e) => {
            const segIdx = parseInt(num.dataset.segmentIdx);
            showSegmentTooltip(segIdx, e);
        });

        num.addEventListener('mousemove', (e) => {
            moveSegmentTooltip(e);
        });

        num.addEventListener('mouseleave', () => {
            hideSegmentTooltip();
        });
    });
}
function moveSegmentTooltip(e) {
    const tooltip = document.getElementById('segmentTooltip');
    tooltip.style.left = (e.clientX + 12) + 'px';
    tooltip.style.top = (e.clientY - 30) + 'px';
}
function hideSegmentTooltip() {
    const tooltip = document.getElementById('segmentTooltip');
    tooltip.classList.remove('visible');
}
function selectSegment(idx) {
    if (activeSegmentIdx === idx) {
        activeSegmentIdx = -1;
        highlightSegmentOnMap(-1);
        resetZoom();
        document.getElementById('clearHighlightBtn').classList.add('hidden');
        hideMapSegmentInfo();
    } else {
        activeSegmentIdx = idx;
        highlightSegmentOnMap(idx);
        zoomToSegment(idx);
        document.getElementById('clearHighlightBtn').classList.remove('hidden');
    }
    updateSegments();
    drawChart();
}
function setSegmentSize(mode) {
    segmentMode = mode;
    activeSegmentIdx = -1;
    highlightSegmentOnMap(-1);
    document.getElementById('clearHighlightBtn').classList.add('hidden');
    currentPage = 1;
    hideMapSegmentInfo();

    document.querySelectorAll('.seg-btn').forEach(btn => {
        btn.classList.remove('active');
    });

    const btnId = mode === 'auto' ? 'segAuto' :
                  mode === 'waypoint' ? 'segWaypoint' :
                  (document.getElementById('segFixedDist') ? 'segFixedDist' : 'seg' + mode);
    document.getElementById(btnId).classList.add('active');

    if (trackData) updateSegments();
}
function showToast(message, type = 'info') {
    const toast = document.createElement('div');
    const colors = {
        success: 'bg-trail-moss text-white',
        error: 'bg-accent-red text-white',
        info: 'bg-trail-dark text-trail-cream'
    };
    toast.className = `fixed bottom-6 right-6 px-5 py-3 rounded-xl ${colors[type]} text-sm font-medium shadow-lg z-50 fade-in`;
    toast.textContent = message;
    document.body.appendChild(toast);

    setTimeout(() => {
        toast.style.opacity = '0';
        toast.style.transition = 'opacity 0.3s';
        setTimeout(() => toast.remove(), 300);
    }, 3000);
}
let normalChartCanvas = null;
let fullscreenChartCanvas = null;
let fullscreenCenterPanY = 0;
function ensureChartHoverOverlay(canvas) {
    if (!canvas || !canvas.parentElement) return null;

    let overlay = canvas._hoverOverlay;
    if (!overlay || !overlay.isConnected || overlay.parentElement !== canvas.parentElement) {
        overlay = canvas.parentElement.querySelector('.chart-hover-overlay');
        if (!overlay) {
            overlay = document.createElement('canvas');
            overlay.className = 'chart-hover-overlay';
            overlay.setAttribute('aria-hidden', 'true');
            overlay.style.position = 'absolute';
            overlay.style.inset = '0';
            overlay.style.width = '100%';
            overlay.style.height = '100%';
            overlay.style.pointerEvents = 'none';
            overlay.style.zIndex = '2';
            canvas.parentElement.appendChild(overlay);
        }
        canvas._hoverOverlay = overlay;
    }

    const scale = canvas._scale;
    const rect = scale ? null : canvas.getBoundingClientRect();
    const cssWidth = scale ? scale.W : rect.width;
    const cssHeight = scale ? scale.H : rect.height;
    const dpr = window.devicePixelRatio || 1;
    const width = Math.max(1, Math.round(cssWidth * dpr));
    const height = Math.max(1, Math.round(cssHeight * dpr));
    if (overlay.width !== width || overlay.height !== height || overlay._dpr !== dpr) {
        overlay.width = width;
        overlay.height = height;
        overlay._dpr = dpr;
    }
    const ctx = overlay.getContext('2d');
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    return { canvas: overlay, ctx, width: cssWidth, height: cssHeight };
}

function clearChartHoverOverlay(canvas = chartCanvas) {
    if (!canvas || !canvas._hoverOverlay) return;
    const overlay = canvas._hoverOverlay;
    const ctx = overlay.getContext('2d');
    const dpr = window.devicePixelRatio || 1;
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, overlay.width / dpr, overlay.height / dpr);
}

function refreshChartHoverOverlay() {
    if (!chartCanvas || !chartCanvas._scale) {
        clearChartHoverOverlay();
        return;
    }

    const overlayInfo = ensureChartHoverOverlay(chartCanvas);
    if (!overlayInfo) return;
    const { ctx, width, height } = overlayInfo;
    ctx.clearRect(0, 0, width, height);

    const activePointIdx = IS_MOBILE ? touchState.vlineIdx : hoveredPointIdx;
    if (!trackData || activePointIdx < 0 || activePointIdx >= trackData.points.length) return;
    const scale = chartCanvas._scale;
    const point = trackData.points[activePointIdx];
    if (point.distance < scale.viewStart || point.distance > scale.viewEnd) return;

    const x = scale.xScale(point.distance);
    const y = scale.yScale(point.ele);
    ctx.save();
    ctx.strokeStyle = 'rgba(26, 46, 31, 0.4)';
    ctx.lineWidth = 1.5;
    ctx.setLineDash([4, 4]);
    ctx.beginPath();
    ctx.moveTo(x, scale.padding.top);
    ctx.lineTo(x, scale.padding.top + scale.chartH);
    ctx.stroke();
    ctx.setLineDash([]);
    ctx.fillStyle = '#1a2e1f';
    ctx.beginPath();
    ctx.arc(x, y, 6, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = '#f5f1e8';
    ctx.beginPath();
    ctx.arc(x, y, 3, 0, Math.PI * 2);
    ctx.fill();
    ctx.restore();
}
function resizeActiveChartCanvas() {
    if (!chartCanvas) return;
    const rect = chartCanvas.getBoundingClientRect();
    const ratio = window.devicePixelRatio || 1;
    const width = Math.max(1, Math.round(rect.width * ratio));
    const height = Math.max(1, Math.round(rect.height * ratio));
    if (chartCanvas.width !== width || chartCanvas.height !== height || chartCanvas._dpr !== ratio) {
        chartCanvas.width = width;
        chartCanvas.height = height;
        chartCanvas._dpr = ratio;
    }
    if (chartCtx) {
        chartCtx = chartCanvas.getContext('2d');
        chartCtx.setTransform(ratio, 0, 0, ratio, 0, 0);
    }
    ensureChartHoverOverlay(chartCanvas);
    if (trackData) drawChart();
}


// 退出全屏时按记录值反向平移还原 ★★★
function applyFullscreenCenterPan() {
    fullscreenCenterPanY = 0;
    if (!trackData || !leafletMap) return;

    const container = document.getElementById('mapContainer');
    if (!container || !container.classList.contains('map-fullscreen-chart')) return;

    const profile = document.querySelector('.fullscreen-profile');
    if (!profile) return;

    const mapRect = leafletMap.getContainer().getBoundingClientRect();
    const profileRect = profile.getBoundingClientRect();
    if (profileRect.height > 0 && profileRect.top > mapRect.top) {
        const viewportCenterY = mapRect.top + mapRect.height / 2;
        fullscreenCenterPanY = viewportCenterY - (mapRect.top + profileRect.top) / 2;
        leafletMap.panBy([0, fullscreenCenterPanY], { animate: false });
    }
}
function restoreFullscreenCenterPan() {
    if (!leafletMap || !fullscreenCenterPanY) return;
    leafletMap.panBy([0, -fullscreenCenterPanY], { animate: false });
    fullscreenCenterPanY = 0;
}
function exitMapFullscreen() {
    const map = document.getElementById('mapContainer');

    if (document.fullscreenElement) {
        document.exitFullscreen?.();
    } else {
        map.classList.remove('map-fullscreen-chart');
        map.classList.remove('portrait-mode');
        document.getElementById('mapLocationLegend')?.classList.remove('hidden');
        document.getElementById('mapSourceControl')?.classList.remove('hidden');
        document.getElementById('fullscreenProfile')?.remove();
        document.getElementById('fullscreenChartToolbar')?.remove();

        if (normalChartCanvas) {
            chartCanvas = normalChartCanvas;
            chartCtx = chartCanvas.getContext('2d');
            setupChartInteraction();
            resizeActiveChartCanvas();
        }

        updateFullscreenButton(false);
        leafletMap?.invalidateSize();
        restoreFullscreenCenterPan();
    }
}
let fullscreenResizeTimer = null;
let fullscreenResizeTimer2 = null;
window.addEventListener('resize', () => {
    if (document.getElementById('fullscreenProfile')) {
        // ★★★ 全屏中旋转屏幕：按方向切换 portrait-mode 类，并刷新图表与地图（含中心平移重算） ★★★
        if (IS_MOBILE) {
            document.getElementById('mapContainer')?.classList.toggle('portrait-mode', isPortraitViewport());
        }
        resizeActiveChartCanvas();
        leafletMap?.invalidateSize();
        applyFullscreenCenterPan();

        // ★★★ Edge/Firefox 旋转后布局稳定较慢且不再触发 resize：防抖延迟再刷新，
        // 避免图表按过渡中的尺寸绘制成一条横线（两次延迟，覆盖慢稳定场景） ★★★
        clearTimeout(fullscreenResizeTimer);
        fullscreenResizeTimer = setTimeout(() => {
            resizeActiveChartCanvas();
            leafletMap?.invalidateSize();
        }, 350);
        clearTimeout(fullscreenResizeTimer2);
        fullscreenResizeTimer2 = setTimeout(() => {
            resizeActiveChartCanvas();
            leafletMap?.invalidateSize();
        }, 900);
    }
});
document.addEventListener('fullscreenchange', () => {
    if (!document.fullscreenElement) {
        const map = document.getElementById('mapContainer');
        map.classList.remove('map-fullscreen-chart');
        map.classList.remove('portrait-mode');
        document.getElementById('mapLocationLegend')?.classList.remove('hidden');
        document.getElementById('mapSourceControl')?.classList.remove('hidden');
        document.getElementById('fullscreenProfile')?.remove();
        document.getElementById('fullscreenChartToolbar')?.remove();

        if (normalChartCanvas) {
            chartCanvas = normalChartCanvas;
            chartCtx = chartCanvas.getContext('2d');
            setupChartInteraction();
            resizeActiveChartCanvas();
            normalChartCanvas = null;
            fullscreenChartCanvas = null;
        }

        updateFullscreenButton(false);
        leafletMap?.invalidateSize();
        restoreFullscreenCenterPan();
    }
});
if (!CanvasRenderingContext2D.prototype.roundRect) {
    CanvasRenderingContext2D.prototype.roundRect = function(x, y, w, h, r) {
        if (w < 2 * r) r = w / 2;
        if (h < 2 * r) r = h / 2;
        this.beginPath();
        this.moveTo(x + r, y);
        this.arcTo(x + w, y, x + w, y + h, r);
        this.arcTo(x + w, y + h, x, y + h, r);
        this.arcTo(x, y + h, x, y, r);
        this.arcTo(x, y, x + w, y, r);
        this.closePath();
        return this;
    };
}


