/* TrailScope module: ui-common.js — generated by JS modularization build. */
const systemThemeMedia = window.matchMedia?.('(prefers-color-scheme: dark)') ?? null;
let themeMode = getThemeMode();
const chartThemePalettes = {
    light: {
        grid: 'rgba(122, 148, 113, 0.12)',
        axisMuted: 'rgba(45, 74, 53, 0.5)',
        axis: 'rgba(45, 74, 53, 0.7)',
        annotationLine: 'rgba(26, 46, 31, 0.3)',
        hoverLine: 'rgba(26, 46, 31, 0.4)',
        hoverOuter: '#1a2e1f',
        hoverInner: '#f5f1e8'
    },
    dark: {
        grid: 'rgba(168, 189, 157, 0.16)',
        axisMuted: 'rgba(199, 214, 195, 0.68)',
        axis: 'rgba(229, 238, 224, 0.82)',
        annotationLine: 'rgba(229, 238, 224, 0.32)',
        hoverLine: 'rgba(237, 243, 233, 0.62)',
        hoverOuter: '#edf3e9',
        hoverInner: '#17271d'
    }
};
let resolvedTheme = document.documentElement.dataset.theme === 'dark' ? 'dark' : 'light';
let chartTheme = chartThemePalettes[resolvedTheme];
let chartThemeVersion = 0;

function updateThemeButtons() {
    const buttonModes = {
        lightThemeBtn: 'light',
        systemThemeBtn: 'system',
        darkThemeBtn: 'dark'
    };
    Object.entries(buttonModes).forEach(([id, mode]) => {
        const button = document.getElementById(id);
        if (!button) return;
        const isActive = themeMode === mode;
        button.classList.toggle('active', isActive);
        button.setAttribute('aria-pressed', String(isActive));
    });
}

function applyThemeMode(mode, persist = true) {
    const nextMode = THEME_MODES.has(mode) ? mode : 'system';
    const nextTheme = resolveTheme(nextMode);
    const themeChanged = resolvedTheme !== nextTheme;
    themeMode = nextMode;
    resolvedTheme = nextTheme;
    chartTheme = chartThemePalettes[resolvedTheme];

    const root = document.documentElement;
    root.dataset.themeMode = themeMode;
    root.dataset.theme = resolvedTheme;
    root.style.colorScheme = resolvedTheme;

    if (persist) {
        try {
            localStorage.setItem(THEME_STORAGE_KEY, themeMode);
        } catch (_) {}
    }

    updateThemeButtons();
    if (!themeChanged) return;

    chartThemeVersion++;
    if (typeof trackData !== 'undefined' && trackData && typeof drawChart === 'function' && chartCanvas) {
        drawChart({ segments: Array.isArray(allSegments) ? allSegments : [] });
    }
}

function setThemeMode(mode) {
    applyThemeMode(mode, true);
}

function handleSystemThemeChange() {
    if (themeMode === 'system') applyThemeMode('system', false);
}

if (systemThemeMedia) {
    if (typeof systemThemeMedia.addEventListener === 'function') {
        systemThemeMedia.addEventListener('change', handleSystemThemeChange);
    } else {
        systemThemeMedia.addListener(handleSystemThemeChange);
    }
}

document.addEventListener('DOMContentLoaded', () => {
    applyThemeMode(themeMode, false);
});

function closeWaypointInfo() {
    document.getElementById('waypointInfo').classList.add('hidden');
}
function clearHighlight() {
    activeSegmentIdx = -1;
    highlightSegmentOnMap(-1);
    resetZoom();
    updateSegments();
    drawChart();
    document.getElementById('clearHighlightBtn').classList.add('hidden');
    hideMapSegmentInfo();
}
function zoomChart(factor) {
    if (IS_MOBILE) return;
    if (!trackData) return;

    const newZoom = Math.max(1, Math.min(trackData.maxZoomLevel, zoomLevel * factor));
    if (newZoom !== zoomLevel) {
        zoomLevel = newZoom;
        updateZoomInfo();
        drawChart();
    }
}
function resetZoom() {
    if (IS_MOBILE) return;
    if (!trackData) return;

    zoomLevel = 1;
    zoomCenter = 0.5;
    updateZoomInfo();
    drawChart();
}
function updateZoomInfo() {
    const info = document.getElementById('zoomInfo');
    const level = document.getElementById('zoomLevel');

    if (zoomLevel > 1 && !IS_MOBILE) {
        info.classList.remove('hidden');
        level.textContent = Math.round(zoomLevel * 100) + '%';
    } else {
        info.classList.add('hidden');
    }
}
const estimatedTimeCache = new WeakMap();
function estimateTime(data) {
    const cached = estimatedTimeCache.get(data);
    if (cached && cached.totalAscent === data.totalAscent && cached.totalDescent === data.totalDescent &&
        cached.pointCount === data.points.length) {
        return cached.value;
    }

    const { totalDistance, totalAscent, totalDescent, points } = data;

    const baseTime = (totalDistance / 5) * 60;
    const ascentTime = (totalAscent / 10);
    const descentTime = (totalDescent / 15);

    let steepDistance = 0;
    for (let i = 1; i < points.length; i++) {
        if (Math.abs(points[i].smoothedGradient) > 15) {
            steepDistance += points[i].distance - points[i - 1].distance;
        }
    }
    const STEEP_PACE_PENALTY = 4;
    const steepAdjust = steepDistance * STEEP_PACE_PENALTY;

    const totalWalkMin = baseTime + ascentTime + descentTime + steepAdjust;
    const restMin = totalWalkMin * 0.15;
    const totalMin = totalWalkMin + restMin;

    const value = {
        totalHours: totalMin / 60,
        walkHours: totalWalkMin / 60,
        restHours: restMin / 60,
        avgPace: totalMin / totalDistance,
        calories: Math.round(70 * (totalDistance * 0.7 + totalAscent * 0.0106))
    };
    estimatedTimeCache.set(data, { totalAscent, totalDescent, pointCount: points.length, value });
    return value;
}
function changePageSize() {
    const select = document.getElementById('pageSizeSelect');
    pageSize = parseInt(select.value);
    currentPage = 1;
    updateSegments();
}
function goToPage(page) {
    const totalPages = Math.ceil(totalSegments / pageSize);
    if (page >= 1 && page <= totalPages) {
        currentPage = page;
        updateSegments();
    }
}
function prevPage() {
    if (currentPage > 1) {
        currentPage--;
        updateSegments();
    }
}
function nextPage() {
    const totalPages = Math.ceil(totalSegments / pageSize);
    if (currentPage < totalPages) {
        currentPage++;
        updateSegments();
    }
}
function goToLastPage() {
    const totalPages = Math.ceil(totalSegments / pageSize);
    goToPage(totalPages);
}
const fileNameHoverMedia = window.matchMedia?.('(hover: hover) and (pointer: fine)') ?? null;
let fileNameTooltipFrame = null;
function syncFileNameTooltip() {
    fileNameTooltipFrame = null;
    const fileName = document.getElementById('fileName');
    if (!fileName) return;
    const isTruncated = fileName.scrollWidth > fileName.clientWidth + 1;
    if (fileNameHoverMedia?.matches && isTruncated) {
        fileName.title = fileName.textContent;
    } else {
        fileName.removeAttribute('title');
    }
}
function scheduleFileNameTooltipSync() {
    if (fileNameTooltipFrame !== null) cancelAnimationFrame(fileNameTooltipFrame);
    fileNameTooltipFrame = requestAnimationFrame(syncFileNameTooltip);
}
function setupFileNameTooltip() {
    const fileName = document.getElementById('fileName');
    const fileInfo = document.getElementById('fileInfo');
    if (!fileName || !fileInfo) return;

    fileName.addEventListener('mouseenter', syncFileNameTooltip);
    new MutationObserver(scheduleFileNameTooltipSync).observe(fileName, {
        childList: true,
        characterData: true,
        subtree: true
    });
    if (typeof ResizeObserver === 'function') {
        const resizeObserver = new ResizeObserver(scheduleFileNameTooltipSync);
        resizeObserver.observe(fileInfo);
        resizeObserver.observe(fileName);
    } else {
        window.addEventListener('resize', scheduleFileNameTooltipSync);
    }
    if (fileNameHoverMedia) {
        if (typeof fileNameHoverMedia.addEventListener === 'function') {
            fileNameHoverMedia.addEventListener('change', scheduleFileNameTooltipSync);
        } else {
            fileNameHoverMedia.addListener(scheduleFileNameTooltipSync);
        }
    }
    scheduleFileNameTooltipSync();
}
document.addEventListener('DOMContentLoaded', setupFileNameTooltip);

function setupSegmentNumberTooltips() {
    const segmentNumbers = document.querySelectorAll('.segment-number');
    const tooltip = document.getElementById('segmentTooltip');

    segmentNumbers.forEach(num => {
        num.addEventListener('mouseenter', (e) => {
            const segIdx = parseInt(num.dataset.segmentIdx);
            showSegmentTooltip(segIdx, e);
        });

        num.addEventListener('mousemove', (e) => {
            moveSegmentTooltip(e);
        });

        num.addEventListener('mouseleave', () => {
            hideSegmentTooltip();
        });
    });
}
function moveSegmentTooltip(e) {
    const tooltip = document.getElementById('segmentTooltip');
    tooltip.style.left = (e.clientX + 12) + 'px';
    tooltip.style.top = (e.clientY - 30) + 'px';
}
function hideSegmentTooltip() {
    const tooltip = document.getElementById('segmentTooltip');
    tooltip.classList.remove('visible');
}
function selectSegment(idx) {
    if (activeSegmentIdx === idx) {
        activeSegmentIdx = -1;
        highlightSegmentOnMap(-1);
        resetZoom();
        document.getElementById('clearHighlightBtn').classList.add('hidden');
        hideMapSegmentInfo();
    } else {
        activeSegmentIdx = idx;
        highlightSegmentOnMap(idx);
        zoomToSegment(idx);
        document.getElementById('clearHighlightBtn').classList.remove('hidden');
    }
    updateSegments();
    drawChart();
}
function setSegmentSize(mode) {
    segmentMode = mode;
    activeSegmentIdx = -1;
    highlightSegmentOnMap(-1);
    document.getElementById('clearHighlightBtn').classList.add('hidden');
    currentPage = 1;
    hideMapSegmentInfo();

    document.querySelectorAll('.seg-btn').forEach(btn => {
        btn.classList.remove('active');
    });

    const btnId = mode === 'auto' ? 'segAuto' :
                  mode === 'waypoint' ? 'segWaypoint' :
                  (document.getElementById('segFixedDist') ? 'segFixedDist' : 'seg' + mode);
    document.getElementById(btnId).classList.add('active');

    if (trackData) updateSegments();
}
function showToast(message, type = 'info') {
    const toast = document.createElement('div');
    const colors = {
        success: 'bg-trail-moss text-white',
        error: 'bg-accent-red text-white',
        info: 'bg-trail-dark text-trail-cream'
    };
    toast.className = `fixed bottom-6 right-6 px-5 py-3 rounded-xl ${colors[type]} text-sm font-medium shadow-lg z-50 fade-in`;
    toast.textContent = message;
    document.body.appendChild(toast);

    setTimeout(() => {
        toast.style.opacity = '0';
        toast.style.transition = 'opacity 0.3s';
        setTimeout(() => toast.remove(), 300);
    }, 3000);
}
let normalChartCanvas = null;
let fullscreenChartCanvas = null;
function ensureChartHoverOverlay(canvas) {
    if (!canvas || !canvas.parentElement) return null;

    let overlay = canvas._hoverOverlay;
    if (!overlay || !overlay.isConnected || overlay.parentElement !== canvas.parentElement) {
        overlay = canvas.parentElement.querySelector('.chart-hover-overlay');
        if (!overlay) {
            overlay = document.createElement('canvas');
            overlay.className = 'chart-hover-overlay';
            overlay.setAttribute('aria-hidden', 'true');
            overlay.style.position = 'absolute';
            overlay.style.inset = '0';
            overlay.style.width = '100%';
            overlay.style.height = '100%';
            overlay.style.pointerEvents = 'none';
            overlay.style.zIndex = '2';
            canvas.parentElement.appendChild(overlay);
        }
        canvas._hoverOverlay = overlay;
    }

    const scale = canvas._scale;
    const rect = scale ? null : canvas.getBoundingClientRect();
    const cssWidth = scale ? scale.W : rect.width;
    const cssHeight = scale ? scale.H : rect.height;
    const dpr = window.devicePixelRatio || 1;
    const width = Math.max(1, Math.round(cssWidth * dpr));
    const height = Math.max(1, Math.round(cssHeight * dpr));
    if (overlay.width !== width || overlay.height !== height || overlay._dpr !== dpr) {
        overlay.width = width;
        overlay.height = height;
        overlay._dpr = dpr;
    }
    const ctx = overlay.getContext('2d');
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    return { canvas: overlay, ctx, width: cssWidth, height: cssHeight };
}

function clearChartHoverOverlay(canvas = chartCanvas) {
    if (!canvas || !canvas._hoverOverlay) return;
    const overlay = canvas._hoverOverlay;
    const ctx = overlay.getContext('2d');
    const dpr = window.devicePixelRatio || 1;
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, overlay.width / dpr, overlay.height / dpr);
}

function refreshChartHoverOverlay() {
    if (!chartCanvas || !chartCanvas._scale) {
        clearChartHoverOverlay();
        return;
    }

    const overlayInfo = ensureChartHoverOverlay(chartCanvas);
    if (!overlayInfo) return;
    const { ctx, width, height } = overlayInfo;
    ctx.clearRect(0, 0, width, height);

    const activePointIdx = IS_MOBILE ? touchState.vlineIdx : hoveredPointIdx;
    if (!trackData || activePointIdx < 0 || activePointIdx >= trackData.points.length) return;
    const scale = chartCanvas._scale;
    const point = trackData.points[activePointIdx];
    if (point.distance < scale.viewStart || point.distance > scale.viewEnd) return;

    const x = scale.xScale(point.distance);
    const y = scale.yScale(point.ele);
    ctx.save();
    ctx.strokeStyle = chartTheme.hoverLine;
    ctx.lineWidth = 1.5;
    ctx.setLineDash([4, 4]);
    ctx.beginPath();
    ctx.moveTo(x, scale.padding.top);
    ctx.lineTo(x, scale.padding.top + scale.chartH);
    ctx.stroke();
    ctx.setLineDash([]);
    ctx.fillStyle = chartTheme.hoverOuter;
    ctx.beginPath();
    ctx.arc(x, y, 6, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = chartTheme.hoverInner;
    ctx.beginPath();
    ctx.arc(x, y, 3, 0, Math.PI * 2);
    ctx.fill();
    ctx.restore();
}
function resizeActiveChartCanvas() {
    if (!chartCanvas) return;
    const rect = chartCanvas.getBoundingClientRect();
    const ratio = window.devicePixelRatio || 1;
    const width = Math.max(1, Math.round(rect.width * ratio));
    const height = Math.max(1, Math.round(rect.height * ratio));
    const dimensionsChanged = chartCanvas.width !== width || chartCanvas.height !== height ||
        chartCanvas._dpr !== ratio || chartCanvas._cssWidth !== rect.width || chartCanvas._cssHeight !== rect.height;
    if (dimensionsChanged) {
        chartCanvas.width = width;
        chartCanvas.height = height;
        chartCanvas._dpr = ratio;
        chartCanvas._cssWidth = rect.width;
        chartCanvas._cssHeight = rect.height;
    }
    if (chartCtx && dimensionsChanged) {
        chartCtx = chartCanvas.getContext('2d');
        chartCtx.setTransform(ratio, 0, 0, ratio, 0, 0);
    }
    if (dimensionsChanged || !chartCanvas._hoverOverlay) {
        ensureChartHoverOverlay(chartCanvas);
    }
    const themeChanged = chartCanvas._themeVersion !== chartThemeVersion;
    if (trackData && (dimensionsChanged || !chartCanvas._scale || themeChanged)) drawChart();
}


// ★★★ 切换地图全屏时保持地图中心点与缩放级别，仅调整中心锚定位置（不使用 pan 函数）：
// 未全屏：中心点在地图窗口正中；全屏：中心点位于排除海拔剖面图面板后的可视区域正中。
// 通过 project/unproject 计算目标经纬度后 setView 重锚定（内部 _resetView 将 pane 归零
// 并重算 pixelOrigin，结果确定且无累积漂移）。
let fullscreenSavedCenter = null;
let fullscreenSavedZoom = null;
let fullscreenEnterPanY = 0;
let fullscreenEntryTimer = null;
let fullscreenEntryGeneration = 0;

function cancelFullscreenRefreshTimers() {
    if (fullscreenEntryTimer) {
        clearTimeout(fullscreenEntryTimer);
        fullscreenEntryTimer = null;
    }
    clearTimeout(fullscreenResizeTimer);
    clearTimeout(fullscreenResizeTimer2);
}
function releaseFullscreenChartResources() {
    if (!fullscreenChartCanvas) return;
    fullscreenChartCanvas._destroyChartInteraction?.();
    const overlay = fullscreenChartCanvas._hoverOverlay;
    if (overlay) {
        overlay.width = 1;
        overlay.height = 1;
    }
    fullscreenChartCanvas.width = 1;
    fullscreenChartCanvas.height = 1;
    fullscreenChartCanvas._hoverOverlay = null;
    fullscreenChartCanvas._tooltip = null;
}

function reAnchorMapView(entering) {
    if (!leafletMap) return;

    const size = leafletMap.getSize();

    if (entering) {
        // 进入全屏：使用进入前保存的中心点与缩放级别（多次调用幂等）
        const center = fullscreenSavedCenter || leafletMap.getCenter();
        const zoom = fullscreenSavedZoom !== null ? fullscreenSavedZoom : leafletMap.getZoom();

        let targetY = size.y / 2;
        const panel = document.getElementById('fullscreenProfile');
        if (panel) {
            const mapRect = leafletMap.getContainer().getBoundingClientRect();
            const panelRect = panel.getBoundingClientRect();
            const visibleBottom = Math.max(0, panelRect.top - mapRect.top);
            targetY = Math.min(size.y / 2, Math.max(0, visibleBottom / 2));
        }

        // 使保存的中心点渲染在可见地图区域正中：
        // 新的地图中心 = 保存中心向南偏移 (size.y / 2 - targetY) 像素
        fullscreenEnterPanY = size.y / 2 - targetY;
        const desired = leafletMap.unproject(
            leafletMap.project(center, zoom).add([0, fullscreenEnterPanY]), zoom);
        const current = leafletMap.getCenter();
        const currentPoint = leafletMap.project(current, zoom);
        const desiredPoint = leafletMap.project(desired, zoom);
        if (leafletMap.getZoom() !== zoom || currentPoint.distanceTo(desiredPoint) > 0.5) {
            leafletMap.setView(desired, zoom, { animate: false, reset: true });
        }
    } else {
        // 退出全屏：把全屏可见区域正中的点放回地图窗口正中
        // （保留全屏期间的平移与缩放，中心缓存保持一致）
        const zoom = leafletMap.getZoom();
        const trueCenter = leafletMap.containerPointToLatLng([size.x / 2, size.y / 2]);
        const desired = leafletMap.unproject(
            leafletMap.project(trueCenter, zoom).add([0, -fullscreenEnterPanY]), zoom);
        const current = leafletMap.getCenter();
        const currentPoint = leafletMap.project(current, zoom);
        const desiredPoint = leafletMap.project(desired, zoom);
        if (currentPoint.distanceTo(desiredPoint) > 0.5) {
            leafletMap.setView(desired, zoom, { animate: false, reset: true });
        }
    }
}
function exitMapFullscreen() {
    const map = document.getElementById('mapContainer');
    cancelFullscreenRefreshTimers();
    fullscreenEntryGeneration++;
    invalidateFullscreenFollowGeometry();

    if (document.fullscreenElement) {
        document.exitFullscreen?.();
    } else {
        map.classList.remove('map-fullscreen-chart');
        map.classList.remove('portrait-mode');
        document.getElementById('mapLocationLegend')?.classList.remove('hidden');
        document.getElementById('mapSourceControl')?.classList.remove('hidden');
        releaseFullscreenChartResources();
        document.getElementById('fullscreenProfile')?.remove();
        document.getElementById('fullscreenChartToolbar')?.remove();

        if (normalChartCanvas) {
            chartCanvas = normalChartCanvas;
            chartCtx = chartCanvas.getContext('2d');
            setupChartInteraction();
            resizeActiveChartCanvas();
        }
        normalChartCanvas = null;
        fullscreenChartCanvas = null;

        updateFullscreenButton(false);
        leafletMap?.invalidateSize();
        reAnchorMapView(false);
    }
}
let fullscreenResizeTimer = null;
let fullscreenResizeTimer2 = null;
window.addEventListener('resize', () => {
    if (document.getElementById('fullscreenProfile')) {
        // ★★★ 全屏中旋转屏幕：按方向切换 portrait-mode 类，并刷新图表与地图尺寸
        // （中心锚定保持不变，与参考实现一致） ★★★
        if (IS_MOBILE) {
            document.getElementById('mapContainer')?.classList.toggle('portrait-mode', isPortraitViewport());
        }
        invalidateFullscreenFollowGeometry();
        resizeActiveChartCanvas();
        leafletMap?.invalidateSize();

        // ★★★ Edge/Firefox 旋转后布局稳定较慢且不再触发 resize：防抖延迟再刷新，
        // 避免图表按过渡中的尺寸绘制成一条横线（两次延迟，覆盖慢稳定场景） ★★★
        clearTimeout(fullscreenResizeTimer);
        fullscreenResizeTimer = setTimeout(() => {
            fullscreenResizeTimer = null;
            if (!document.getElementById('fullscreenProfile')) return;
            resizeActiveChartCanvas();
            leafletMap?.invalidateSize();
        }, 350);
        clearTimeout(fullscreenResizeTimer2);
        fullscreenResizeTimer2 = setTimeout(() => {
            fullscreenResizeTimer2 = null;
            if (!document.getElementById('fullscreenProfile')) return;
            resizeActiveChartCanvas();
            leafletMap?.invalidateSize();
        }, 900);
    }
});
document.addEventListener('fullscreenchange', () => {
    if (document.fullscreenElement) {
        // ★★★ 进入原生全屏后，按最终尺寸重新锚定地图中心点（保持中心点与缩放级别不变） ★★★
        invalidateFullscreenFollowGeometry();
        leafletMap?.invalidateSize();
        reAnchorMapView(true);
        return;
    }
    cancelFullscreenRefreshTimers();
    fullscreenEntryGeneration++;
    invalidateFullscreenFollowGeometry();
    const map = document.getElementById('mapContainer');
    map.classList.remove('map-fullscreen-chart');
    map.classList.remove('portrait-mode');
    document.getElementById('mapLocationLegend')?.classList.remove('hidden');
    document.getElementById('mapSourceControl')?.classList.remove('hidden');
    releaseFullscreenChartResources();
    document.getElementById('fullscreenProfile')?.remove();
    document.getElementById('fullscreenChartToolbar')?.remove();

    if (normalChartCanvas) {
        chartCanvas = normalChartCanvas;
        chartCtx = chartCanvas.getContext('2d');
        setupChartInteraction();
        resizeActiveChartCanvas();
        normalChartCanvas = null;
        fullscreenChartCanvas = null;
    }

    updateFullscreenButton(false);
    leafletMap?.invalidateSize();
    reAnchorMapView(false);
});
if (!CanvasRenderingContext2D.prototype.roundRect) {
    CanvasRenderingContext2D.prototype.roundRect = function(x, y, w, h, r) {
        if (w < 2 * r) r = w / 2;
        if (h < 2 * r) r = h / 2;
        this.beginPath();
        this.moveTo(x + r, y);
        this.arcTo(x + w, y, x + w, y + h, r);
        this.arcTo(x + w, y + h, x, y + h, r);
        this.arcTo(x, y + h, x, y, r);
        this.arcTo(x, y, x + w, y, r);
        this.closePath();
        return this;
    };
}


