/* TrailScope module: utils.js — generated by JS modularization build. */
        function hexToRgb(hex) {
            const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
            return result ? {
                r: parseInt(result[1], 16),
                g: parseInt(result[2], 16),
                b: parseInt(result[3], 16)
            } : { r: 0, g: 0, b: 0 };
        }
        function rgbToHex(r, g, b) {
            return '#' + [r, g, b].map(x => {
                const hex = Math.max(0, Math.min(255, Math.round(x))).toString(16);
                return hex.length === 1 ? '0' + hex : hex;
            }).join('');
        }
        function interpolateColorMulti(colors, ratio) {
            if (ratio <= 0) return colors[0];
            if (ratio >= 1) return colors[colors.length - 1];
            const segLen = 1 / (colors.length - 1);
            const idx = Math.min(Math.floor(ratio / segLen), colors.length - 2);
            const localT = (ratio - idx * segLen) / segLen;
            return interpolateColor(colors[idx], colors[idx + 1], localT);
        }
        function interpolateColor(color1, color2, t) {
            const c1 = hexToRgb(color1);
            const c2 = hexToRgb(color2);
            const r = Math.round(c1.r + (c2.r - c1.r) * t);
            const g = Math.round(c1.g + (c2.g - c1.g) * t);
            const b = Math.round(c1.b + (c2.b - c1.b) * t);
            return rgbToHex(r, g, b);
        }
        function getUphillColor(gradient) {
            if (gradient <= 0) return UPHILL_GRADIENT_COLORS[0];
            const ratio = Math.min(gradient / MAX_GRADIENT, 1);
            return interpolateColorMulti(UPHILL_GRADIENT_COLORS, ratio);
        }
        function getDownhillColor(gradient) {
            if (gradient >= 0) return DOWNHILL_GRADIENT_COLORS[0];
            const absGrad = Math.abs(gradient);
            const ratio = Math.min(absGrad / MAX_GRADIENT, 1);
            return interpolateColorMulti(DOWNHILL_GRADIENT_COLORS, ratio);
        }
        function getGradientColor(gradient) {
            return gradient >= 0 ? getUphillColor(gradient) : getDownhillColor(gradient);
        }
        function getElevationColor(elevation, minEle, maxEle) {
            const range = maxEle - minEle;
            if (range === 0) return elevationColorBreakpoints[0];
            const ratio = Math.max(0, Math.min(1, (elevation - minEle) / range));
            return interpolateColorMulti(elevationColorBreakpoints, ratio);
        }
        function getGradientLevel(gradient) {
            const absGrad = Math.abs(gradient);
            if (absGrad <= 5) return 0;
            if (absGrad <= 10) return 1;
            if (absGrad <= 15) return 2;
            if (absGrad <= 25) return 3;
            if (absGrad <= 35) return 4;
            return 5;
        }
        function changeColorMode() {
            const select = document.getElementById('colorModeSelect');
            colorMode = select.value;

            const fsColorSelect = document.getElementById('fullscreenColorModeSelect');
            if (fsColorSelect) fsColorSelect.value = colorMode;

            const gradientLegend = document.getElementById('gradientLegend');
            const elevationLegend = document.getElementById('elevationLegend');

            const fsGradientLegend = document.getElementById('fs-gradientLegend');
            const fsElevationLegend = document.getElementById('fs-elevationLegend');

            if (colorMode === 'elevation') {
                gradientLegend.classList.add('hidden');
                elevationLegend.classList.remove('hidden');
                if (fsGradientLegend) fsGradientLegend.classList.add('hidden');
                if (fsElevationLegend) fsElevationLegend.classList.remove('hidden');
                document.getElementById('mapGradientLegend').classList.add('hidden');
                document.getElementById('mapElevationLegend').classList.remove('hidden');
            } else {
                gradientLegend.classList.remove('hidden');
                elevationLegend.classList.add('hidden');
                if (fsGradientLegend) fsGradientLegend.classList.remove('hidden');
                if (fsElevationLegend) fsElevationLegend.classList.add('hidden');
                document.getElementById('mapGradientLegend').classList.remove('hidden');
                document.getElementById('mapElevationLegend').classList.add('hidden');
            }

            if (trackData) {
                drawChart();
                drawMap(true);
            }
        }
