/* TrailScope module: waypoints.js — generated by JS modularization build. */
        function toggleWaypointDisplay() {
            // 循环状态：'show-names' -> 'hide-names' -> 'hide-all' -> 'show-names'
            if (waypointDisplayMode === 'show-names') {
                waypointDisplayMode = 'hide-names';
            } else if (waypointDisplayMode === 'hide-names') {
                waypointDisplayMode = 'hide-all';
            } else {
                waypointDisplayMode = 'show-names';
            }

            // 如果切换为 hide-all，关闭可能打开的航路点信息
            if (waypointDisplayMode === 'hide-all') {
                closeWaypointInfo();
                // 关闭地图上的弹窗
                waypointMarkers.forEach(marker => {
                    try { marker.closePopup(); } catch (e) {}
                });
                // 取消固定状态
                if (selectedWaypointMarker) {
                    selectedWaypointMarker.closePopup();
                    selectedWaypointMarker = null;
                }
                isWaypointInfoPinned = false;
            }

            // 更新按钮文本和图标
            updateWaypointButton();

            // 重绘地图和图表
            if (trackData) {
                drawMap(true);
                drawChart();
            }
        }
