/* TrailScope module: analysis.js — generated by JS modularization build. */
function assessDifficulty(data) {
    const { totalDistance, totalAscent, points, uphillMaxGradient, downhillMaxGradient } = data;

    const distScore = Math.min(100, (totalDistance / 40) * 100);
    const ascentScore = Math.min(100, (totalAscent / 2000) * 100);

    let steepDistance = 0;
    let verySteepDistance = 0;
    for (let i = 1; i < points.length; i++) {
        const segDist = points[i].distance - points[i - 1].distance;
        const absGrad = Math.abs(points[i].smoothedGradient);
        if (absGrad > 15) steepDistance += segDist;
        if (absGrad > 25) verySteepDistance += segDist;
    }
    const steepRatio = steepDistance / totalDistance;
    const verySteepRatio = verySteepDistance / totalDistance;
    const gradScore = Math.min(100, steepRatio * 150 + verySteepRatio * 200);

    const overall = Math.round(distScore * 0.3 + ascentScore * 0.35 + gradScore * 0.35);

    let label, color;
    if (overall < 20) { label = 'Casual';
        color = 'var(--diff-recreation)'; } else if (overall < 40) { label = 'Easy';
        color = 'var(--diff-easy)'; } else if (overall < 55) { label = 'Moderate';
        color = 'var(--diff-moderate)'; } else if (overall < 70) { label = 'Strenuous';
        color = 'var(--diff-hard)'; } else if (overall < 85) { label = 'Expert';
        color = 'var(--diff-expert)'; } else { label = 'Bomber';
        color = 'var(--diff-extreme)'; }

    return { overall, label, color, distScore, ascentScore, gradScore };
}
function syncAdvancedWeatherResultVisibility() {
    document.querySelectorAll('#weatherResult .wbgt-result-row').forEach(row => {
        row.classList.toggle('hidden', !advancedPanelOpen);
    });
}
function formatWeatherResultTemperature(celsius, displayMode = 'dual', decimals = 1) {
    const celsiusValue = Number(celsius);
    const isMetric = unitSystem === 'metric';
    if (displayMode === 'threshold') {
        const value = isMetric ? celsiusValue : celsiusToFahrenheit(celsiusValue);
        return value.toFixed(decimals) + (isMetric ? ' °C' : ' °F');
    }
    const celsiusText = celsiusValue.toFixed(decimals);
    const fahrenheitText = celsiusToFahrenheit(celsiusValue).toFixed(decimals);
    return isMetric ?
        `${celsiusText} ℃ (${fahrenheitText} ℉)` :
        `${fahrenheitText} ℉ (${celsiusText} ℃)`;
}
function weatherResultTemperatureMarkup(celsius, displayMode = 'dual', decimals = 1) {
    return `<span class="weather-result-temperature" data-celsius="${celsius}" data-display-mode="${displayMode}" data-decimals="${decimals}">${formatWeatherResultTemperature(celsius, displayMode, decimals)}</span>`;
}
function updateWeatherResultTemperatureUnits() {
    document.querySelectorAll('#weatherResult .weather-result-temperature').forEach(element => {
        element.textContent = formatWeatherResultTemperature(
            Number(element.dataset.celsius),
            element.dataset.displayMode,
            Number(element.dataset.decimals)
        );
    });
}
function toggleAdvancedPanel() {
    const panel = document.getElementById('advancedPanel');
    const toggleLabel = document.getElementById('toggleLabel');
    const toggleArrow = document.getElementById('toggleArrow');

    advancedPanelOpen = !advancedPanelOpen;

    if (advancedPanelOpen) {
        panel.classList.add('open');
        toggleLabel.textContent = 'Hide advanced weather data';
        toggleArrow.classList.add('open');
    } else {
        panel.classList.remove('open');
        toggleLabel.textContent = 'Show advanced weather data';
        toggleArrow.classList.remove('open');
    }
    syncAdvancedWeatherResultVisibility();
}
function analyzeWeather() {
    const isMetric = unitSystem === 'metric';

    let tempInput = document.getElementById('weatherTemp').value.trim();
    let humidityInput = document.getElementById('weatherHumidity').value.trim();
    let windInput = document.getElementById('weatherWind').value.trim();
    const type = document.getElementById('weatherType').value;

    if (tempInput === '' || humidityInput === '') {
        alert('No sufficient data to analyze Weather! \n\n· BOTH Temperature and Humidity are required.');
        return;
    }

    let temp = Number(tempInput);
    let humidity = Number(humidityInput);
    let wind = windInput === '' ? 0 : Number(windInput);

    if (isNaN(temp) || isNaN(humidity) || (windInput !== '' && isNaN(wind))) {
        alert('ONLY NUMBERS accepted in Temperature, Humidity and Wind Speed.');
        return;
    }

    let tempC = isMetric ? temp : fahrenheitToCelsius(temp);
    let windMs = isMetric ? wind : mphToMps(wind);

    const invalid = (type.includes('Snow') && (tempC > 8 || humidity < 15)) ||
        tempC > 45 || tempC < -60 || humidity < 0 || humidity > 100;
    if (invalid) {
        let rangeMsg = isMetric ?
            'Temperature: -60 ~ 45 °C, Humidity: 0 ~ 100%' :
            'Temperature: -76 ~ 113 °F, Humidity: 0 ~ 100%';
        alert('Weather data not reasonable, unable to analyze weather.\n\n• ' + rangeMsg);
        return;
    }
    if (windMs < 0 || windMs > 150) {
        let windMsg = isMetric ?
            'Wind Speed: 0 ~ 150 m/s' :
            'Wind Speed: 0 ~ 335 mph';
        alert('Weather data not reasonable, unable to analyze weather.\n\n• ' + windMsg);
        return;
    }

    weatherData = { temp: tempC, humidity, wind: windMs, type };

    const tips = [];
    let heatIndexC = tempC;

    if (tempC >= 27 && humidity >= 40) {
        const T_F = tempC * 9 / 5 + 32;
        const RH = humidity;
        const hi_F = -42.379 +
            2.04901523 * T_F +
            10.14333127 * RH -
            0.22475541 * T_F * RH -
            0.00683783 * T_F * T_F -
            0.05481717 * RH * RH +
            0.00122874 * T_F * T_F * RH +
            0.00085282 * T_F * RH * RH -
            0.00000199 * T_F * T_F * RH * RH;
        heatIndexC = (hi_F - 32) * 5 / 9;
        if (heatIndexC < tempC) heatIndexC = tempC;
    }

    const makeTip = (icon, text, colorClass = '') => {
        return `<div class="weather-tip-row"><span class="weather-tip-icon ${colorClass}"><i class="fa-solid ${icon}"></i></span><span class="weather-tip-text ${colorClass} font-semibold">${text}</span></div>`;
    };

    if (heatIndexC >= 35) {
        const msg = 'Heat index ≥ ' +
            weatherResultTemperatureMarkup(35, 'threshold', 0) +
            ': skip long hikes and the hottest hours, and carry extra water.';
        tips.push(makeTip('fa-temperature-full', msg, 'text-accent-red'));
    } else if (heatIndexC >= 30) {
        const msg = 'Heat index ≥ ' +
            weatherResultTemperatureMarkup(30, 'threshold', 0) +
            ': drink more, add electrolytes, and watch for heat exhaustion.';
        tips.push(makeTip('fa-temperature-full', msg, 'text-accent-amber'));
    }
    if (type.includes('typhoon') || windMs >= 32) {
        tips.push(makeTip('fa-hurricane', 'Typhoon or strong wind: postpone the hike and stay off exposed terrain.',
            'text-accent-red'));
    }
    if (tempC <= 5) {
        tips.push(makeTip('fa-temperature-empty', 'Cold: dress in layers and carry warm insulation to avoid hypothermia.',
            'text-accent-blue'));
    }
    if (type.includes('Showers') || type.includes('Light Rain')) {
        tips.push(makeTip('fa-cloud-rain', 'Rain: bring waterproofs and take care on slick trails.',
            'text-accent-blue'));
    }
    if (type.includes('Moderate')) {
        tips.push(makeTip('fa-cloud-showers-heavy', 'Heavy rain: trails can get dangerous. Postpone the hike, especially on steep or exposed routes.',
            'text-accent-red'));
    }
    if (windMs >= 8) {
        tips.push(makeTip('fa-wind', 'Strong wind: add a windproof layer and be careful on exposed ridges.',
            'text-accent-blue'));
    }

    const rows = [];

    if (tips.length) {
        tips.forEach(tip => rows.push(tip));
    } else {
        rows.push(makeTip('fa-check', 'No extra weather risks right now.', 'text-trail-moss'));
    }

    if (advancedPanelOpen) {
        const wetBulbInput = document.getElementById('wetBulbTemp').value.trim();
        const dewPointInput = document.getElementById('dewPoint').value.trim();
        const solarRadInput = document.getElementById('solarRadiation').value.trim();
        const pressureInput = document.getElementById('pressure').value.trim();

        let directRatioInput = document.getElementById('directRadiationRatio').value.trim();
        let solarAngleInput = document.getElementById('solarAltitudeAngle').value.trim();

        if (directRatioInput === '') directRatioInput = '0.6';
        if (solarAngleInput === '') solarAngleInput = '45';

        const allAdvancedFilled = wetBulbInput !== '' && dewPointInput !== '' && solarRadInput !== '' &&
            pressureInput !== '';

        if (!allAdvancedFilled) {
            rows.push(makeTip('fa-triangle-exclamation', 'Not enough data for the advanced analysis.',
                'text-accent-amber'));
        } else {
            let wbVal = Number(wetBulbInput);
            let dpVal = Number(dewPointInput);
            let sVal = Number(solarRadInput);
            let pVal = Number(pressureInput);
            let drVal = Number(directRatioInput);
            let angleDeg = Number(solarAngleInput);

            if (isNaN(wbVal) || isNaN(dpVal) || isNaN(sVal) || isNaN(pVal) || isNaN(drVal) || isNaN(angleDeg)) {
                alert('All advanced data MUST NUMBERS.');
                return;
            }

            let wbC = isMetric ? wbVal : fahrenheitToCelsius(wbVal);
            let dpC = isMetric ? dpVal : fahrenheitToCelsius(dpVal);
            let pressureHPa = isMetric ? pVal : inHgToHPa(pVal);

            const errors = [];
            if (windMs < 0 || windMs > 150) {
                errors.push('Wind Speed: 0 ~ 150 m/s' + (isMetric ? '' : ' (0 ~ 335 mph)'));
            }
            if (sVal < 0 || sVal > 1400) {
                errors.push('Solar Radiation: 0 ~ 1400 W/m²');
            }
            if (pressureHPa < 200 || pressureHPa > 1200) {
                let pMsg = isMetric ?
                    'Air Pressure: 200 ~ 1200 hPa' :
                    'Air Pressure: 5.91 ~ 35.43 inHg';
                errors.push(pMsg);
            }
            if (wbC > tempC) {
                let wbDisplay = isMetric ? Math.round(wbC) + ' ℃' : Math.round(celsiusToFahrenheit(wbC)) + ' ℉';
                let tempDisplay = isMetric ? Math.round(tempC) + ' ℃' : Math.round(celsiusToFahrenheit(tempC)) + ' ℉';
                errors.push('Wet Bulb Temperature (' + wbDisplay + ') higher than Air Temperature (' + tempDisplay +
                ')');
            }
            if (dpC > tempC) {
                let dpDisplay = isMetric ? Math.round(dpC) + ' ℃' : Math.round(celsiusToFahrenheit(dpC)) + ' ℉';
                let tempDisplay = isMetric ? Math.round(tempC) + ' ℃' : Math.round(celsiusToFahrenheit(tempC)) + ' ℉';
                errors.push('Dew Point (' + dpDisplay + ') higher than Air Temperature (' + tempDisplay + ')');
            }
            if (dpC > wbC) {
                let dpDisplay = isMetric ? Math.round(dpC) + ' ℃' : Math.round(celsiusToFahrenheit(dpC)) + ' ℉';
                let wbDisplay = isMetric ? Math.round(wbC) + ' ℃' : Math.round(celsiusToFahrenheit(wbC)) + ' ℉';
                errors.push('Dew Point (' + dpDisplay + ') higher than Wet Bulb Temperature (' + wbDisplay + ')');
            }
            if (drVal < 0 || drVal > 1) {
                errors.push('Direct Radiation Ratio should between 0 and 1');
            }
            if (angleDeg < 0 || angleDeg > 90) {
                errors.push('Solar Altitude Angle should between 0 and 90');
            }

            if (errors.length > 0) {
                alert('Weather data not reasonable, unable to analyze weather.\n\n• ' + errors.join('\n• '));
                return;
            }

            const angleRad = angleDeg * Math.PI / 180;
            const e = 6.112 * Math.exp((17.67 * dpC) / (dpC + 243.5)) * (1.0007 + 0.00000346 * pressureHPa);
            const emissivity = 0.575 * Math.pow(e, 1 / 7);
            const C = 0.315 * Math.pow((windMs * 3600), 0.58) * 5.3865 * Math.pow(10, -8);
            const part1 = drVal * 2.268 * Math.pow(10, -8) * Math.cos(angleRad);
            const part2 = 1.2 * 5.67 * Math.pow(10, -8) * (1 - drVal);
            const B = sVal * (part1 + part2) + emissivity * Math.pow(tempC, 4);
            const Tnwb = wbC + 0.001651 * sVal - 0.09555 * windMs + 0.13235 * (tempC - wbC) + 0.20249;
            const Tg = (B + C * tempC + 7680000) / (C + 256000);
            const WBGT = 0.7 * Tnwb + 0.2 * Tg + 0.1 * tempC;

            let wbgtAdvice = '';
            let wbgtColor = 'var(--theme-text-secondary)';

            if (WBGT <= 10) {
                wbgtAdvice = 'Cold. Dress warmly and watch for hypothermia.';
                wbgtColor = 'var(--wbgt-cold)';
            } else if (WBGT > 10 && WBGT <= 18) {
                wbgtAdvice = 'Comfortable. Keep your usual pace, fluids, and food.';
                wbgtColor = 'var(--wbgt-cool)';
            } else if (WBGT > 18 && WBGT <= 23) {
                wbgtAdvice = 'Mild heat stress. Ease off a little and drink regularly.';
                wbgtColor = 'var(--wbgt-mild)';
            } else if (WBGT > 23 && WBGT <= 28) {
                wbgtAdvice = 'High heat stress. Drink more, add electrolytes, watch for heat exhaustion.';
                wbgtColor = 'var(--wbgt-warm)';
            } else if (WBGT > 28) {
                wbgtAdvice = 'Extreme heat stress. No hard efforts; postpone strenuous hikes.';
                wbgtColor = 'var(--wbgt-hot)';
            }

            let wbgtIcon;
            if (WBGT <= 10) wbgtIcon = 'fa-temperature-empty';
            else if (WBGT <= 18) wbgtIcon = 'fa-temperature-quarter';
            else if (WBGT <= 23) wbgtIcon = 'fa-temperature-half';
            else if (WBGT <= 28) wbgtIcon = 'fa-temperature-three-quarters';
            else wbgtIcon = 'fa-temperature-full';

            if (heatIndexC >= 27) {
                rows.push(
                    `<div class="weather-tip-row"><span class="weather-tip-icon text-accent-amber"><i class="fa-solid fa-temperature-full"></i></span><span class="weather-tip-text text-accent-amber font-semibold">Heat Index ≈ ${weatherResultTemperatureMarkup(heatIndexC)}</span></div>`
                    );
            }
            rows.push(
                `<div class="weather-tip-row wbgt-result-row"><span class="weather-tip-icon" style="color:${wbgtColor}"><i class="fa-solid ${wbgtIcon}"></i></span><span class="weather-tip-text" style="font-weight:600; color:${wbgtColor};">WBGT ≈ ${weatherResultTemperatureMarkup(WBGT)}，${wbgtAdvice}</span></div>`
                );
        }
    }

    const resultHtml = '<div class="weather-tips-container">' + rows.join('') + '</div>';
    document.getElementById('weatherResult').innerHTML = resultHtml;
    updateWeatherResultTemperatureUnits();
    syncAdvancedWeatherResultVisibility();

    if (trackData) updateUI();
}
function getWeatherEquipmentModifier() {
    if (!weatherData) return { recommended: [], supplies: [] };

    const r = { recommended: [], supplies: [] };

    if (weatherData.temp >= 30) {
        r.supplies.push({
            icon: 'fa-bottle-water',
            name: 'Electrolytes',
            desc: 'Replaces the fluids and salts you lose to sweat.'
        });

        r.recommended.push({
            icon: 'fa-sun',
            name: 'Sun Protection',
            desc: 'Sun hat, sunscreen, and cooling accessories.'
        });
    }

    if (weatherData.temp <= 5 || (trackData && trackData.maxElevation > 2500 && weatherData.temp <= 10)) {
        r.recommended.push({
            icon: 'fa-mitten',
            name: 'Warm Layers',
            desc: 'Fleece/down jacket and emergency insulation.'
        });
    }

    if (weatherData.type.includes('Rain')) {
        r.recommended.push({
            icon: 'fa-cloud-rain',
            name: 'Rain Gear',
            desc: 'Rain jacket, waterproof bags, and spare socks.'
        });
    }

    return r;
}
function generateEquipmentRecommendation(data, difficulty, risk) {
    const { totalDistance, totalAscent, maxElevation, uphillMaxGradient, downhillMaxGradient } = data;

    const essential = [
        {
            icon: 'fa-shoe-prints',
            name: 'Hiking Footwear',
            desc: 'Good traction and durability; mid/high-cut footwear recommended for rough terrain.'
        },
        {
            icon: 'lucide:backpack',
            name: 'Hiking Backpack',
            desc: `${totalDistance > 15 ? '30–40 L' : '20–30 L'} capacity`
        },
        {
            icon: 'fa-mobile-screen',
            name: 'Phone + Power Bank',
            desc: 'So you can stay in touch.'
        },
        {
            icon: 'fa-id-card',
            name: 'Identification',
            desc: 'Carry personal identification.'
        },
        {
            icon: 'fa-kit-medical',
            name: 'First Aid Kit',
            desc: 'Bandages, antiseptic, pain relief, and basic medical supplies.'
        }
    ];

    const recommended = [];
    const weatherModifier = getWeatherEquipmentModifier();

    if (Math.abs(uphillMaxGradient) > 15 || Math.abs(downhillMaxGradient) > 15 || totalAscent > 500) {
        recommended.push({
            icon: 'fa-person-hiking',
            name: 'Trekking Poles',
            desc: 'Easier on the knees and steadier on steep ground.'
        });
    }

    recommended.push({
        icon: 'fa-cloud-rain',
        name: 'Rain Jacket',
        desc: 'Protection from wind and rain.'
    });

    if (maxElevation > 1500) {
        recommended.push({
            icon: 'fa-sun',
            name: 'Sun Protection',
            desc: 'SPF50+ sunscreen, sunglasses, and sun hat.'
        });
    }

    if (maxElevation > 2000) {
        recommended.push({
            icon: 'fa-mitten',
            name: 'Insulating Layers',
            desc: 'Fleece/down jacket for changing temperatures.'
        });
    }

    if (totalDistance > 15) {
        recommended.push({
            icon: 'fa-lightbulb',
            name: 'Headlamp',
            desc: 'Useful if the hike takes longer than expected.'
        });
    }

    if (Math.abs(uphillMaxGradient) > 30 || Math.abs(downhillMaxGradient) > 30) {
        recommended.push({
            icon: 'fa-helmet-safety',
            name: 'Helmet',
            desc: 'Additional protection on steep or rocky terrain.'
        });
    }

    recommended.push({
        icon: 'fa-map',
        name: 'Map + Compass',
        desc: 'Backup navigation tools.'
    });

    recommended.push({
        icon: 'fa-bell',
        name: 'Emergency Whistle',
        desc: 'For emergency signaling.'
    });

    const supplies = [];

    const time = estimateTime(data);

    const waterAmount = Math.ceil(time.totalHours * 0.5 + 1);

    supplies.push({
        icon: 'fa-bottle-water',
        name: 'Water',
        desc: UnitHelper.waterVolumeLabel(waterAmount) + ' (recommended: ' + UnitHelper.waterVolumeLabel(waterAmount +
            1) + ')'
    });

    const mealsNeeded = Math.ceil(time.totalHours / 4);

    supplies.push({
        icon: 'fa-burger',
        name: 'Meals',
        desc: `${mealsNeeded} meal(s), such as energy bars, sandwiches, or trail food`
    });

    const snacksAmount = Math.ceil(time.totalHours * 2);

    supplies.push({
        icon: 'fa-cookie-bite',
        name: 'Energy Snacks',
        desc: `${snacksAmount} servings, such as chocolate, nuts, or energy gels`
    });

    if (totalAscent > 800 || time.totalHours > 4) {
        supplies.push({
            icon: 'fa-flask',
            name: 'Electrolytes',
            desc: 'Sports drinks or electrolyte tablets.'
        });
    }

    if (difficulty.overall > 60) {
        supplies.push({
            icon: 'fa-plus',
            name: 'Extra Food Reserve',
            desc: 'Additional emergency meal supply.'
        });
    }

    return { essential, recommended, supplies };
}
function assessRisks(data) {
    const risks = [];

    if (weatherData) {
        if (weatherData.temp >= 30) {
            risks.push({
                level: 'high',
                icon: 'fa-temperature-full',
                title: 'High Heat Risk',
                desc: 'Hot weather — risk of heat exhaustion and dehydration. Carry plenty of water and take it easy.'
            });
        }

        if (weatherData.temp <= 0) {
            risks.push({
                level: 'high',
                icon: 'fa-snowflake',
                title: 'Cold Weather Risk',
                desc: 'Freezing weather — risk of hypothermia. Bring warm layers.'
            });
        }

        if (weatherData.type.includes('Moderate')) {
            risks.push({
                level: 'high',
                icon: 'fa-cloud-showers-heavy',
                title: 'Heavy Rain Risk',
                desc: 'Heavy rain can make trails dangerous. Postpone hikes on steep, exposed, or badly drained routes.'
            });
        }

        if (weatherData.type.includes('Showers') || weatherData.type.includes('Light Rain')) {
            risks.push({
                level: 'medium',
                icon: 'fa-cloud-rain',
                title: 'Wet Trail Conditions',
                desc: 'Wet surfaces get slippery. Take care on rocks, roots, steep sections, and downhills.'
            });
        }
    }

    const { totalDistance, totalAscent, totalDescent, maxElevation, points, uphillMaxGradient,
        downhillMaxGradient } = data;

    if (maxElevation > 3000) {
        risks.push({
            level: 'high',
            icon: 'fa-mountain',
            title: 'High Altitude Risk',
            desc: `Highest elevation ${UnitHelper.elevationLabel(maxElevation, 0)}. Altitude sickness is possible. Acclimatize before you go.`
        });

    } else if (maxElevation > 2000) {
        risks.push({
            level: 'medium',
            icon: 'fa-mountain',
            title: 'High Elevation',
            desc: `Highest elevation ${UnitHelper.elevationLabel(maxElevation, 0)}. Strong UV and big temperature swings.`
        });
    }

    if (uphillMaxGradient > 35) {
        risks.push({
            level: 'high',
            icon: 'fa-arrow-trend-up',
            title: 'Extremely Steep Ascent',
            desc: `Maximum uphill grade ${uphillMaxGradient.toFixed(1)}%. Steep climbing needs solid fitness and poles.`
        });

    } else if (uphillMaxGradient > 25) {
        risks.push({
            level: 'medium',
            icon: 'fa-arrow-trend-up',
            title: 'Steep Ascent',
            desc: `Maximum uphill grade ${uphillMaxGradient.toFixed(1)}%. Pace yourself and conserve energy.`
        });
    }

    if (downhillMaxGradient < -35) {
        risks.push({
            level: 'high',
            icon: 'fa-arrow-trend-down',
            title: 'Extremely Steep Descent',
            desc: `Maximum downhill grade ${Math.abs(downhillMaxGradient).toFixed(1)}%. High fall risk. Be careful and use poles.`
        });

    } else if (downhillMaxGradient < -25) {
        risks.push({
            level: 'medium',
            icon: 'fa-arrow-trend-down',
            title: 'Steep Descent',
            desc: `Maximum downhill grade ${Math.abs(downhillMaxGradient).toFixed(1)}%. Look after your knees and watch your footing.`
        });
    }

    if (totalDistance > 25) {
        risks.push({
            level: 'high',
            icon: 'fa-route',
            title: 'Long Distance Route',
            desc: `Total distance ${UnitHelper.distanceLabel(totalDistance, 1)}. Needs endurance and enough supplies.`
        });

    } else if (totalDistance > 15) {
        risks.push({
            level: 'medium',
            icon: 'fa-route',
            title: 'Moderate Distance Route',
            desc: `Total distance ${UnitHelper.distanceLabel(totalDistance, 1)}. Plan water and resupply stops ahead.`
        });
    }

    if (totalAscent > 1500) {
        risks.push({
            level: 'high',
            icon: 'fa-mountain',
            title: 'Large Elevation Gain',
            desc: `Elevation gain ${UnitHelper.elevationLabel(totalAscent, 0)}. Hard on the heart and lungs.`
        });
    }

    if (totalDescent > 1200) {
        risks.push({
            level: 'medium',
            icon: 'fa-arrow-trend-down',
            title: 'Large Elevation Loss',
            desc: `Elevation loss ${UnitHelper.elevationLabel(totalDescent, 0)}. Long downhills wear on the knees.`
        });
    }

    risks.sort((a, b) => {
        const order = { high: 0, medium: 1, low: 2 };
        return order[a.level] - order[b.level];
    });

    const highCount = risks.filter(r => r.level === 'high').length;
    const medCount = risks.filter(r => r.level === 'medium').length;

    let riskLevel, riskPercent;
    if (highCount >= 2) { riskLevel = 'HIGH';
        riskPercent = 98; } else if (highCount >= 1) { riskLevel = 'MEDIUM-HIGH';
        riskPercent = 78; } else if (medCount >= 2) { riskLevel = 'MEDIUM';
        riskPercent = 58; } else if (medCount >= 1) { riskLevel = 'MEDIUM-LOW';
        riskPercent = 39; } else { riskLevel = 'LOW';
        riskPercent = 19; }

    return { risks, riskLevel, riskPercent };
}
function resetSegmentAnalysisCache() {
    allSegments = [];
    totalSegments = 0;
    cachedSegmentsTrack = null;
    cachedSegmentsMode = null;
    cachedSegmentsElevationMode = null;
    cachedSegmentsPointCount = -1;
}

function analyzeSegments(data, mode) {
    if (!data || !data.points) return [];

    const pointCount = data.points.length;
    const currentElevationMode = elevationMode || 'raw';
    if (cachedSegmentsTrack === data &&
        cachedSegmentsMode === mode &&
        cachedSegmentsElevationMode === currentElevationMode &&
        cachedSegmentsPointCount === pointCount) {
        return allSegments;
    }

    const segments = computeSegments(data, mode);
    cachedSegmentsTrack = data;
    cachedSegmentsMode = mode;
    cachedSegmentsElevationMode = currentElevationMode;
    cachedSegmentsPointCount = data.points.length;
    allSegments = segments;
    totalSegments = segments.length;
    return segments;
}

function computeSegments(data, mode) {
    const points = data.points;
    const segments = [];

    if (mode === 'waypoint') {
        const wps = data.waypoints;
        const breakpoints = [0];

        // ★★★ Re-locate each waypoint by its recorded distance instead of the trackIdx from
        // load time: distance-based segmentation inserts virtual points into `points`,
        // invalidating all trackIdx values and misaligning segment start/end markers with
        // waypoint markers in the elevation profile. Binary search by distance keeps the
        // boundaries exactly on the waypoints. ★★★
        wps.forEach(wp => breakpoints.push(findNearestPointIndexByDistance(points, wp.distance)));
        breakpoints.push(points.length - 1);

        const uniqueBreakpoints = [...new Set(breakpoints)].sort((a, b) => a - b);

        for (let i = 0; i < uniqueBreakpoints.length - 1; i++) {
            const startIdx = uniqueBreakpoints[i];
            const endIdx = uniqueBreakpoints[i + 1];

            if (endIdx > startIdx) {
                const seg = createSegment(points, startIdx, endIdx, 'auto');
                if (i === 0) {
                    seg.name = 'Start';
                    if (wps.length > 0) seg.endName = wps[0].name;
                } else if (i === uniqueBreakpoints.length - 2) {
                    seg.name = wps[wps.length - 1].name;
                    seg.endName = 'Finish';
                } else {
                    seg.name = wps[i - 1] ? wps[i - 1].name : `Section ${i}`;
                    seg.endName = wps[i] ? wps[i].name : `Section ${i+1}`;
                }
                segments.push(seg);
            }
        }

    } else if (mode === 'auto') {
        let segStart = 0;
        let segType = points[1].smoothedGradient > 3 ? 'climb' : (points[1].smoothedGradient < -3 ? 'descent' :
            'flat');

        for (let i = 2; i < points.length; i++) {
            const newType = points[i].smoothedGradient > 3 ? 'climb' : (points[i].smoothedGradient < -3 ? 'descent' :
                'flat');

            if (newType !== segType) {
                const segDist = points[i - 1].distance - points[segStart].distance;
                if (segDist >= 0.2) {
                    segments.push(createSegment(points, segStart, i - 1, segType));
                }
                segStart = i - 1;
                segType = newType;
            }
        }

        const lastSegDist = points[points.length - 1].distance - points[segStart].distance;
        if (lastSegDist >= 0.2) {
            segments.push(createSegment(points, segStart, points.length - 1, segType));
        }

    } else {
        // ── Distance-based segments (1km / 5km etc.): absolute target boundaries with linear interpolation ──
        const segSize = mode / 1000;
        const totalDist = points[points.length - 1].distance;
        // Integer number of full segments (floor), with epsilon for floating-point edge cases
        const numFullSegs = Math.floor(totalDist / segSize + 1e-10);

        let segStartIdx = 0;

        for (let seg = 0; seg < numFullSegs; seg++) {
            const targetDist = (seg + 1) * segSize;

            let i = segStartIdx + 1;
            while (i < points.length && points[i].distance < targetDist) i++;
            if (i >= points.length) break;

            const prev = points[i - 1];
            const curr = points[i];
            if (Math.abs(curr.distance - targetDist) < 1e-12) {
                segments.push(createSegment(points, segStartIdx, i, 'auto'));
                segStartIdx = i;
            } else {
                const segLen = curr.distance - prev.distance;
                if (segLen < 1e-12) {
                    segStartIdx = i;
                    continue;
                }
                const t = (targetDist - prev.distance) / segLen;
                const vpt = {
                    lat: prev.lat + (curr.lat - prev.lat) * t,
                    lon: prev.lon + (curr.lon - prev.lon) * t,
                    ele: prev.ele + (curr.ele - prev.ele) * t,
                    distance: targetDist,
                    horizontalDistance: prev.horizontalDistance + (curr.horizontalDistance - prev.horizontalDistance) * t,
                    gradient: curr.gradient,
                    smoothedGradient: curr.smoothedGradient
                };
                points.splice(i, 0, vpt);
                segments.push(createSegment(points, segStartIdx, i, 'auto'));
                segStartIdx = i;
            }
        }

        // Remainder section: covers the remaining distance less than one full section
        if (segStartIdx < points.length - 1) {
            const remDist = points[points.length - 1].distance - points[segStartIdx].distance;
            if (remDist > segSize * 0.005) {  // > 0.5% of segSize (e.g. 5m for 1km), skip tiny remainders
                segments.push(createSegment(points, segStartIdx, points.length - 1, 'auto'));
            }
        }
    }

    return segments;
}
function createSegment(points, startIdx, endIdx, type) {
    const startPt = points[startIdx];
    const endPt = points[endIdx];
    const distance = endPt.distance - startPt.distance;
    const horizontalDistance = (endPt.horizontalDistance || 0) - (startPt.horizontalDistance || 0);

    const mode = elevationMode || 'raw';
    const elevResult = ElevationCalculator.computeSegment(points, startIdx, endIdx, mode);
    const ascent = elevResult.ascent;
    const descent = elevResult.descent;

    let maxUphillGrad = 0;
    let maxDownhillGrad = 0;
    let uphillAscent = 0;
    let downhillDescent = 0;
    let uphillHorizontalDist = 0;
    let downhillHorizontalDist = 0;

    for (let i = startIdx + 1; i <= endIdx; i++) {
        const grad = points[i].smoothedGradient;
        const absGrad = Math.abs(grad);

        const segHorizontalDist = (points[i].horizontalDistance || 0) - (points[i - 1].horizontalDistance || 0);

        if (grad > 1) {
            maxUphillGrad = Math.max(maxUphillGrad, grad);
            uphillAscent += Math.max(0, points[i].ele - points[i - 1].ele);
            uphillHorizontalDist += segHorizontalDist;
        } else if (grad < -1) {
            maxDownhillGrad = Math.min(maxDownhillGrad, grad);
            downhillDescent += Math.max(0, points[i - 1].ele - points[i].ele);
            downhillHorizontalDist += segHorizontalDist;
        }
    }

    const uphillAvg = uphillHorizontalDist > 0 ? (uphillAscent / (uphillHorizontalDist * 1000)) * 100 : 0;
    const downhillAvg = downhillHorizontalDist > 0 ? (downhillDescent / (downhillHorizontalDist * 1000)) * 100 : 0;

    if (type === 'auto') {
        const totalChange = uphillAscent + downhillDescent;
        if (totalChange === 0) {
            type = 'flat';
        } else {
            const ascentRatio = uphillAscent / totalChange;
            if (ascentRatio >= 0.6) {
                type = 'climb';
            } else if (ascentRatio <= 0.4) {
                type = 'descent';
            } else {
                type = 'mixed';
            }
        }
    }

    const baseTime = (distance / 5) * 60;
    const elevTime = ascent / 10;
    const steepAdjust = Math.max(maxUphillGrad, Math.abs(maxDownhillGrad)) > 15 ? (Math.max(maxUphillGrad, Math
        .abs(maxDownhillGrad)) - 15) * 0.5 : 0;
    const segTime = (baseTime + elevTime + steepAdjust) / 60;

    const segDiff = Math.min(100, (distance / 5) * 10 + (ascent / 300) * 20 + (Math.max(maxUphillGrad, Math.abs(
        maxDownhillGrad)) / 35) * 30);

    return {
        startIdx,
        endIdx,
        distance,
        ascent,
        descent,
        uphillAvg,
        downhillAvg,
        maxUphillGrad,
        maxDownhillGrad,
        type,
        time: segTime,
        difficulty: segDiff,
        startEle: startPt.ele,
        endEle: endPt.ele,
        startDist: startPt.distance,
        endDist: endPt.distance
    };
}
function calculateGradientDistribution(data) {
    const points = data.points;

    const upColors = UPHILL_GRADIENT_COLORS;
    const downColors = DOWNHILL_GRADIENT_COLORS;

    const uphill = [
        { name: 'Flat (≤5%)', color: upColors[0], distance: 0, level: 0,
            tip: 'Walk at a comfortable pace and keep breathing steady.' },
        { name: 'Gentle (5-10%)', color: upColors[1], distance: 0, level: 1,
            tip: 'Ease off a little, lean forward, take shorter steps.' },
        { name: 'Moderate (10-15%)', color: upColors[2], distance: 0, level: 2,
            tip: 'Poles help here. Shorten your stride and find a rhythm.' },
        { name: 'Steep (15-25%)', color: upColors[3], distance: 0, level: 3,
            tip: 'Use switchbacks. Stop often, drink, eat.' },
        { name: 'Very Steep (25-35%)', color: upColors[4], distance: 0, level: 4,
            tip: 'Use your hands for balance. Test every foothold.' },
        { name: 'Extremely Steep (>35%)', color: upColors[5], distance: 0, level: 5,
            tip: 'Serious terrain. Reroute if you can; otherwise bring proper gear and protection.' }
    ];

    const downhill = [
        { name: 'Flat (≤5%)', color: downColors[0], distance: 0, level: 0,
            tip: 'Walk normally and watch for uneven or slippery surfaces.' },
        { name: 'Gentle (5-10%)', color: downColors[1], distance: 0, level: 1,
            tip: 'Keep knees soft, step deliberately, don\'t rush.' },
        { name: 'Moderate (10-15%)', color: downColors[2], distance: 0, level: 2,
            tip: 'Poles save your knees and steady your footing.' },
        { name: 'Steep (15-25%)', color: downColors[3], distance: 0, level: 3,
            tip: 'Place each step carefully. No jumping or running down.' },
        { name: 'Very Steep (25-35%)', color: downColors[4], distance: 0, level: 4,
            tip: 'Face the slope, stay low, use handholds.' },
        { name: 'Extremely Steep (>35%)', color: downColors[5], distance: 0, level: 5,
            tip: 'Technical terrain with real fall risk. Know scrambling or rope techniques.' }
    ];

    for (let i = 1; i < points.length; i++) {
        const segDist = points[i].distance - points[i - 1].distance;
        const grad = points[i].smoothedGradient;
        const level = getGradientLevel(grad);

        if (grad > 0) {
            uphill[level].distance += segDist;
        } else {
            downhill[level].distance += segDist;
        }
    }

    const total = data.totalDistance;
    uphill.forEach(l => l.percentage = (l.distance / total) * 100);
    downhill.forEach(l => l.percentage = (l.distance / total) * 100);

    return { uphill, downhill };
}


