/* TrailScope module: chart.js — generated by JS modularization build. */
        function drawChart() {
            if (!trackData) return;

            const canvas = chartCanvas;
            const ctx = chartCtx;
            const dpr = window.devicePixelRatio || 1;
            const rect = canvas.getBoundingClientRect();

            canvas.width = rect.width * dpr;
            canvas.height = rect.height * dpr;
            ctx.scale(dpr, dpr);

            const W = rect.width;
            const H = rect.height;
            let padding = { top: 30, right: 50, bottom: 45, left: 60 };
            if (IS_MOBILE) {
                padding.left = 60;
                padding.right = 30;
            }
            const chartW = W - padding.left - padding.right;
            const chartH = H - padding.top - padding.bottom;

            ctx.clearRect(0, 0, W, H);

            const points = trackData.points;
            const maxDist = trackData.totalDistance;
            const minEle = trackData.minElevation;
            const maxEle = trackData.maxElevation;
            const eleRange = Math.max(50, maxEle - minEle);
            const elePadding = eleRange * 0.1;

            const visibleRange = maxDist / zoomLevel;
            const centerDist = maxDist * zoomCenter;
            let viewStart = Math.max(0, centerDist - visibleRange / 2);
            let viewEnd = Math.min(maxDist, viewStart + visibleRange);
            if (viewEnd - viewStart < visibleRange) {
                viewStart = Math.max(0, viewEnd - visibleRange);
            }

            const xScale = (d) => padding.left + ((d - viewStart) / (viewEnd - viewStart)) * chartW;
            const yScale = (e) => padding.top + chartH - ((e - minEle + elePadding) / (eleRange + 2 * elePadding)) * chartH;

            ctx.strokeStyle = 'rgba(122, 148, 113, 0.12)';
            ctx.lineWidth = 1;
            ctx.font = '11px Inter, sans-serif';
            ctx.fillStyle = 'rgba(45, 74, 53, 0.5)';

            const ySteps = 5;
            for (let i = 0; i <= ySteps; i++) {
                const y = padding.top + (chartH / ySteps) * i;
                const elev = maxEle + elePadding - ((eleRange + 2 * elePadding) / ySteps) * i;

                ctx.beginPath();
                ctx.moveTo(padding.left, y);
                ctx.lineTo(W - padding.right, y);
                ctx.stroke();

                ctx.textAlign = 'right';
                ctx.fillText(UnitHelper.elevationLabel(elev, 0), padding.left - 8, y + 4);
            }

            let xSteps = Math.min(10, Math.ceil(viewEnd - viewStart));
            if (IS_MOBILE) xSteps = 4;

            for (let i = 0; i <= xSteps; i++) {
                const dist = viewStart + ((viewEnd - viewStart) / xSteps) * i;
                const x = xScale(dist);

                ctx.beginPath();
                ctx.moveTo(x, padding.top);
                ctx.lineTo(x, padding.top + chartH);
                ctx.stroke();

                ctx.textAlign = 'center';
                ctx.fillText(UnitHelper.distanceLabel(dist, 1), x, H - padding.bottom + 18);
            }

            if (activeSegmentIdx >= 0) {
                const segments = analyzeSegments(trackData, segmentMode);
                if (activeSegmentIdx < segments.length) {
                    const seg = segments[activeSegmentIdx];
                    if (seg && seg.startIdx !== undefined && seg.endIdx !== undefined &&
                        seg.startIdx >= 0 && seg.endIdx >= 0 &&
                        seg.startIdx < points.length && seg.endIdx < points.length) {
                        const segStartX = xScale(points[seg.startIdx].distance);
                        const segEndX = xScale(points[seg.endIdx].distance);

                        const clipStartX = Math.max(segStartX, padding.left);
                        const clipEndX = Math.min(segEndX, W - padding.right);

                        if (clipEndX > clipStartX) {
                            ctx.save();
                            ctx.beginPath();
                            ctx.rect(padding.left, padding.top, chartW, chartH);
                            ctx.clip();

                            ctx.fillStyle = 'rgba(212, 160, 23, 0.15)';
                            ctx.fillRect(clipStartX, padding.top, clipEndX - clipStartX, chartH);

                            ctx.strokeStyle = 'rgba(212, 160, 23, 0.5)';
                            ctx.lineWidth = 1;
                            ctx.setLineDash([4, 4]);
                            ctx.beginPath();
                            ctx.moveTo(segStartX, padding.top);
                            ctx.lineTo(segStartX, padding.top + chartH);
                            ctx.moveTo(segEndX, padding.top);
                            ctx.lineTo(segEndX, padding.top + chartH);
                            ctx.stroke();
                            ctx.setLineDash([]);

                            ctx.restore();
                        }
                    }
                }
            }

            ctx.save();
            ctx.beginPath();
            ctx.rect(padding.left, padding.top, chartW, chartH);
            ctx.clip();

            let firstVisibleIdx = 0;
            for (let i = 0; i < points.length; i++) {
                if (points[i].distance >= viewStart) {
                    firstVisibleIdx = i;
                    break;
                }
            }
            let lastVisibleIdx = points.length - 1;
            for (let i = points.length - 1; i >= 0; i--) {
                if (points[i].distance <= viewEnd) {
                    lastVisibleIdx = i;
                    break;
                }
            }

            ctx.beginPath();
            ctx.moveTo(xScale(points[firstVisibleIdx].distance), yScale(points[firstVisibleIdx].ele));

            for (let i = firstVisibleIdx + 1; i <= lastVisibleIdx; i++) {
                ctx.lineTo(xScale(points[i].distance), yScale(points[i].ele));
            }

            ctx.lineTo(xScale(points[lastVisibleIdx].distance), padding.top + chartH);
            ctx.lineTo(xScale(points[firstVisibleIdx].distance), padding.top + chartH);
            ctx.closePath();

            const fillGradient = ctx.createLinearGradient(0, padding.top, 0, padding.top + chartH);
            fillGradient.addColorStop(0, 'rgba(122, 148, 113, 0.3)');
            fillGradient.addColorStop(1, 'rgba(122, 148, 113, 0.05)');
            ctx.fillStyle = fillGradient;
            ctx.fill();

            let startIdx = 0;
            for (let i = 0; i < points.length; i++) {
                if (points[i].distance >= viewStart) {
                    startIdx = Math.max(0, i - 1);
                    break;
                }
            }
            let endIdx = points.length - 1;
            for (let i = points.length - 1; i >= 0; i--) {
                if (points[i].distance <= viewEnd) {
                    endIdx = Math.min(points.length - 1, i + 1);
                    break;
                }
            }

            for (let i = startIdx + 1; i <= endIdx; i++) {
                let color;
                if (colorMode === 'elevation') {
                    color = getElevationColor(points[i].ele, minEle, maxEle);
                } else {
                    const avgGrad = (points[i].smoothedGradient + points[i - 1].smoothedGradient) / 2;
                    color = getGradientColor(avgGrad);
                }
                ctx.strokeStyle = color;
                ctx.lineWidth = 2.5;
                ctx.lineCap = 'round';
                ctx.lineJoin = 'round';

                ctx.beginPath();
                ctx.moveTo(xScale(points[i - 1].distance), yScale(points[i - 1].ele));
                ctx.lineTo(xScale(points[i].distance), yScale(points[i].ele));
                ctx.stroke();
            }

            ctx.restore();

            if (showAnnotations) {
                drawAnnotations(ctx, points, xScale, yScale, padding, chartW, chartH, viewStart, viewEnd);
            }

            drawStartEndMarkers(ctx, points, xScale, yScale, viewStart, viewEnd);

            // ★★★ 航路点绘制：根据三状态决定 ★★★
            if (waypointDisplayMode !== 'hide-all') {
                const showNames = (waypointDisplayMode === 'show-names');
                drawWaypoints(ctx, trackData.waypoints, xScale, yScale, viewStart, viewEnd, showNames);
            }

            if (IS_MOBILE && touchState.vlineActive && touchState.vlineIdx >= 0) {
                const pt = points[touchState.vlineIdx];
                if (pt && pt.distance >= viewStart && pt.distance <= viewEnd) {
                    const x = xScale(pt.distance);
                    ctx.save();
                    ctx.strokeStyle = 'rgba(26, 46, 31, 0.4)';
                    ctx.lineWidth = 1.5;
                    ctx.setLineDash([4, 4]);
                    ctx.beginPath();
                    ctx.moveTo(x, padding.top);
                    ctx.lineTo(x, padding.top + chartH);
                    ctx.stroke();
                    ctx.setLineDash([]);
                    ctx.restore();

                    const y = yScale(pt.ele);
                    ctx.fillStyle = '#1a2e1f';
                    ctx.beginPath();
                    ctx.arc(x, y, 6, 0, Math.PI * 2);
                    ctx.fill();
                    ctx.fillStyle = '#f5f1e8';
                    ctx.beginPath();
                    ctx.arc(x, y, 3, 0, Math.PI * 2);
                    ctx.fill();
                }
            }

            if (!IS_MOBILE && hoveredPointIdx >= 0) {
                const pt = points[hoveredPointIdx];
                if (pt.distance >= viewStart && pt.distance <= viewEnd) {
                    const x = xScale(pt.distance);
                    ctx.save();
                    ctx.strokeStyle = 'rgba(26, 46, 31, 0.4)';
                    ctx.lineWidth = 1.5;
                    ctx.setLineDash([4, 4]);
                    ctx.beginPath();
                    ctx.moveTo(x, padding.top);
                    ctx.lineTo(x, padding.top + chartH);
                    ctx.stroke();
                    ctx.setLineDash([]);
                    ctx.restore();

                    const y = yScale(pt.ele);
                    ctx.fillStyle = '#1a2e1f';
                    ctx.beginPath();
                    ctx.arc(x, y, 6, 0, Math.PI * 2);
                    ctx.fill();
                    ctx.fillStyle = '#f5f1e8';
                    ctx.beginPath();
                    ctx.arc(x, y, 3, 0, Math.PI * 2);
                    ctx.fill();
                }
            }

            ctx.fillStyle = 'rgba(45, 74, 53, 0.7)';
            ctx.font = '600 12px Inter, sans-serif';
            ctx.textAlign = 'center';
            ctx.fillText('Distance (' + UnitHelper.distanceUnit() + ')', W / 2, H - 8);

            ctx.save();
            ctx.translate(15, H / 2);
            ctx.rotate(-Math.PI / 2);
            ctx.fillText('Elevation (' + UnitHelper.elevationUnit() + ')', 0, 0);
            ctx.restore();

            canvas._scale = { xScale, yScale, padding, chartW, chartH, W, H, viewStart, viewEnd };
        }
        function drawStartEndMarkers(ctx, points, xScale, yScale, viewStart, viewEnd) {
            if (points[0].distance >= viewStart && points[0].distance <= viewEnd) {
                const x = xScale(points[0].distance);
                const y = yScale(points[0].ele);

                ctx.fillStyle = '#5c7a52';
                ctx.beginPath();
                ctx.arc(x, y, 7, 0, Math.PI * 2);
                ctx.fill();

                ctx.fillStyle = '#fff';
                ctx.beginPath();
                ctx.arc(x, y, 3.5, 0, Math.PI * 2);
                ctx.fill();

                ctx.font = '600 10px Inter, sans-serif';
                ctx.textAlign = 'center';
                const labelText = 'Start';
                const textWidth = ctx.measureText(labelText).width;

                ctx.fillStyle = '#5c7a52';
                ctx.beginPath();
                ctx.roundRect(x - textWidth / 2 - 6, y - 28, textWidth + 12, 16, 8);
                ctx.fill();

                ctx.fillStyle = '#fff';
                ctx.fillText(labelText, x, y - 16);
            }

            const lastPt = points[points.length - 1];
            if (lastPt.distance >= viewStart && lastPt.distance <= viewEnd) {
                const x = xScale(lastPt.distance);
                const y = yScale(lastPt.ele);

                ctx.fillStyle = '#c54b3c';
                ctx.beginPath();
                ctx.arc(x, y, 7, 0, Math.PI * 2);
                ctx.fill();

                ctx.fillStyle = '#fff';
                ctx.beginPath();
                ctx.arc(x, y, 3.5, 0, Math.PI * 2);
                ctx.fill();

                ctx.font = '600 10px Inter, sans-serif';
                ctx.textAlign = 'center';
                const labelText = 'Finish';
                const textWidth = ctx.measureText(labelText).width;

                ctx.fillStyle = '#c54b3c';
                ctx.beginPath();
                ctx.roundRect(x - textWidth / 2 - 6, y - 28, textWidth + 12, 16, 8);
                ctx.fill();

                ctx.fillStyle = '#fff';
                ctx.fillText(labelText, x, y - 16);
            }
        }
        function drawWaypoints(ctx, waypoints, xScale, yScale, viewStart, viewEnd, showNames) {
            waypoints.forEach((wp) => {
                if (wp.distance < viewStart || wp.distance > viewEnd) return;

                const x = xScale(wp.distance);
                const y = yScale(wp.elevation);

                ctx.fillStyle = '#8b7355';
                ctx.strokeStyle = '#fff';
                ctx.lineWidth = 2;

                ctx.beginPath();
                ctx.moveTo(x, y - 6);
                ctx.lineTo(x + 6, y);
                ctx.lineTo(x, y + 6);
                ctx.lineTo(x - 6, y);
                ctx.closePath();
                ctx.fill();
                ctx.stroke();

                if (showNames) {
                    const shortName = wp.name.length > 8 ? wp.name.substring(0, 7) + '…' : wp.name;
                    ctx.font = '500 10px Inter, sans-serif';
                    ctx.textAlign = 'center';
                    ctx.textBaseline = 'alphabetic';
                    const textWidth = ctx.measureText(shortName).width;

                    ctx.fillStyle = 'rgba(139, 115, 85, 0.9)';
                    ctx.beginPath();
                    ctx.roundRect(x - textWidth / 2 - 5, y + 12, textWidth + 10, 14, 7);
                    ctx.fill();

                    ctx.fillStyle = '#fff';
                    ctx.fillText(shortName, x, y + 22);
                }
            });
        }
        function drawAnnotations(ctx, points, xScale, yScale, padding, chartW, chartH, viewStart, viewEnd) {
            const segments = [];
            let currentSeg = { type: points[1].gradient > 0 ? 'climb' : 'descent', start: 0, end: 1, ascent: 0,
            descent: 0 };

            for (let i = 1; i < points.length; i++) {
                const isClimb = points[i].smoothedGradient > 1;
                const isDescent = points[i].smoothedGradient < -1;

                if (currentSeg.type === 'climb' && isClimb) {
                    currentSeg.end = i;
                    currentSeg.ascent += Math.max(0, points[i].ele - points[i - 1].ele);
                } else if (currentSeg.type === 'descent' && isDescent) {
                    currentSeg.end = i;
                    currentSeg.descent += Math.max(0, points[i - 1].ele - points[i].ele);
                } else {
                    if (currentSeg.end - currentSeg.start > 5) {
                        segments.push({ ...currentSeg });
                    }
                    currentSeg = { type: isClimb ? 'climb' : (isDescent ? 'descent' : 'flat'), start: i, end: i,
                        ascent: 0, descent: 0 };
                }
            }
            if (currentSeg.end - currentSeg.start > 5) {
                segments.push({ ...currentSeg });
            }

            const significant = segments.filter(s => s.ascent > 30 || s.descent > 30);
            significant.sort((a, b) => (b.ascent + b.descent) - (a.ascent + a.descent));
            const topSegments = significant.slice(0, 6);

            topSegments.forEach((seg) => {
                const startPt = points[seg.start];
                const endPt = points[seg.end];
                const midIdx = Math.floor((seg.start + seg.end) / 2);
                const midPt = points[midIdx];

                if (midPt.distance < viewStart || midPt.distance > viewEnd) return;

                const x = xScale(midPt.distance);
                const y = yScale(midPt.ele);

                const isClimb = seg.type === 'climb';
                const color = isClimb ? '#c54b3c' : '#3a6b8a';
                const label = isClimb ? '↑' : '↓';
                const value = isClimb ? seg.ascent : seg.descent;

                ctx.fillStyle = color;
                ctx.beginPath();
                ctx.arc(x, y, 5, 0, Math.PI * 2);
                ctx.fill();

                ctx.fillStyle = '#fff';
                ctx.beginPath();
                ctx.arc(x, y, 2.5, 0, Math.PI * 2);
                ctx.fill();

                const labelY = isClimb ? y - 18 : y + 22;
                const labelText = label + UnitHelper.elevationLabel(value, 0);

                ctx.font = '600 10px Inter, sans-serif';
                ctx.textAlign = 'center';

                const textWidth = ctx.measureText(labelText).width;
                ctx.fillStyle = 'rgba(26, 46, 31, 0.9)';
                ctx.beginPath();
                ctx.roundRect(x - textWidth / 2 - 6, labelY - 8, textWidth + 12, 16, 8);
                ctx.fill();

                ctx.fillStyle = '#f5f1e8';
                ctx.fillText(labelText, x, labelY + 4);

                ctx.strokeStyle = 'rgba(26, 46, 31, 0.3)';
                ctx.lineWidth = 1;
                ctx.setLineDash([2, 2]);
                ctx.beginPath();
                ctx.moveTo(x, y);
                ctx.lineTo(x, labelY + (isClimb ? 4 : -4));
                ctx.stroke();
                ctx.setLineDash([]);
            });

            const maxIdx = points.reduce((maxI, p, i, arr) => p.ele > arr[maxI].ele ? i : maxI, 0);
            const minIdx = points.reduce((minI, p, i, arr) => p.ele < arr[minI].ele ? i : minI, 0);

            [
                { idx: maxIdx, label: 'HIGH', color: '#d4a017', offset: -25 },
                { idx: minIdx, label: 'LOW', color: '#3a6b8a', offset: 25 }
            ].forEach(({ idx, label, color, offset }) => {
                if (points[idx].distance < viewStart || points[idx].distance > viewEnd) return;

                const x = xScale(points[idx].distance);
                const y = yScale(points[idx].ele);

                ctx.fillStyle = color;
                ctx.beginPath();
                if (offset < 0) {
                    ctx.moveTo(x, y - 4);
                    ctx.lineTo(x - 5, y - 12);
                    ctx.lineTo(x + 5, y - 12);
                } else {
                    ctx.moveTo(x, y + 4);
                    ctx.lineTo(x - 5, y + 12);
                    ctx.lineTo(x + 5, y + 12);
                }
                ctx.closePath();
                ctx.fill();

                ctx.font = '600 10px Inter, sans-serif';
                ctx.textAlign = 'center';
                const labelText = label + ' ' + UnitHelper.elevationLabel(points[idx].ele, 0);
                const textWidth = ctx.measureText(labelText).width;

                ctx.fillStyle = color;
                ctx.beginPath();
                ctx.roundRect(x - textWidth / 2 - 6, y + offset - 8, textWidth + 12, 16, 8);
                ctx.fill();

                ctx.fillStyle = '#fff';
                ctx.fillText(labelText, x, y + offset + 4);
            });
        }
