/* TrailScope module: gpx.js — generated by JS modularization build. */
function parseGPX(gpxText) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(gpxText, 'text/xml');

    const points = [];
    let isRtept = false;

    const trkpts = doc.querySelectorAll('trkpt');
    trkpts.forEach(pt => {
        const lat = parseFloat(pt.getAttribute('lat'));
        const lon = parseFloat(pt.getAttribute('lon'));
        const eleElem = pt.querySelector('ele');
        const timeElem = pt.querySelector('time');
        const ele = eleElem ? parseFloat(eleElem.textContent) : null;
        const time = timeElem ? new Date(timeElem.textContent) : null;

        if (!isNaN(lat) && !isNaN(lon)) {
            points.push({ lat, lon, ele, time });
        }
    });

    if (points.length === 0) {
        const rtepts = doc.querySelectorAll('rtept');
        if (rtepts.length > 0) {
            isRtept = true;
            rtepts.forEach(pt => {
                const lat = parseFloat(pt.getAttribute('lat'));
                const lon = parseFloat(pt.getAttribute('lon'));
                const eleElem = pt.querySelector('ele');
                const timeElem = pt.querySelector('time');
                const ele = eleElem ? parseFloat(eleElem.textContent) : null;
                const time = timeElem ? new Date(timeElem.textContent) : null;

                if (!isNaN(lat) && !isNaN(lon)) {
                    points.push({ lat, lon, ele, time });
                }
            });
        }
    }

    const wpts = doc.querySelectorAll('wpt');
    const waypoints = [];

    wpts.forEach(wpt => {
        const lat = parseFloat(wpt.getAttribute('lat'));
        const lon = parseFloat(wpt.getAttribute('lon'));
        const nameElem = wpt.querySelector('name');
        const eleElem = wpt.querySelector('ele');
        const descElem = wpt.querySelector('desc');
        const name = nameElem ? nameElem.textContent : 'Untitled Waypoint';
        const ele = eleElem ? parseFloat(eleElem.textContent) : null;
        const desc = descElem ? descElem.textContent : '';

        if (!isNaN(lat) && !isNaN(lon)) {
            waypoints.push({ lat, lon, name, ele, desc });
        }
    });

    return { points, waypoints, isRtept };
}
function processTrack(points, waypoints) {
    if (points.length < 2) return null;

    let hasElevation = points.some(p => p.ele !== null);
    if (!hasElevation) {
        points.forEach((p, i) => {
            p.ele = 800 + Math.sin(i * 0.05) * 200 + Math.sin(i * 0.15) * 100 + Math.random() * 20;
        });
    } else {
        for (let i = 0; i < points.length; i++) {
            if (points[i].ele === null) {
                let prev = i - 1,
                    next = i + 1;
                while (prev >= 0 && points[prev].ele === null) prev--;
                while (next < points.length && points[next].ele === null) next++;
                if (prev >= 0 && next < points.length) {
                    points[i].ele = (points[prev].ele + points[next].ele) / 2;
                } else if (prev >= 0) {
                    points[i].ele = points[prev].ele;
                } else if (next < points.length) {
                    points[i].ele = points[next].ele;
                }
            }
        }
    }

    let totalDistance = 0;
    let totalHorizontalDistance = 0;
    let maxElevation = -Infinity;
    let minElevation = Infinity;

    let uphillDistance = 0;
    let downhillDistance = 0;
    let flatDistance = 0;
    let uphillMaxGradient = 0;
    let downhillMaxGradient = 0;
    let uphillAvgGradient = 0;
    let downhillAvgGradient = 0;
    let uphillGradientSum = 0;
    let downhillGradientSum = 0;
    let uphillCount = 0;
    let downhillCount = 0;

    points[0].distance = 0;
    points[0].horizontalDistance = 0;
    points[0].gradient = 0;

    for (let i = 1; i < points.length; i++) {
        const horizontalDist = haversine(points[i - 1].lat, points[i - 1].lon, points[i].lat, points[i].lon);
        const elevDiff = points[i].ele - points[i - 1].ele;

        const dist3D = calculate3DDistance(
            points[i - 1].lat, points[i - 1].lon, points[i - 1].ele,
            points[i].lat, points[i].lon, points[i].ele
        );

        totalDistance += dist3D;
        totalHorizontalDistance += horizontalDist;
        points[i].distance = totalDistance;
        points[i].horizontalDistance = totalHorizontalDistance;

        if (points[i].ele > maxElevation) maxElevation = points[i].ele;
        if (points[i].ele < minElevation) minElevation = points[i].ele;

        const gradient = horizontalDist > 0 ? (elevDiff / (horizontalDist * 1000)) * 100 : 0;
        points[i].gradient = gradient;

        if (gradient > 1) {
            uphillDistance += dist3D;
            uphillGradientSum += gradient;
            uphillCount++;
        } else if (gradient < -1) {
            downhillDistance += dist3D;
            downhillGradientSum += gradient;
            downhillCount++;
        } else {
            flatDistance += dist3D;
        }
    }

    uphillAvgGradient = uphillCount > 0 ? uphillGradientSum / uphillCount : 0;
    downhillAvgGradient = downhillCount > 0 ? downhillGradientSum / downhillCount : 0;

    const windowSize = Math.min(5, Math.floor(points.length / 10));
    if (windowSize > 1) {
        for (let i = 0; i < points.length; i++) {
            let sum = 0,
                count = 0;
            for (let j = Math.max(0, i - windowSize); j <= Math.min(points.length - 1, i + windowSize); j++) {
                sum += points[j].gradient;
                count++;
            }
            points[i].smoothedGradient = sum / count;
        }
    } else {
        points.forEach(p => p.smoothedGradient = p.gradient);
    }

    uphillMaxGradient = 0;
    downhillMaxGradient = 0;

    for (let i = 1; i < points.length; i++) {
        if (points[i].smoothedGradient > 0) {
            uphillMaxGradient = Math.max(uphillMaxGradient, points[i].smoothedGradient);
        } else if (points[i].smoothedGradient < 0) {
            downhillMaxGradient = Math.min(downhillMaxGradient, points[i].smoothedGradient);
        }
    }

    const mode = elevationMode || 'raw';
    const totalElev = ElevationCalculator.computeTotal(points, mode);
    const avgGradient = totalHorizontalDistance > 0 ? (totalElev.ascent / (totalHorizontalDistance * 1000)) * 100 : 0;

    const matchedWaypoints = waypoints.map(wp => {
        const nearestIdx = findNearestPointIndex(points, wp.lat, wp.lon);
        return {
            ...wp,
            trackIdx: nearestIdx,
            distance: points[nearestIdx].distance,
            elevation: wp.ele || points[nearestIdx].ele
        };
    });

    matchedWaypoints.sort((a, b) => a.distance - b.distance);

    const maxZoom = Math.max(1, totalDistance / 1);

    return {
        points,
        waypoints: matchedWaypoints,
        totalDistance,
        totalHorizontalDistance,
        totalAscent: totalElev.ascent,
        totalDescent: totalElev.descent,
        maxElevation,
        minElevation,
        elevationRange: maxElevation - minElevation,
        uphillDistance,
        downhillDistance,
        flatDistance,
        uphillMaxGradient,
        downhillMaxGradient,
        uphillAvgGradient,
        downhillAvgGradient,
        avgGradient,
        maxZoomLevel: maxZoom
    };
}
function getGradientLabel(gradient) {
    const absGrad = Math.abs(gradient);
    if (absGrad <= 5) return 'Flat';
    if (absGrad <= 10) return 'Gentle';
    if (absGrad <= 15) return 'Medium';
    if (absGrad <= 25) return 'Steep';
    if (absGrad <= 35) return 'Very Steep';
    return 'Extremely Steep';
}


