/* TrailScope module: init.js — generated by JS modularization build. */
document.addEventListener('DOMContentLoaded', () => {
    chartCanvas = document.getElementById('elevationChart');
    chartCtx = chartCanvas.getContext('2d');

    buildMapSourceCombobox(document.getElementById('mapSourceSelect'));

    if (IS_MOBILE) {
        const chartWrapper = document.getElementById('chartWrapper');
        if (chartWrapper) {
            chartWrapper.classList.add('mobile-hide-zoom');
        }
        document.getElementById('zoomInfo').classList.add('hidden');
        const infoDiv = document.querySelector('.text-xs.text-trail-mid\\/50.ml-auto');
        if (infoDiv) {
            infoDiv.innerHTML = '<i class="fa-solid fa-circle-info"></i> Pinch to zoom · Swipe for details · Tap outside to deselect';
        }
    }

    setUnitSystem('metric');
    setElevationMode('raw');

    // ★★★ 初始化航路点按钮 ★★★
    waypointDisplayMode = 'show-names';
    updateWaypointButton();

    const initLinkageBtn = document.getElementById('mapLinkageBtn');
    if (initLinkageBtn) {
        if (mapLinkageEnabled) {
            initLinkageBtn.classList.add('active-linkage');
            initLinkageBtn.title = 'Disable Follow Cursor';
        } else {
            initLinkageBtn.classList.remove('active-linkage');
            initLinkageBtn.title = 'Enable Follow Cursor';
        }
    }

    updateWeatherUnitLabelsAndPlaceholders();

    document.getElementById('fileInput').addEventListener('change', (e) => {
        handleFile(e.target.files[0]);
    });

    const uploadZone = document.getElementById('uploadZone');

    uploadZone.addEventListener('dragover', (e) => {
        e.preventDefault();
        uploadZone.classList.add('dragover');
    });

    uploadZone.addEventListener('dragleave', () => {
        uploadZone.classList.remove('dragover');
    });

    uploadZone.addEventListener('drop', (e) => {
        e.preventDefault();
        uploadZone.classList.remove('dragover');
        handleFile(e.dataTransfer.files[0]);
    });

    setupChartInteraction();

    let resizeTimer;
    window.addEventListener('resize', () => {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(() => {
            if (trackData && !document.getElementById('fullscreenProfile')) {
                drawChart();
                if (leafletMap) leafletMap.invalidateSize();
            }
        }, 200);
    });

    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            const href = this.getAttribute('href');

            if (href === '#upload') {
                e.preventDefault();
                const target = document.querySelector(href);
                if (target) {
                    const nav = document.querySelector('nav');
                    const navHeight = nav ? nav.offsetHeight : 0;
                    const targetPosition = target.getBoundingClientRect().top + window.pageYOffset -
                        navHeight - 10;
                    window.scrollTo({
                        top: targetPosition,
                        behavior: 'smooth'
                    });
                }
                return;
            }

            if (!trackData) {
                e.preventDefault();
                return;
            }

            e.preventDefault();
            const target = document.querySelector(href);
            if (target) {
                const nav = document.querySelector('nav');
                const navHeight = nav ? nav.offsetHeight : 0;
                const targetPosition = target.getBoundingClientRect().top + window.pageYOffset - navHeight -
                    10;
                window.scrollTo({
                    top: targetPosition,
                    behavior: 'smooth'
                });
            }
        });
    });
});
console.log('Device Type', DEVICE_TYPE, IS_MOBILE ? 'Mobile' : 'Computer');
console.log('Unit System:', unitSystem);
console.log('Elevation Mode:', elevationMode);
console.log('Follow Cursor:', mapLinkageEnabled ? 'enabled' : 'disabled');
console.log('Waypoint Display Mode:', waypointDisplayMode);


