/* TrailScope module: map-sources.js — generated by JS modularization build. */
const mapSources = {
    osm: {
        name: 'OpenStreetMap',
        url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        subdomains: 'abc',
        maxZoom: 19,
        attribution: '© OpenStreetMap contributors'
    },
 /*   windy: {
        name: 'Windy',
        url: 'https://tiles.windy.com/v1/maptiles/outdoor/256%402x/{z}/{x}/{y}',
        subdomains: '',
        maxZoom: 18,
        attribution: '© Windy'
    },*/
    opentopomap: {
        name: 'OpenTopoMap',
        url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
        subdomains: 'abc',
        maxZoom: 17,
        attribution: '© OpenTopoMap'
    },
    opencyclemap: {
        name: 'OpenCycleMap',
        url: 'https://api.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=a5dd6a2f1c934394bce6b0fb077203eb',
        subdomains: '',
        maxZoom: 18,
        attribution: '© Thunderforest'
    },
    cyclosm: {
        name: 'CyclOSM',
        url: 'https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png',
        subdomains: 'abc',
        maxZoom: 20,
        attribution: '© CyclOSM'
    },
    openhikingmap: {
        name: 'OpenHikingMap',
        url: 'https://tile.openmaps.fr/openhikingmap/{z}/{x}/{y}.png',
        subdomains: '',
        maxZoom: 18,
        attribution: '<a href="https://github.com/sletuffe/OpenTopoMap">&copy; OpenTopoMap-R</a> <a href="https://openmaps.fr/donate">❤️ Donation</a> <a href="http://www.openstreetmap.org/copyright">&copy; OpenStreetMap</a>'
    },
    googlesatellite: {
        name: 'Google Satellite',
        url: 'http://ggmap01.bosim.top:8880/gmap/{x}/{y}/{z}/lyrs=s&hl=en&scale=1/?gk=AIV4qSZ1NqAdsAjE1mhfrw&t=1718630666',
        subdomains: '',
        maxZoom: 20,
        attribution: '© Google'
    },
    googlehybrid: {
        name: 'Google Hybrid',
        url: 'http://ggmap01.bosim.top:8880/gmap/{x}/{y}/{z}/lyrs=y&hl=en&scale=1/?gk=AIV4qSZ1NqAdsAjE1mhfrw&t=1718630666',
        subdomains: '',
        maxZoom: 20,
        attribution: '© Google'
    },
    amaproad: {
        name: 'Amap Road',
        url: 'https://webrd0{s}.is.autonavi.com/appmaptile?lang=en&size=1&scale=1&style=8&x={x}&y={y}&z={z}',
        subdomains: ['1', '2', '3', '4'],
        maxZoom: 18,
        attribution: '© Amap'
    },
    amapsatellite: {
        name: 'Amap Satellite',
        url: 'https://webst0{s}.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}',
        subdomains: ['1', '2', '3', '4'],
        maxZoom: 18,
        attribution: '© Amap'
    },
    gaode_hybrid: {
        name: 'Amap Hybrid',
        maxZoom: 18,
        attribution: '© Amap',
    }
};


