/* TrailScope module: map-sources.js — generated by JS modularization build. */
const mapSources = {
    osm: {
        name: 'OpenStreetMap',
        url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        subdomains: 'abc',
        maxZoom: 19,
        attribution: '© OpenStreetMap contributors'
    },
    ESRIWorldImagery: {
        name: 'ESRI World Imagery',
        url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        subdomains: '',
        maxZoom: 19,
        attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
    },
    opentopomap: {
        name: 'OpenTopoMap',
        url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
        subdomains: 'abc',
        maxZoom: 17,
        attribution: '© OpenTopoMap'
    },
    opencyclemap: {
        name: 'OpenCycleMap',
        url: 'https://api.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=a5dd6a2f1c934394bce6b0fb077203eb',
        subdomains: '',
        maxZoom: 18,
        attribution: '© Thunderforest'
    },
    cyclosm: {
        name: 'CyclOSM',
        url: 'https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png',
        subdomains: 'abc',
        maxZoom: 20,
        attribution: '© CyclOSM'
    },
    openhikingmap: {
        name: 'OpenHikingMap',
        url: 'https://tile.openmaps.fr/openhikingmap/{z}/{x}/{y}.png',
        subdomains: '',
        maxZoom: 18,
        attribution: '<a href="https://github.com/sletuffe/OpenTopoMap">&copy; OpenTopoMap-R</a> <a href="https://openmaps.fr/donate">❤️ Donation</a> <a href="http://www.openstreetmap.org/copyright">&copy; OpenStreetMap</a>'
    },
    MapyOutdoor: {
        name: 'Mapy Outdoor',
        url: 'https://api.mapy.com/v1/maptiles/outdoor/256/{z}/{x}/{y}?apikey=dRyLZyNVqHzMf0pNCC4RGg7wrT9uNTbDQ3gJi98K1D4',
		minZoom: 0,
        maxZoom: 19,
        attribution: '<a href="https://api.mapy.com/copyright" target="_blank">&copy; Seznam.cz a.s. a další</a>'
    },
    MapyAerial: {
        name: 'Mapy Aerial',
        url: 'https://api.mapy.com/v1/maptiles/aerial/256/{z}/{x}/{y}?apikey=dRyLZyNVqHzMf0pNCC4RGg7wrT9uNTbDQ3gJi98K1D4',
		minZoom: 0,
        maxZoom: 19,
        attribution: '<a href="https://api.mapy.com/copyright" target="_blank">&copy; Seznam.cz a.s. a další</a>'
    },
    amaproad: {
        name: 'Amap Road',
        url: 'https://webrd0{s}.is.autonavi.com/appmaptile?lang=en&size=1&scale=1&style=8&x={x}&y={y}&z={z}',
        subdomains: ['1', '2', '3', '4'],
        maxZoom: 18,
        attribution: '© Amap'
    },
    amapsatellite: {
        name: 'Amap Satellite',
        url: 'https://webst0{s}.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}',
        subdomains: ['1', '2', '3', '4'],
        maxZoom: 18,
        attribution: '© Amap'
    },
    gaode_hybrid: {
        name: 'Amap Hybrid',
        maxZoom: 18,
        attribution: '© Amap',
    },
	ESRIWorldTopoMap: {
		name: 'ESRI-WorldTopoMap',
		maxZoom: 18,
		attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
	},
    tianditusatellite: {
        name: 'Tianditu Satellite',
        url: 'http://t{s}.tianditu.gov.cn/img_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=img&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=50fdf5d2464091ca4951c7c2d7e017c4',
        subdomains: ['0', '1', '2', '3', '4', '5', '6', '7'],
		tileSize: 256,
        maxZoom: 18,
        attribution: '© 天地图'
    },
};


