/* TrailScope module: map.js — generated by JS modularization build. */
function initMap() {
    if (leafletMap) return;

    leafletMap = L.map('leafletMap', {
        zoomControl: false,
        attributionControl: false,
        scrollWheelZoom: true
    }).setView([30.185, 102.065], 13);

    changeMapSource('osm');

    leafletMap.on('click', function() {
        hideWaypointInfoOverlay();
        if (IS_MOBILE) {
            clearMobileVLine();
        }
    });
}
function changeMapSource(source) {
    if (!leafletMap) return;

    if (!source) {
        source = document.getElementById('mapSourceSelect').value;
    }

    currentMapSource = source;
    useGCJ02Display = (source === 'amaproad' || source === 'amapsatellite' || source === 'gaode_hybrid');
    const config = mapSources[source];

    if (!config) return;

    const center = leafletMap.getCenter();
    const zoom = leafletMap.getZoom();

    if (currentTileLayer) {
        leafletMap.removeLayer(currentTileLayer);
        currentTileLayer = null;
    }

    if (source === 'gaode_hybrid') {
        const roadLayer = L.tileLayer(
            'https://wprd0{s}.is.autonavi.com/appmaptile?lang=en&size=1&scale=1&style=8&x={x}&y={y}&z={z}', { subdomains: ['1', '2', '3', '4'], maxZoom: 18,
                attribution: '© amap' }
        );
        const satelliteLayer = L.tileLayer(
            'https://wprd0{s}.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}', { subdomains: ['1', '2', '3', '4'], maxZoom: 18,
                attribution: '© amap' }
        );
        satelliteLayer.setZIndex(5);
        roadLayer.setZIndex(10);
        const group = L.layerGroup([roadLayer, satelliteLayer]);
        group.addTo(leafletMap);
        currentTileLayer = group;
    } else {
        const tileOptions = {
            maxZoom: config.maxZoom,
            attribution: config.attribution
        };
        if (config.subdomains) {
            tileOptions.subdomains = config.subdomains;
        }
        const newLayer = L.tileLayer(config.url, tileOptions);
        newLayer.addTo(leafletMap);
        currentTileLayer = newLayer;
    }

    const maxZoom = config.maxZoom || 18;
    leafletMap.setView(center, Math.min(zoom, maxZoom));

    document.getElementById('mapSourceSelect').value = source;
    const fsMapSource = document.getElementById('fullscreenMapSourceSelect');
    if (fsMapSource) fsMapSource.value = source;

    if (trackData) drawMap(true);
}
function drawMap(skipFit = false) {
    if (!trackData || !leafletMap) return;

    trackLayers.forEach(layer => leafletMap.removeLayer(layer));
    trackLayers = [];

    waypointMarkers.forEach(marker => leafletMap.removeLayer(marker));
    waypointMarkers = [];

    if (currentMarker) {
        leafletMap.removeLayer(currentMarker);
        currentMarker = null;
    }

    segmentHighlightLayers.forEach(layer => leafletMap.removeLayer(layer));
    segmentHighlightLayers = [];

    const points = trackData.points;

    for (let i = 1; i < points.length; i++) {
        let color;
        if (colorMode === 'elevation') {
            color = getElevationColor(points[i].ele, trackData.minElevation, trackData.maxElevation);
        } else {
            const avgGrad = (points[i].smoothedGradient + points[i - 1].smoothedGradient) / 2;
            color = getGradientColor(avgGrad);
        }

        const segment = L.polyline([
            displayLatLng(points[i - 1]),
            displayLatLng(points[i])
        ], {
            color: color,
            weight: 4,
            opacity: 0.9
        }).addTo(leafletMap);

        trackLayers.push(segment);
    }

    const startIcon = L.divIcon({
        className: '',
        html: '<div class="custom-marker start-marker"><i class="fa-solid fa-flag"></i></div>',
        iconSize: [24, 24],
        iconAnchor: [12, 12]
    });

    const startMarker = L.marker(displayLatLng(points[0]), { icon: startIcon })
        .bindTooltip('Start', { permanent: false })
        .addTo(leafletMap);
    trackLayers.push(startMarker);

    const endIcon = L.divIcon({
        className: '',
        html: '<div class="custom-marker end-marker"><i class="fa-solid fa-flag-checkered"></i></div>',
        iconSize: [24, 24],
        iconAnchor: [12, 12]
    });

    const endMarker = L.marker(displayLatLng(points[points.length - 1]), { icon: endIcon })
        .bindTooltip('Finish', { permanent: false })
        .addTo(leafletMap);
    trackLayers.push(endMarker);

    // ★★★ 只有在非 hide-all 状态下才绘制航路点 ★★★
    if (waypointDisplayMode !== 'hide-all') {
        const showNames = (waypointDisplayMode === 'show-names');
        trackData.waypoints.forEach((wp) => {
            const wpIcon = L.divIcon({
                className: '',
                html: '<div class="custom-marker"><i class="fa-solid fa-map-pin" style="font-size: 10px;"></i></div>',
                iconSize: [20, 20],
                iconAnchor: [10, 10]
            });

            const marker = L.marker(displayWaypointLatLng(wp), { icon: wpIcon })
                .addTo(leafletMap);

            if (showNames) {
                const popupContent = `
                    <div class="waypoint-popup-content">
                      <strong>${wp.name}</strong><br/>
                      <span class="waypoint-info-line">Distance: ${UnitHelper.distanceLabel(wp.distance, 2)}</span><br/>
                      <span class="waypoint-info-line">Elevation: ${UnitHelper.elevationLabel(wp.elevation, 0)}</span><br/>
                    </div>
                  `;
                marker.bindPopup(popupContent, {
                    closeButton: false,
                    offset: [0, -10],
                    autoClose: false,
                    closeOnClick: false
                });

                marker.on('mouseover', function(e) {
                    if (!isWaypointInfoPinned) {
                        marker.openPopup();
                    }
                });

                marker.on('mouseout', function(e) {
                    if (!isWaypointInfoPinned) {
                        marker.closePopup();
                    }
                });

                marker.on('click', function(e) {
                    L.DomEvent.stopPropagation(e);
                    if (isWaypointInfoPinned && selectedWaypointMarker === marker) {
                        marker.closePopup();
                        isWaypointInfoPinned = false;
                        selectedWaypointMarker = null;
                    } else {
                        marker.openPopup();
                        isWaypointInfoPinned = true;
                        selectedWaypointMarker = marker;
                    }
                });
            }

            waypointMarkers.push(marker);
        });
    }

    if (!skipFit) {
        fitMapToTrack();
    }
}
function updateMapCurrentPoint(pointIdx) {
    if (!trackData || !leafletMap) return;

    if (currentMarker) {
        leafletMap.removeLayer(currentMarker);
        currentMarker = null;
    }

    if (pointIdx < 0 || pointIdx >= trackData.points.length) {
        if (!document.getElementById('mapContainer').classList.contains('map-fullscreen-chart')) {
            document.getElementById('mapInfoOverlay').classList.add('hidden');
        }
        return;
    }

    const pt = trackData.points[pointIdx];

    const currentIcon = L.divIcon({
        className: '',
        html: '<div class="custom-marker current-marker"></div>',
        iconSize: [18, 18],
        iconAnchor: [9, 9]
    });

    currentMarker = L.marker(displayLatLng(pt), { icon: currentIcon })
        .addTo(leafletMap);

    if (mapLinkageEnabled) {
        const displayPos = displayLatLng(pt);
        leafletMap.panTo(displayPos, { animate: false });

        if (document.getElementById('mapContainer').classList.contains('map-fullscreen-chart')) {
            const profile = document.querySelector('.fullscreen-profile');
            if (profile) {
                const profileHeight = profile.getBoundingClientRect().height;
                const offsetY = profileHeight / 2;
                leafletMap.panBy([0, offsetY], { animate: false });
            }
        }
    }

    if (!document.getElementById('mapContainer').classList.contains('map-fullscreen-chart')) {
        const overlay = document.getElementById('mapInfoOverlay');
        overlay.classList.remove('hidden');

        document.getElementById('mapInfoDist').textContent = UnitHelper.distanceLabel(pt.distance, 2);

        const eleSpan = document.getElementById('mapInfoEle');
        eleSpan.textContent = UnitHelper.elevationLabel(pt.ele, 0);
        eleSpan.style.color = getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation);

        const gradSpan = document.getElementById('mapInfoGrad');
        const gradLabel = getGradientLabel(pt.smoothedGradient);
        gradSpan.textContent = (pt.smoothedGradient > 0 ? '+' : '') + pt.smoothedGradient.toFixed(1) + '% （' + gradLabel +
            '）';
        gradSpan.style.color = getGradientColor(pt.smoothedGradient);
    } else {
        const overlay = document.getElementById('mapInfoOverlay');
        overlay.classList.remove('hidden');
        document.getElementById('mapInfoDist').textContent = UnitHelper.distanceLabel(pt.distance, 2);
        const eleSpan = document.getElementById('mapInfoEle');
        eleSpan.textContent = UnitHelper.elevationLabel(pt.ele, 0);
        eleSpan.style.color = getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation);
        const gradSpan = document.getElementById('mapInfoGrad');
        const gradLabel = getGradientLabel(pt.smoothedGradient);
        gradSpan.textContent = (pt.smoothedGradient > 0 ? '+' : '') + pt.smoothedGradient.toFixed(1) + '% （' + gradLabel +
            '）';
        gradSpan.style.color = getGradientColor(pt.smoothedGradient);
    }
}
function updateMapSegmentLabel(segmentIdx, segments) {
    const segLabel = document.getElementById('mapSegmentLabel');
    const prevBtn = document.getElementById('prevSegmentBtn');
    const nextBtn = document.getElementById('nextSegmentBtn');

    if (segmentMode === 'waypoint') {
        const seg = segments[segmentIdx];
        const startName = seg.name || 'Start';
        const endName = seg.endName || 'Finish';
        segLabel.textContent = `${startName} → ${endName}`;
    } else {
        segLabel.textContent = `Section ${segmentIdx + 1}/${segments.length}`;
    }

    prevBtn.disabled = segmentIdx === 0;
    nextBtn.disabled = segmentIdx === segments.length - 1;
}


