/* TrailScope module: units.js — generated by JS modularization build. */
let unitSystem = 'metric';
const UnitHelper = {
    getSystem() { return unitSystem; },

    setSystem(sys) {
        if (sys === 'metric' || sys === 'imperial') {
            unitSystem = sys;
            document.getElementById('metricUnitBtn').classList.toggle('active', sys === 'metric');
            document.getElementById('imperialUnitBtn').classList.toggle('active', sys === 'imperial');

            // Update fixed-distance section button label (1 km ↔ 1 mi)
            const segBtn = document.getElementById('segFixedDist');
            if (segBtn) {
                segBtn.textContent = sys === 'imperial' ? '1 mi' : '1 km';
            }

            // If current section mode is distance-based, switch to the corresponding unit
            if (typeof segmentMode === 'number') {
                if (sys === 'imperial' && segmentMode === 1000) {
                    segmentMode = 1609.34;
                } else if (sys === 'metric' && segmentMode === 1609.34) {
                    segmentMode = 1000;
                }
            }

            updateWeatherUnitLabelsAndPlaceholders();
            convertWeatherInputValues();
            if (trackData) {
                updateUI();
                drawChart();
                if (hoveredPointIdx >= 0) {
                    updateMapCurrentPoint(hoveredPointIdx);
                }
                if (activeSegmentIdx >= 0) {
                    const segments = analyzeSegments(trackData, segmentMode);
                    if (activeSegmentIdx < segments.length) {
                        showMapSegmentInfo(activeSegmentIdx, segments);
                    }
                }
            }
        }
    },

    distance(km, decimals) {
        decimals = decimals !== undefined ? decimals : 2;
        if (unitSystem === 'imperial') {
            return (km * 0.621371).toFixed(decimals);
        }
        return km.toFixed(decimals);
    },
    distanceUnit() {
        return unitSystem === 'imperial' ? 'mi' : 'km';
    },
    distanceLabel(km, decimals) {
        return this.distance(km, decimals) + ' ' + this.distanceUnit();
    },

    elevation(m, decimals) {
        decimals = decimals !== undefined ? decimals : 0;
        if (unitSystem === 'imperial') {
            return (m * 3.28084).toFixed(decimals);
        }
        return m.toFixed(decimals);
    },
    elevationUnit() {
        return unitSystem === 'imperial' ? 'ft' : 'm';
    },
    elevationLabel(m, decimals) {
        return this.elevation(m, decimals) + ' ' + this.elevationUnit();
    },

    pace(minPerKm, decimals) {
        decimals = decimals !== undefined ? decimals : 0;
        if (unitSystem === 'imperial') {
            return (minPerKm * 1.60934).toFixed(decimals);
        }
        return minPerKm.toFixed(decimals);
    },
    paceUnit() {
        return unitSystem === 'imperial' ? 'min/mi' : 'min/km';
    },
    paceLabel(minPerKm, decimals) {
        return this.pace(minPerKm, decimals) + ' ' + this.paceUnit();
    },

    volume(liters, decimals) {
        decimals = decimals !== undefined ? decimals : 1;
        if (unitSystem === 'imperial') {
            if (liters >= 1) {
                return (liters * 0.264172).toFixed(decimals);
            } else {
                return (liters * 33.814).toFixed(decimals);
            }
        }
        return liters.toFixed(decimals);
    },
    volumeUnit(liters) {
        if (unitSystem === 'imperial') {
            return (liters >= 1) ? 'gal' : 'fl oz';
        }
        return 'L';
    },
    volumeLabel(liters, decimals) {
        return this.volume(liters, decimals) + ' ' + this.volumeUnit(liters);
    },

    waterVolumeOz(liters) {
        return (liters * 33.814).toFixed(1);
    },
    waterVolumeLabel(liters) {
        return this.waterVolumeOz(liters) + ' oz';
    }
};
function celsiusToFahrenheit(c) { return c * 9 / 5 + 32; }
function fahrenheitToCelsius(f) { return (f - 32) * 5 / 9; }
function mpsToMph(mps) { return mps * 2.23694; }
function mphToMps(mph) { return mph / 2.23694; }
function hPaToInHg(hPa) { return hPa * 0.02952998; }
function inHgToHPa(inHg) { return inHg / 0.02952998; }
function formatTempC(c) { return Math.round(c); }
function formatTempF(f) { return Math.round(f); }
function formatPressureInHg(inHg) { return inHg.toFixed(2); }
function updateWeatherUnitLabelsAndPlaceholders() {
    const isMetric = unitSystem === 'metric';

    const tempLabel = document.getElementById('weatherTempLabel');
    const tempInput = document.getElementById('weatherTemp');
    if (tempLabel) tempLabel.textContent = 'Temperature / ' + (isMetric ? '°C' : '°F');
    if (tempInput) tempInput.placeholder = 'Unit: ' + (isMetric ? '℃' : '℉');

    const windLabel = document.getElementById('weatherWindLabel');
    const windInput = document.getElementById('weatherWind');
    if (windLabel) windLabel.textContent = 'Wind Speed / ' + (isMetric ? '(m·s⁻¹)' : '(mph)');
    if (windInput) windInput.placeholder = 'Unit: ' + (isMetric ? 'm/s' : 'mph');

    const wbLabel = document.getElementById('wetBulbLabel');
    const wbInput = document.getElementById('wetBulbTemp');
    if (wbLabel) wbLabel.textContent = 'Wet Bulb Temperature / ' + (isMetric ? '°C' : '°F');
    if (wbInput) wbInput.placeholder = 'Unit: ' + (isMetric ? '℃' : '℉');

    const dpLabel = document.getElementById('dewPointLabel');
    const dpInput = document.getElementById('dewPoint');
    if (dpLabel) dpLabel.textContent = 'Dew Point / ' + (isMetric ? '℃' : '℉');
    if (dpInput) dpInput.placeholder = 'Unit: ' + (isMetric ? '℃' : '℉');

    const pressureLabel = document.getElementById('pressureLabel');
    const pressureInput = document.getElementById('pressure');
    if (pressureLabel) pressureLabel.textContent = 'Air Pressure / ' + (isMetric ? 'hPa' : 'inHg');
    if (pressureInput) pressureInput.placeholder = 'Unit: ' + (isMetric ? 'hPa' : 'inHg');
}
function convertWeatherInputs(fromSys, toSys) {
    if (fromSys === toSys) return;

    const isFromMetric = fromSys === 'metric';
    const isToMetric = toSys === 'metric';

    const tempIds = ['weatherTemp', 'wetBulbTemp', 'dewPoint'];
    tempIds.forEach(id => {
        const el = document.getElementById(id);
        if (el && el.value !== '') {
            const val = parseFloat(el.value);
            if (!isNaN(val)) {
                let newVal;
                if (isFromMetric && !isToMetric) {
                    newVal = celsiusToFahrenheit(val);
                } else if (!isFromMetric && isToMetric) {
                    newVal = fahrenheitToCelsius(val);
                } else {
                    newVal = val;
                }
                el.value = Math.round(newVal);
            }
        }
    });

    const windEl = document.getElementById('weatherWind');
    if (windEl && windEl.value !== '') {
        const val = parseFloat(windEl.value);
        if (!isNaN(val)) {
            let newVal;
            if (isFromMetric && !isToMetric) {
                newVal = mpsToMph(val);
            } else if (!isFromMetric && isToMetric) {
                newVal = mphToMps(val);
            } else {
                newVal = val;
            }
            windEl.value = newVal.toFixed(1);
        }
    }

    const pressureEl = document.getElementById('pressure');
    if (pressureEl && pressureEl.value !== '') {
        const val = parseFloat(pressureEl.value);
        if (!isNaN(val)) {
            let newVal;
            if (isFromMetric && !isToMetric) {
                newVal = hPaToInHg(val);
                pressureEl.value = newVal.toFixed(2);
            } else if (!isFromMetric && isToMetric) {
                newVal = inHgToHPa(val);
                pressureEl.value = Math.round(newVal);
            } else {
                pressureEl.value = val;
            }
        }
    }
}
// ================================================================
// ★★★ 单位切换入口（原 HTML 内联 onclick 与 DOMContentLoaded 调用）★★★
// ================================================================
function setUnitSystem(sys) {
    UnitHelper.setSystem(sys);
}

// ★★★ 切换单位制时，把天气输入框中的数值从旧单位制换算到新单位制 ★★★
function convertWeatherInputValues() {
    const fromSys = unitSystem === 'metric' ? 'imperial' : 'metric';
    convertWeatherInputs(fromSys, unitSystem);
}


