/* TrailScope module: waypoints.js — generated by JS modularization build. */
function updateWaypointButton() {
    const btn = document.getElementById('waypointToggleBtn');
    const label = document.getElementById('waypointToggleLabel');
    const fsBtn = document.getElementById('fullscreenWaypointToggleBtn');
    const fsLabel = document.getElementById('fullscreenWaypointToggleLabel');

    let icon, text;
    if (waypointDisplayMode === 'show-names') {
        icon = 'fa-tag';
        text = 'Hide Waypoint Names';
    } else if (waypointDisplayMode === 'hide-names') {
        icon = 'fa-eye-slash';
        text = 'Hide All Waypoints';
    } else {
        icon = 'fa-tag';
        text = 'Show Waypoint Names';
    }

    if (btn) btn.innerHTML = `<i class="fa-solid ${icon}"></i> <span id="waypointToggleLabel">${text}</span>`;
    if (fsBtn) fsBtn.innerHTML = `<i class="fa-solid ${icon}"></i> <span id="fullscreenWaypointToggleLabel">${text}</span>`;
}
function showWaypointInfo(wp) {
    const info = document.getElementById('waypointInfo');
    info.classList.remove('hidden');
    document.getElementById('wpName').textContent = wp.name;
    document.getElementById('wpDetails').textContent = trackData && !trackData.hasValidElevation
        ? 'Distance ' + UnitHelper.distanceLabel(wp.distance, 2) + (wp.desc ? ' · ' + wp.desc : '')
        : 'Distance ' + UnitHelper.distanceLabel(wp.distance, 2) +
            ' · Elevation ' + UnitHelper.elevationLabel(wp.elevation, 0) +
            (wp.desc ? ' · ' + wp.desc : '');
}


