/* TrailScope module: analysis.js — generated by JS modularization build. */
        function assessDifficulty(data) {
            const { totalDistance, totalAscent, points, uphillMaxGradient, downhillMaxGradient } = data;

            const distScore = Math.min(100, (totalDistance / 40) * 100);
            const ascentScore = Math.min(100, (totalAscent / 2000) * 100);

            let steepDistance = 0;
            let verySteepDistance = 0;
            for (let i = 1; i < points.length; i++) {
                const segDist = points[i].distance - points[i - 1].distance;
                const absGrad = Math.abs(points[i].smoothedGradient);
                if (absGrad > 15) steepDistance += segDist;
                if (absGrad > 25) verySteepDistance += segDist;
            }
            const steepRatio = steepDistance / totalDistance;
            const verySteepRatio = verySteepDistance / totalDistance;
            const gradScore = Math.min(100, steepRatio * 150 + verySteepRatio * 200);

            const overall = Math.round(distScore * 0.3 + ascentScore * 0.35 + gradScore * 0.35);

            let label, color;
            if (overall < 20) { label = '休闲';
                color = '#5c7a52'; } else if (overall < 40) { label = '轻松';
                color = '#7a9471'; } else if (overall < 55) { label = '中等';
                color = '#d4a017'; } else if (overall < 70) { label = '较难';
                color = '#cd762a'; } else if (overall < 85) { label = '困难';
                color = '#c54b3c'; } else { label = '极具挑战';
                color = '#ff0000'; }

            return { overall, label, color, distScore, ascentScore, gradScore };
        }
        function toggleAdvancedPanel() {
            const panel = document.getElementById('advancedPanel');
            const toggleLabel = document.getElementById('toggleLabel');
            const toggleArrow = document.getElementById('toggleArrow');

            advancedPanelOpen = !advancedPanelOpen;

            if (advancedPanelOpen) {
                panel.classList.add('open');
                toggleLabel.textContent = '点击收起进阶气象分析项目';
                toggleArrow.classList.add('open');
            } else {
                panel.classList.remove('open');
                toggleLabel.textContent = '点击展开进阶气象分析项目';
                toggleArrow.classList.remove('open');
            }
        }
        function analyzeWeather() {
            const t = document.getElementById('weatherTemp').value.trim();
            const h = document.getElementById('weatherHumidity').value.trim();
            const w = document.getElementById('weatherWind').value.trim();
            const type = document.getElementById('weatherType').value;

            if (t === '' || h === '') {
                alert('数据不足，无法进行气象分析：\n\n· 需要同时填写温度和湿度。');
                return;
            }

            const temp = Number(t);
            const humidity = Number(h);
            const wind = w === '' ? 0 : Number(w);

            if (isNaN(temp) || isNaN(humidity) || (w !== '' && isNaN(wind))) {
                alert('温度、湿度、风速必须为数字。');
                return;
            }

            const invalid = (type.includes('雪') && (temp > 8 || humidity < 15)) ||
                temp > 45 || temp < -60 || humidity < 0 || humidity > 100;
            if (invalid) {
                alert('气象数据不符合实际情况，无法进行气象分析');
                return;
            }
            if (wind < 0 || wind > 150) {
                alert('气象数据不符合实际情况，无法进行气象分析：\n\n• 风速不符合气象观测历史数据（合理范围 0~150 m/s）');
                return;
            }

            weatherData = { temp, humidity, wind, type };

            const tips = [];
            let heatIndex = temp;

            if (temp >= 27 && humidity >= 40) {
                const T_F = temp * 9 / 5 + 32;
                const RH = humidity;

                const hi_F = -42.379 +
                    2.04901523 * T_F +
                    10.14333127 * RH -
                    0.22475541 * T_F * RH -
                    0.00683783 * T_F * T_F -
                    0.05481717 * RH * RH +
                    0.00122874 * T_F * T_F * RH +
                    0.00085282 * T_F * RH * RH -
                    0.00000199 * T_F * T_F * RH * RH;
                heatIndex = (hi_F - 32) * 5 / 9;
                if (heatIndex < temp) heatIndex = temp;
            }

            const makeTip = (icon, text, colorClass = '') => {
                return `<div class="weather-tip-row"><span class="weather-tip-icon ${colorClass}"><i class="fa-solid ${icon}"></i></span><span class="weather-tip-text ${colorClass} font-semibold">${text}</span></div>`;
            };

            if (heatIndex >= 35) {
                tips.push(makeTip('fa-temperature-full', '极端高温天气（体感温度 ≥ 35℃）：不建议进行长距离徒步，请避开高温时段，并加强补水和防暑措施。',
                    'text-accent-red'));
            } else if (heatIndex >= 30) {
                tips.push(makeTip('fa-temperature-full', '高温高湿环境（体感温度 ≥ 30℃）：增加饮水和电解质补充，注意中暑风险。', 'text-accent-amber'));
            }
            if (type.includes('台风') || wind >= 32) {
                tips.push(makeTip('fa-hurricane', '台风或强风天气：禁止出行，请取消户外徒步计划。', 'text-accent-red'));
            }
            if (temp <= 5) {
                tips.push(makeTip('fa-temperature-empty', '低温环境：注意保暖，携带保暖衣物和保温装备。', 'text-accent-blue'));
            }
            if (type.includes('阵雨') || type.includes('小雨')) {
                tips.push(makeTip('fa-cloud-rain', '降雨天气：携带防水装备，注意湿滑路面。', 'text-accent-blue'));
            }
            if (type.includes('中雨')) {
                tips.push(makeTip('fa-cloud-showers-heavy', '大雨天气：禁止出行，请取消户外徒步计划。', 'text-accent-red'));
            }
            if (wind >= 8) {
                tips.push(makeTip('fa-wind', '大风：注意失温风险，增加防风层。', 'text-accent-blue'));
            }

            const rows = [];

            if (tips.length) {
                tips.forEach(tip => rows.push(tip));
            } else {
                rows.push(makeTip('fa-check', '当前气象条件未发现额外风险。', 'text-trail-moss'));
            }

            if (advancedPanelOpen) {
                const wetBulb = document.getElementById('wetBulbTemp').value.trim();
                const dewPoint = document.getElementById('dewPoint').value.trim();
                const solarRad = document.getElementById('solarRadiation').value.trim();
                const pressure = document.getElementById('pressure').value.trim();

                let directRatio = document.getElementById('directRadiationRatio').value.trim();
                let solarAngle = document.getElementById('solarAltitudeAngle').value.trim();

                if (directRatio === '') directRatio = '0.6';
                if (solarAngle === '') solarAngle = '45';

                const allAdvancedFilled = wetBulb !== '' && dewPoint !== '' && solarRad !== '' &&
                    pressure !== '';

                if (!allAdvancedFilled) {
                    rows.push(makeTip('fa-triangle-exclamation', '进阶气象分析所需数据不完整，无法进行进阶气象分析。', 'text-accent-amber'));
                } else {
                    const wb = Number(wetBulb);
                    const dp = Number(dewPoint);
                    const S = Number(solarRad);
                    const p = Number(pressure);
                    const dr = Number(directRatio);
                    const angleDeg = Number(solarAngle);

                    if (isNaN(wb) || isNaN(dp) || isNaN(S) || isNaN(p) || isNaN(dr) || isNaN(angleDeg)) {
                        alert('所有进阶气象数据必须为数字。');
                        return;
                    }

                    const errors = [];
                    if (wind < 0 || wind > 150) {
                        errors.push('风速不符合气象观测历史数据（合理范围 0~150 m/s）');
                    }
                    if (S < 0 || S > 1400) {
                        errors.push('太阳辐射强度超出合理范围（0~1400 W/m²）');
                    }
                    if (p < 200 || p > 1200) {
                        errors.push('气压数值不符合气象观测历史数据（合理范围 200~1200 hPa）');
                    }
                    if (wb > temp) {
                        errors.push('湿球温度不应高于干球温度（当前湿球温度 ' + wb.toFixed(1) + '℃ > 干球温度 ' + temp.toFixed(1) +
                            '℃）');
                    }
                    if (dp > temp) {
                        errors.push('露点温度不应高于干球温度（当前露点温度 ' + dp.toFixed(1) + '℃ > 干球温度 ' + temp.toFixed(1) +
                            '℃）');
                    }
                    if (dp > wb) {
                        errors.push('露点温度不应高于湿球温度（当前露点温度 ' + dp.toFixed(1) + '℃ > 湿球温度 ' + wb.toFixed(1) +
                            '℃）');
                    }
                    if (dr < 0 || dr > 1) {
                        errors.push('直接辐射比例的取值范围在 0 和 1 之间');
                    }
                    if (angleDeg < 0 || angleDeg > 90) {
                        errors.push('太阳高度角的取值范围在 0 和 90 之间');
                    }

                    if (errors.length > 0) {
                        alert('气象数据不符合实际情况，无法进行气象分析：\n\n• ' + errors.join('\n• '));
                        return;
                    }

                    const angleRad = angleDeg * Math.PI / 180;

                    const e = 6.112 * Math.exp((17.67 * dp) / (dp + 243.5)) * (1.0007 + 0.00000346 * p);

                    const emissivity = 0.575 * Math.pow(e, 1 / 7);

                    const C = 0.315 * Math.pow((wind * 3600), 0.58) * 5.3865 * Math.pow(10, -8);

                    const part1 = dr * 2.268 * Math.pow(10, -8) * Math.cos(angleRad);
                    const part2 = 1.2 * 5.67 * Math.pow(10, -8) * (1 - dr);
                    const B = S * (part1 + part2) + emissivity * Math.pow(temp, 4);

                    const Tnwb = wb + 0.001651 * S - 0.09555 * wind + 0.13235 * (temp - wb) + 0.20249;

                    const Tg = (B + C * temp + 7680000) / (C + 256000);

                    const WBGT = 0.7 * Tnwb + 0.2 * Tg + 0.1 * temp;

                    let wbgtAdvice = '';
                    let wbgtColor = '#1a1a1a';

                    if (WBGT <= 10) {
                        wbgtAdvice = '低温天气，需注意防寒保暖，预防失温。';
                        wbgtColor = '#0a2463';
                    } else if (WBGT > 10 && WBGT <= 18) {
                        wbgtAdvice = '中性天气，注意补给节奏。';
                        wbgtColor = '#4a90d9';
                    } else if (WBGT > 18 && WBGT <= 23) {
                        wbgtAdvice = '中等热度，注意运动强度和补给节奏。';
                        wbgtColor = '#2e7d32';
                    } else if (WBGT > 23 && WBGT <= 28) {
                        wbgtAdvice = '高热度，注意补充水和电解质，小心中暑。';
                        wbgtColor = '#e65100';
                    } else if (WBGT > 28) {
                        wbgtAdvice = '极端高热，不宜进行高强度户外运动。';
                        wbgtColor = '#c62828';
                    }

                    let wbgtIcon;
                    if (WBGT <= 10) {
                        wbgtIcon = 'fa-temperature-empty';
                    } else if (WBGT <= 18) {
                        wbgtIcon = 'fa-temperature-quarter';
                    } else if (WBGT <= 23) {
                        wbgtIcon = 'fa-temperature-half';
                    } else if (WBGT <= 28) {
                        wbgtIcon = 'fa-temperature-three-quarters';
                    } else {
                        wbgtIcon = 'fa-temperature-full';
                    }

                    rows.push(
                        `<div class="weather-tip-row"><span class="weather-tip-icon" style="color:${wbgtColor}"><i class="fa-solid ${wbgtIcon}"></i></span><span class="weather-tip-text" style="font-weight:600; color:${wbgtColor};">WBGT ≈ ${WBGT.toFixed(1)}℃，${wbgtAdvice}</span></div>`
                        );
                }
            }

            const resultHtml = '<div class="weather-tips-container">' + rows.join('') + '</div>';
            document.getElementById('weatherResult').innerHTML = resultHtml;

            if (trackData) updateUI();
        }
        function getWeatherEquipmentModifier() {
            if (!weatherData) return { recommended: [], supplies: [] };
            const r = { recommended: [], supplies: [] };
            if (weatherData.temp >= 30) {
                r.supplies.push({ icon: 'fa-bottle-water', name: '电解质饮料', desc: '高温徒步补充水分和盐分，预防中暑' });
                r.recommended.push({ icon: 'fa-sun', name: '防暑装备', desc: '遮阳帽、防晒、降温用品' });
            }
            if (weatherData.temp <= 5 || (trackData && trackData.maxElevation > 2500 && weatherData.temp <= 10)) {
                r.recommended.push({ icon: 'fa-mitten', name: '保暖装备', desc: '抓绒/羽绒服及保温毯' });
            }
            if (weatherData.type.includes('雨')) {
                r.recommended.push({ icon: 'fa-cloud-rain', name: '雨具加强', desc: '雨衣、防水袋、备用袜' });
            }
            return r;
        }
        function generateEquipmentRecommendation(data, difficulty, risk) {
            const { totalDistance, totalAscent, maxElevation, uphillMaxGradient, downhillMaxGradient } = data;

            const essential = [
                { icon: 'fa-shoe-prints', name: '徒步鞋', desc: '防滑耐磨，建议中高帮' },
                { icon: 'fa-person-hiking', name: '登山背包', desc: `${totalDistance > 15 ? '30-40 L' : '20-30 L'}容量` },
                { icon: 'fa-mobile-screen', name: '手机+充电宝', desc: '保持通讯畅通' },
                { icon: 'fa-id-card', name: '身份证件', desc: '随身携带' },
                { icon: 'fa-kit-medical', name: '急救包', desc: '含创可贴、消毒液、止痛药' }
            ];

            const recommended = [];
            const weatherModifier = getWeatherEquipmentModifier();

            if (Math.abs(uphillMaxGradient) > 15 || Math.abs(downhillMaxGradient) > 15 || totalAscent > 500) {
                recommended.push({ icon: 'fa-person-hiking', name: '登山杖', desc: '减轻膝盖压力，建议双杖' });
            }

            recommended.push({ icon: 'fa-cloud-rain', name: '雨衣/雨披', desc: '防风防雨' });

            if (maxElevation > 1500) {
                recommended.push({ icon: 'fa-sun', name: '防晒用品', desc: 'SPF50+ 防晒霜、太阳镜、遮阳帽' });
            }

            if (maxElevation > 2000) {
                recommended.push({ icon: 'fa-mitten', name: '保暖衣物', desc: '抓绒衣/羽绒服，温度变化大' });
            }

            if (totalDistance > 15) {
                recommended.push({ icon: 'fa-lightbulb', name: '头灯', desc: '以防天黑前无法完成' });
            }

            if (Math.abs(uphillMaxGradient) > 30 || Math.abs(downhillMaxGradient) > 30) {
                recommended.push({ icon: 'fa-helmet-safety', name: '安全帽', desc: '陡坡防落石' });
            }

            recommended.push({ icon: 'fa-map', name: '地图+指南针', desc: '备用导航' });
            recommended.push({ icon: 'fa-bell', name: '哨子', desc: '紧急求救用' });

            const supplies = [];

            const time = estimateTime(data);
            const waterAmount = Math.ceil(time.totalHours * 0.5 + 1);
            supplies.push({ icon: 'fa-bottle-water', name: '饮用水', desc: `${waterAmount} L（建议 ${waterAmount + 1} L）` });

            const mealsNeeded = Math.ceil(time.totalHours / 4);
            supplies.push({ icon: 'fa-burger', name: '主食', desc: `${mealsNeeded} 餐，能量棒/面包/米饭` });

            const snacksAmount = Math.ceil(time.totalHours * 2);
            supplies.push({ icon: 'fa-cookie-bite', name: '能量零食', desc: `${snacksAmount} 份，巧克力/坚果/能量胶` });

            if (totalAscent > 800 || time.totalHours > 4) {
                supplies.push({ icon: 'fa-flask', name: '电解质', desc: '运动饮料/盐丸' });
            }

            if (difficulty.overall > 60) {
                supplies.push({ icon: 'fa-plus', name: '备用补给', desc: '额外 1 餐应急食物' });
            }

            return { essential, recommended, supplies };
        }
        function assessRisks(data) {
            const risks = [];
            if (weatherData) {
                if (weatherData.temp >= 30) risks.push({ level: 'high', icon: 'fa-temperature-full', title: '高温风险',
                    desc: '高温环境，注意中暑和脱水。' });
                if (weatherData.temp <= 0) risks.push({ level: 'high', icon: 'fa-snowflake', title: '低温风险',
                    desc: '低温环境，注意失温。' });
                if (weatherData.type.includes('中雨')) risks.push({ level: 'high', icon: 'fa-cloud-showers-heavy',
                    title: '降雨风险',
                    desc: '大雨天气，请取消户外徒步计划。' });
                if (weatherData.type.includes('阵雨') || weatherData.type.includes('小雨')) risks.push({ level: 'medium',
                    icon: 'fa-cloud-rain', title: '降雨风险',
                    desc: '雨天路滑，注意防滑和路线安全。' });
            }
            const { totalDistance, totalAscent, totalDescent, maxElevation, points, uphillMaxGradient,
                downhillMaxGradient } = data;

            if (maxElevation > 3000) {
                risks.push({ level: 'high', icon: 'fa-mountain', title: '高海拔风险',
                    desc: `最高点海拔 ${Math.round(maxElevation)} m，存在高原反应风险，建议提前适应海拔。` });
            } else if (maxElevation > 2000) {
                risks.push({ level: 'medium', icon: 'fa-mountain', title: '中高海拔',
                    desc: `最高点海拔 ${Math.round(maxElevation)} m，注意紫外线防护和温度变化。` });
            }

            if (uphillMaxGradient > 35) {
                risks.push({ level: 'high', icon: 'fa-arrow-trend-up', title: '极陡上坡',
                    desc: `最大上坡坡度达 ${uphillMaxGradient.toFixed(1)}%，攀爬困难，建议使用登山杖。` });
            } else if (uphillMaxGradient > 25) {
                risks.push({ level: 'medium', icon: 'fa-arrow-trend-up', title: '陡峭上坡',
                    desc: `最大上坡坡度 ${uphillMaxGradient.toFixed(1)}%，需要较好体能。` });
            }

            if (downhillMaxGradient < -35) {
                risks.push({ level: 'high', icon: 'fa-arrow-trend-down', title: '极陡下坡',
                    desc: `最大下坡坡度达 ${Math.abs(downhillMaxGradient).toFixed(1)}%，存在滑坠风险，注意安全。` });
            } else if (downhillMaxGradient < -25) {
                risks.push({ level: 'medium', icon: 'fa-arrow-trend-down', title: '陡峭下坡',
                    desc: `最大下坡坡度 ${Math.abs(downhillMaxGradient).toFixed(1)}%，下坡时注意保护膝盖。` });
            }

            if (totalDistance > 25) {
                risks.push({ level: 'high', icon: 'fa-route', title: '长距离',
                    desc: `总距离 ${totalDistance.toFixed(1)} km，需要良好体能储备，建议携带充足补给。` });
            } else if (totalDistance > 15) {
                risks.push({ level: 'medium', icon: 'fa-route', title: '中长距离',
                    desc: `总距离 ${totalDistance.toFixed(1)} km，建议提前规划补给点。` });
            }

            if (totalAscent > 1500) {
                risks.push({ level: 'high', icon: 'fa-mountain', title: '大爬升量',
                    desc: `累计爬升 ${Math.round(totalAscent)} m，对心肺功能要求较高。` });
            }

            if (totalDescent > 1200) {
                risks.push({ level: 'medium', icon: 'fa-arrow-trend-down', title: '大下降量',
                    desc: `累计下降 ${Math.round(totalDescent)} m，注意膝关节保护。` });
            }

            risks.sort((a, b) => {
                const order = { high: 0, medium: 1, low: 2 };
                return order[a.level] - order[b.level];
            });

            const highCount = risks.filter(r => r.level === 'high').length;
            const medCount = risks.filter(r => r.level === 'medium').length;

            let riskLevel, riskPercent;
            if (highCount >= 2) { riskLevel = '高风险';
                riskPercent = 98; } else if (highCount >= 1) { riskLevel = '中高风险';
                riskPercent = 78; } else if (medCount >= 2) { riskLevel = '中等风险';
                riskPercent = 58; } else if (medCount >= 1) { riskLevel = '低中风险';
                riskPercent = 39; } else { riskLevel = '低风险';
                riskPercent = 19; }

            return { risks, riskLevel, riskPercent };
        }
        function analyzeSegments(data, mode) {
            const points = data.points;
            const segments = [];

            if (mode === 'waypoint') {
                const wps = data.waypoints;
                const breakpoints = [0];

                wps.forEach(wp => breakpoints.push(wp.trackIdx));
                breakpoints.push(points.length - 1);

                const uniqueBreakpoints = [...new Set(breakpoints)].sort((a, b) => a - b);

                for (let i = 0; i < uniqueBreakpoints.length - 1; i++) {
                    const startIdx = uniqueBreakpoints[i];
                    const endIdx = uniqueBreakpoints[i + 1];

                    if (endIdx > startIdx) {
                        const seg = createSegment(points, startIdx, endIdx, 'auto');
                        if (i === 0) {
                            seg.name = '起点';
                            if (wps.length > 0) seg.endName = wps[0].name;
                        } else if (i === uniqueBreakpoints.length - 2) {
                            seg.name = wps[wps.length - 1].name;
                            seg.endName = '终点';
                        } else {
                            seg.name = wps[i - 1] ? wps[i - 1].name : `段${i}`;
                            seg.endName = wps[i] ? wps[i].name : `段${i+1}`;
                        }
                        segments.push(seg);
                    }
                }

            } else if (mode === 'auto') {
                let segStart = 0;
                let segType = points[1].smoothedGradient > 3 ? 'climb' : (points[1].smoothedGradient < -3 ? 'descent' :
                    'flat');

                for (let i = 2; i < points.length; i++) {
                    const newType = points[i].smoothedGradient > 3 ? 'climb' : (points[i].smoothedGradient < -3 ? 'descent' :
                        'flat');

                    if (newType !== segType) {
                        const segDist = points[i - 1].distance - points[segStart].distance;
                        if (segDist >= 0.2) {
                            segments.push(createSegment(points, segStart, i - 1, segType));
                        }
                        segStart = i - 1;
                        segType = newType;
                    }
                }

                const lastSegDist = points[points.length - 1].distance - points[segStart].distance;
                if (lastSegDist >= 0.2) {
                    segments.push(createSegment(points, segStart, points.length - 1, segType));
                }

            } else {
                // ── 距离分段（1km / 5km 等）：使用绝对目标边界 + 线性插值，消除累积舍入误差 ──
                const segSize = mode / 1000;
                const totalDist = points[points.length - 1].distance;
                // 整数分段数量（向下取整），使用 epsilon 处理浮点边界情况
                const numFullSegs = Math.floor(totalDist / segSize + 1e-10);

                let segStartIdx = 0;

                for (let seg = 0; seg < numFullSegs; seg++) {
                    const targetDist = (seg + 1) * segSize;

                    // 找到第一个距离 >= targetDist 的轨迹点
                    let i = segStartIdx + 1;
                    while (i < points.length && points[i].distance < targetDist) {
                        i++;
                    }
                    if (i >= points.length) break;

                    const prev = points[i - 1];
                    const curr = points[i];

                    // 如果当前点距离几乎恰好等于目标，则直接使用（避免不必要的插值）
                    if (Math.abs(curr.distance - targetDist) < 1e-12) {
                        segments.push(createSegment(points, segStartIdx, i, 'auto'));
                        segStartIdx = i;
                    } else {
                        // 线性插值创建精确边界虚拟点
                        const segLen = curr.distance - prev.distance;
                        if (segLen < 1e-12) {
                            // 退化情况：跳过
                            segStartIdx = i;
                            continue;
                        }
                        const t = (targetDist - prev.distance) / segLen;

                        const vpt = {
                            lat: prev.lat + (curr.lat - prev.lat) * t,
                            lon: prev.lon + (curr.lon - prev.lon) * t,
                            ele: prev.ele + (curr.ele - prev.ele) * t,
                            distance: targetDist,
                            horizontalDistance: prev.horizontalDistance + (curr.horizontalDistance - prev.horizontalDistance) * t,
                            gradient: curr.gradient,
                            smoothedGradient: curr.smoothedGradient
                        };

                        // 在 curr 之前插入虚拟点
                        points.splice(i, 0, vpt);

                        segments.push(createSegment(points, segStartIdx, i, 'auto'));
                        segStartIdx = i;
                    }
                }

                // 尾段：覆盖不足一个分段的剩余距离
                if (segStartIdx < points.length - 1) {
                    const remDist = points[points.length - 1].distance - points[segStartIdx].distance;
                    if (remDist > segSize * 0.005) {  // 大于分段尺寸的 0.5%（如 1km 分段则为 5m），忽略微小尾段
                        segments.push(createSegment(points, segStartIdx, points.length - 1, 'auto'));
                    }
                }
            }

            return segments;
        }
        function createSegment(points, startIdx, endIdx, type) {
            const startPt = points[startIdx];
            const endPt = points[endIdx];
            const distance = endPt.distance - startPt.distance;
            const horizontalDistance = (endPt.horizontalDistance || 0) - (startPt.horizontalDistance || 0);

            const mode = elevationMode || 'raw';
            const elevResult = ElevationCalculator.computeSegment(points, startIdx, endIdx, mode);
            const ascent = elevResult.ascent;
            const descent = elevResult.descent;

            let maxUphillGrad = 0;
            let maxDownhillGrad = 0;
            let uphillAscent = 0;
            let downhillDescent = 0;
            let uphillHorizontalDist = 0;
            let downhillHorizontalDist = 0;

            for (let i = startIdx + 1; i <= endIdx; i++) {
                const grad = points[i].smoothedGradient;
                const absGrad = Math.abs(grad);

                const segHorizontalDist = (points[i].horizontalDistance || 0) - (points[i - 1].horizontalDistance || 0);

                if (grad > 1) {
                    maxUphillGrad = Math.max(maxUphillGrad, grad);
                    uphillAscent += Math.max(0, points[i].ele - points[i - 1].ele);
                    uphillHorizontalDist += segHorizontalDist;
                } else if (grad < -1) {
                    maxDownhillGrad = Math.min(maxDownhillGrad, grad);
                    downhillDescent += Math.max(0, points[i - 1].ele - points[i].ele);
                    downhillHorizontalDist += segHorizontalDist;
                }
            }

            const uphillAvg = uphillHorizontalDist > 0 ? (uphillAscent / (uphillHorizontalDist * 1000)) * 100 : 0;
            const downhillAvg = downhillHorizontalDist > 0 ? (downhillDescent / (downhillHorizontalDist * 1000)) * 100 : 0;

            if (type === 'auto') {
                const totalChange = uphillAscent + downhillDescent;
                if (totalChange === 0) {
                    type = 'flat';
                } else {
                    const ascentRatio = uphillAscent / totalChange;
                    if (ascentRatio >= 0.6) {
                        type = 'climb';
                    } else if (ascentRatio <= 0.4) {
                        type = 'descent';
                    } else {
                        type = 'mixed';
                    }
                }
            }

            const baseTime = (distance / 5) * 60;
            const elevTime = ascent / 10;
            const steepAdjust = Math.max(maxUphillGrad, Math.abs(maxDownhillGrad)) > 15 ? (Math.max(maxUphillGrad, Math
                .abs(maxDownhillGrad)) - 15) * 0.5 : 0;
            const segTime = (baseTime + elevTime + steepAdjust) / 60;

            const segDiff = Math.min(100, (distance / 5) * 10 + (ascent / 300) * 20 + (Math.max(maxUphillGrad, Math.abs(
                maxDownhillGrad)) / 35) * 30);

            return {
                startIdx,
                endIdx,
                distance,
                ascent,
                descent,
                uphillAvg,
                downhillAvg,
                maxUphillGrad,
                maxDownhillGrad,
                type,
                time: segTime,
                difficulty: segDiff,
                startEle: startPt.ele,
                endEle: endPt.ele,
                startDist: startPt.distance,
                endDist: endPt.distance
            };
        }
        function calculateGradientDistribution(data) {
            const points = data.points;

            const upColors = UPHILL_GRADIENT_COLORS;
            const downColors = DOWNHILL_GRADIENT_COLORS;

            const uphill = [
                { name: '平缓 (≤5%)', color: upColors[0], distance: 0, level: 0, tip: '正常步行速度，保持均匀呼吸' },
                { name: '缓坡 (5-10%)', color: upColors[1], distance: 0, level: 1, tip: '适当放慢节奏，身体微前倾，小步幅前进' },
                { name: '中坡 (10-15%)', color: upColors[2], distance: 0, level: 2, tip: '使用登山杖辅助，缩短步幅，保持稳定呼吸频率' },
                { name: '陡坡 (15-25%)', color: upColors[3], distance: 0, level: 3, tip: 'Z字形攀爬减少坡度，频繁休息，补充水分和能量' },
                { name: '很陡 (25-35%)', color: upColors[4], distance: 0, level: 4, tip: '手脚并用攀爬，每步确认落脚点稳固，必要时使用绳索' },
                { name: '极陡 (>35%)', color: upColors[5], distance: 0, level: 5, tip: '极度危险，建议寻找替代路线，必须攀爬时需专业装备和保护' }
            ];

            const downhill = [
                { name: '平缓 (≤5%)', color: downColors[0], distance: 0, level: 0, tip: '正常步行，注意路面湿滑' },
                { name: '缓坡 (5-10%)', color: downColors[1], distance: 0, level: 1, tip: '膝盖微屈缓冲，脚跟先着地，控制速度' },
                { name: '中坡 (10-15%)', color: downColors[2], distance: 0, level: 2, tip: '使用登山杖减轻膝盖压力，侧身下坡减少关节冲击' },
                { name: '陡坡 (15-25%)', color: downColors[3], distance: 0, level: 3, tip: '面向或侧向坡面，一步一步确认落脚，避免跳跃式下坡' },
                { name: '很陡 (25-35%)', color: downColors[4], distance: 0, level: 4, tip: '面向坡面攀扶下降，使用绳索或寻找抓手点，保持重心低' },
                { name: '极陡 (>35%)', color: downColors[5], distance: 0, level: 5, tip: '极度危险，滑坠风险极高，必须使用绳索下降技术' }
            ];

            for (let i = 1; i < points.length; i++) {
                const segDist = points[i].distance - points[i - 1].distance;
                const grad = points[i].smoothedGradient;
                const level = getGradientLevel(grad);

                if (grad > 0) {
                    uphill[level].distance += segDist;
                } else {
                    downhill[level].distance += segDist;
                }
            }

            const total = data.totalDistance;
            uphill.forEach(l => l.percentage = (l.distance / total) * 100);
            downhill.forEach(l => l.percentage = (l.distance / total) * 100);

            return { uphill, downhill };
        }
