/* TrailScope module: chart.js — generated by JS modularization build. */
function drawChart(options = {}) {
    if (!trackData) return;

    const canvas = chartCanvas;
    const ctx = chartCtx;
    if (!trackData.hasValidElevation) {
        if (canvas) {
            if (ctx) {
                ctx.save();
                ctx.setTransform(1, 0, 0, 1, 0, 0);
                ctx.clearRect(0, 0, canvas.width, canvas.height);
                ctx.restore();
            }
            clearChartHoverOverlay(canvas);
            canvas._scale = null;
        }
        return;
    }

    const providedSegments = options && Array.isArray(options.segments) ? options.segments : null;
    const dpr = window.devicePixelRatio || 1;
    const rect = canvas.getBoundingClientRect();

    const pixelWidth = Math.max(1, Math.round(rect.width * dpr));
    const pixelHeight = Math.max(1, Math.round(rect.height * dpr));
    if (canvas.width !== pixelWidth || canvas.height !== pixelHeight || canvas._dpr !== dpr) {
        canvas.width = pixelWidth;
        canvas.height = pixelHeight;
        canvas._dpr = dpr;
    }
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    const W = rect.width;
    const H = rect.height;
    if (W < 1 || H < 1) {
        // 布局过渡瞬间画布尺寸可能为 0：跳过本次绘制，避免画出横线并保留旧画面
        return;
    }
    let padding = { top: 30, right: 50, bottom: 45, left: 60 };
    if (IS_MOBILE) {
        padding.left = 60;
        padding.right = 30;
    }
    const chartW = W - padding.left - padding.right;
    let chartH = H - padding.top - padding.bottom;
    if (chartH < 1) {
        // 画布过矮（如手机横屏全屏）：压缩上下内边距，保证绘图区高度为正，
        // 否则 y 轴映射反转（图表上下颠倒）且触摸判定区间失效（滑动无响应）
        padding.top = Math.max(4, Math.floor(H * 0.12));
        padding.bottom = Math.max(4, Math.floor(H * 0.12));
        chartH = H - padding.top - padding.bottom;
    }

    ctx.clearRect(0, 0, W, H);

    const points = trackData.points;
    const maxDist = trackData.totalDistance;
    const minEle = trackData.minElevation;
    const maxEle = trackData.maxElevation;
    const eleRange = Math.max(50, maxEle - minEle);
    const elePadding = eleRange * 0.1;

    const visibleRange = maxDist / zoomLevel;
    const centerDist = maxDist * zoomCenter;
    let viewStart = Math.max(0, centerDist - visibleRange / 2);
    let viewEnd = Math.min(maxDist, viewStart + visibleRange);
    if (viewEnd - viewStart < visibleRange) {
        viewStart = Math.max(0, viewEnd - visibleRange);
    }

    const xScale = (d) => padding.left + ((d - viewStart) / (viewEnd - viewStart)) * chartW;
    const yScale = (e) => padding.top + chartH - ((e - minEle + elePadding) / (eleRange + 2 * elePadding)) * chartH;

    // Grid lines
    ctx.strokeStyle = chartTheme.grid;
    ctx.lineWidth = 1;
    ctx.font = '11px Inter, sans-serif';
    ctx.fillStyle = chartTheme.axisMuted;

    const ySteps = 5;
    for (let i = 0; i <= ySteps; i++) {
        const y = padding.top + (chartH / ySteps) * i;
        const elev = maxEle + elePadding - ((eleRange + 2 * elePadding) / ySteps) * i;

        ctx.beginPath();
        ctx.moveTo(padding.left, y);
        ctx.lineTo(W - padding.right, y);
        ctx.stroke();

        ctx.textAlign = 'right';
        ctx.fillText(Math.round(elev) + ' m', padding.left - 8, y + 4);
    }

    let xSteps = Math.min(10, Math.ceil(viewEnd - viewStart));
    if (IS_MOBILE) xSteps = 4;

    for (let i = 0; i <= xSteps; i++) {
        const dist = viewStart + ((viewEnd - viewStart) / xSteps) * i;
        const x = xScale(dist);

        ctx.beginPath();
        ctx.moveTo(x, padding.top);
        ctx.lineTo(x, padding.top + chartH);
        ctx.stroke();

        ctx.textAlign = 'center';
        ctx.fillText(dist.toFixed(1) + ' km', x, H - padding.bottom + 18);
    }

    // Highlight active segment
    if (activeSegmentIdx >= 0) {
        const segments = providedSegments || analyzeSegments(trackData, segmentMode);
        if (activeSegmentIdx < segments.length) {
            const seg = segments[activeSegmentIdx];
            if (seg && seg.startIdx !== undefined && seg.endIdx !== undefined &&
                seg.startIdx >= 0 && seg.endIdx >= 0 &&
                seg.startIdx < points.length && seg.endIdx < points.length) {
                const segStartX = xScale(points[seg.startIdx].distance);
                const segEndX = xScale(points[seg.endIdx].distance);

                const clipStartX = Math.max(segStartX, padding.left);
                const clipEndX = Math.min(segEndX, W - padding.right);

                if (clipEndX > clipStartX) {
                    ctx.save();
                    ctx.beginPath();
                    ctx.rect(padding.left, padding.top, chartW, chartH);
                    ctx.clip();

                    ctx.fillStyle = 'rgba(212, 160, 23, 0.15)';
                    ctx.fillRect(clipStartX, padding.top, clipEndX - clipStartX, chartH);

                    ctx.strokeStyle = 'rgba(212, 160, 23, 0.5)';
                    ctx.lineWidth = 1;
                    ctx.setLineDash([4, 4]);
                    ctx.beginPath();
                    ctx.moveTo(segStartX, padding.top);
                    ctx.lineTo(segStartX, padding.top + chartH);
                    ctx.moveTo(segEndX, padding.top);
                    ctx.lineTo(segEndX, padding.top + chartH);
                    ctx.stroke();
                    ctx.setLineDash([]);

                    ctx.restore();
                }
            }
        }
    }

    // Profile line
    ctx.save();
    ctx.beginPath();
    ctx.rect(padding.left, padding.top, chartW, chartH);
    ctx.clip();

    const firstVisibleIdx = findFirstPointAtOrAfterDistance(points, viewStart);
    const lastVisibleIdx = findLastPointAtOrBeforeDistance(points, viewEnd);
    const startIdx = Math.max(0, firstVisibleIdx - 1);
    const endIdx = Math.min(points.length - 1, lastVisibleIdx + 1);
    const displayIndices = getChartDisplayPointIndices(points, startIdx, endIdx, chartW);
    const renderIndices = displayIndices || Array.from({ length: endIdx - startIdx + 1 }, (_, index) => startIdx + index);
    const fillPaths = new Map();
    const strokePaths = new Map();
    const baseline = padding.top + chartH;

    for (let i = 1; i < renderIndices.length; i++) {
        const previousIdx = renderIndices[i - 1];
        const currentIdx = renderIndices[i];
        const previousPoint = points[previousIdx];
        const currentPoint = points[currentIdx];
        const value = colorMode === 'elevation'
            ? currentPoint.ele
            : (currentPoint.smoothedGradient + previousPoint.smoothedGradient) / 2;
        const renderColor = getChartRenderColor(colorMode, value, minEle, maxEle);
        let fillPath = fillPaths.get(renderColor.key);
        let strokePath = strokePaths.get(renderColor.key);
        if (!fillPath) {
            fillPath = { color: renderColor.rgba, path: new Path2D() };
            strokePath = { color: renderColor.color, path: new Path2D() };
            fillPaths.set(renderColor.key, fillPath);
            strokePaths.set(renderColor.key, strokePath);
        }

        const previousX = xScale(previousPoint.distance);
        const previousY = yScale(previousPoint.ele);
        const currentX = xScale(currentPoint.distance);
        const currentY = yScale(currentPoint.ele);
        fillPath.path.moveTo(previousX, previousY);
        fillPath.path.lineTo(currentX, currentY);
        fillPath.path.lineTo(currentX, baseline);
        fillPath.path.lineTo(previousX, baseline);
        fillPath.path.closePath();
        strokePath.path.moveTo(previousX, previousY);
        strokePath.path.lineTo(currentX, currentY);
    }

    fillPaths.forEach(({ color, path }) => {
        ctx.fillStyle = color;
        ctx.fill(path);
    });
    ctx.lineWidth = 2.5;
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    strokePaths.forEach(({ color, path }) => {
        ctx.strokeStyle = color;
        ctx.stroke(path);
    });

    ctx.restore();

    if (showAnnotations) {
        drawAnnotations(ctx, points, xScale, yScale, padding, chartW, chartH, viewStart, viewEnd);
    }

    drawStartEndMarkers(ctx, points, xScale, yScale, viewStart, viewEnd);

    // ★★★ 航路点绘制：根据三状态决定 ★★★
    if (waypointDisplayMode !== 'hide-all') {
        const showNames = (waypointDisplayMode === 'show-names');
        drawWaypoints(ctx, trackData.waypoints, xScale, yScale, viewStart, viewEnd, showNames);
    }

    ctx.fillStyle = chartTheme.axis;
    ctx.font = '600 12px Inter, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('距离', W / 2, H - 8);

    ctx.save();
    ctx.translate(15, H / 2);
    ctx.rotate(-Math.PI / 2);
    ctx.fillText('海拔', 0, 0);
    ctx.restore();

    canvas._scale = { xScale, yScale, padding, chartW, chartH, W, H, viewStart, viewEnd };
    canvas._themeVersion = chartThemeVersion;
    ensureChartHoverOverlay(canvas);
    refreshChartHoverOverlay();
}
function drawStartEndMarkers(ctx, points, xScale, yScale, viewStart, viewEnd) {
    if (points[0].distance >= viewStart && points[0].distance <= viewEnd) {
        const x = xScale(points[0].distance);
        const y = yScale(points[0].ele);

        ctx.fillStyle = '#5c7a52';
        ctx.beginPath();
        ctx.arc(x, y, 7, 0, Math.PI * 2);
        ctx.fill();

        ctx.fillStyle = '#fff';
        ctx.beginPath();
        ctx.arc(x, y, 3.5, 0, Math.PI * 2);
        ctx.fill();

        ctx.font = '600 10px Inter, sans-serif';
        ctx.textAlign = 'center';
        const labelText = '起点';
        const textWidth = ctx.measureText(labelText).width;

        ctx.fillStyle = '#5c7a52';
        ctx.beginPath();
        ctx.roundRect(x - textWidth / 2 - 6, y - 28, textWidth + 12, 16, 8);
        ctx.fill();

        ctx.fillStyle = '#fff';
        ctx.fillText(labelText, x, y - 16);
    }

    const lastPt = points[points.length - 1];
    if (lastPt.distance >= viewStart && lastPt.distance <= viewEnd) {
        const x = xScale(lastPt.distance);
        const y = yScale(lastPt.ele);

        ctx.fillStyle = '#c54b3c';
        ctx.beginPath();
        ctx.arc(x, y, 7, 0, Math.PI * 2);
        ctx.fill();

        ctx.fillStyle = '#fff';
        ctx.beginPath();
        ctx.arc(x, y, 3.5, 0, Math.PI * 2);
        ctx.fill();

        ctx.font = '600 10px Inter, sans-serif';
        ctx.textAlign = 'center';
        const labelText = '终点';
        const textWidth = ctx.measureText(labelText).width;

        ctx.fillStyle = '#c54b3c';
        ctx.beginPath();
        ctx.roundRect(x - textWidth / 2 - 6, y - 28, textWidth + 12, 16, 8);
        ctx.fill();

        ctx.fillStyle = '#fff';
        ctx.fillText(labelText, x, y - 16);
    }
}
function drawWaypoints(ctx, waypoints, xScale, yScale, viewStart, viewEnd, showNames) {
    waypoints.forEach((wp) => {
        if (wp.distance < viewStart || wp.distance > viewEnd) return;

        const x = xScale(wp.distance);
        const y = yScale(wp.elevation);

        // 总是绘制标记
        ctx.fillStyle = '#8b7355';
        ctx.strokeStyle = '#fff';
        ctx.lineWidth = 2;

        ctx.beginPath();
        ctx.moveTo(x, y - 6);
        ctx.lineTo(x + 6, y);
        ctx.lineTo(x, y + 6);
        ctx.lineTo(x - 6, y);
        ctx.closePath();
        ctx.fill();
        ctx.stroke();

        if (showNames) {
            const shortName = wp.name.length > 8 ? wp.name.substring(0, 7) + '…' : wp.name;
            ctx.font = '500 10px Inter, sans-serif';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'alphabetic';
            const textWidth = ctx.measureText(shortName).width;

            ctx.fillStyle = 'rgba(139, 115, 85, 0.9)';
            ctx.beginPath();
            ctx.roundRect(x - textWidth / 2 - 5, y + 12, textWidth + 10, 14, 7);
            ctx.fill();

            ctx.fillStyle = '#fff';
            ctx.fillText(shortName, x, y + 22);
        }
    });
}
function drawAnnotations(ctx, points, xScale, yScale, padding, chartW, chartH, viewStart, viewEnd) {
    const annotationModel = getChartAnnotationModel(points);
    const topSegments = annotationModel.topSegments;

    topSegments.forEach((seg) => {
        const startPt = points[seg.start];
        const endPt = points[seg.end];
        const midIdx = Math.floor((seg.start + seg.end) / 2);
        const midPt = points[midIdx];

        if (midPt.distance < viewStart || midPt.distance > viewEnd) return;

        const x = xScale(midPt.distance);
        const y = yScale(midPt.ele);

        const isClimb = seg.type === 'climb';
        const color = isClimb ? '#c54b3c' : '#3a6b8a';
        const label = isClimb ? '↑' : '↓';
        const value = isClimb ? seg.ascent : seg.descent;

        ctx.fillStyle = color;
        ctx.beginPath();
        ctx.arc(x, y, 5, 0, Math.PI * 2);
        ctx.fill();

        ctx.fillStyle = '#fff';
        ctx.beginPath();
        ctx.arc(x, y, 2.5, 0, Math.PI * 2);
        ctx.fill();

        const labelY = isClimb ? y - 18 : y + 22;
        const labelText = `${label}${Math.round(value)} m`;

        ctx.font = '600 10px Inter, sans-serif';
        ctx.textAlign = 'center';

        const textWidth = ctx.measureText(labelText).width;
        ctx.fillStyle = 'rgba(26, 46, 31, 0.9)';
        ctx.beginPath();
        ctx.roundRect(x - textWidth / 2 - 6, labelY - 8, textWidth + 12, 16, 8);
        ctx.fill();

        ctx.fillStyle = '#f5f1e8';
        ctx.fillText(labelText, x, labelY + 4);

        ctx.strokeStyle = chartTheme.annotationLine;
        ctx.lineWidth = 1;
        ctx.setLineDash([2, 2]);
        ctx.beginPath();
        ctx.moveTo(x, y);
        ctx.lineTo(x, labelY + (isClimb ? 4 : -4));
        ctx.stroke();
        ctx.setLineDash([]);
    });

    const maxIdx = annotationModel.maxIdx;
    const minIdx = annotationModel.minIdx;

    [
        { idx: maxIdx, label: '最高点', color: '#d4a017', offset: -25 },
        { idx: minIdx, label: '最低点', color: '#3a6b8a', offset: 25 }
    ].forEach(({ idx, label, color, offset }) => {
        if (points[idx].distance < viewStart || points[idx].distance > viewEnd) return;

        const x = xScale(points[idx].distance);
        const y = yScale(points[idx].ele);

        ctx.fillStyle = color;
        ctx.beginPath();
        if (offset < 0) {
            ctx.moveTo(x, y - 4);
            ctx.lineTo(x - 5, y - 12);
            ctx.lineTo(x + 5, y - 12);
        } else {
            ctx.moveTo(x, y + 4);
            ctx.lineTo(x - 5, y + 12);
            ctx.lineTo(x + 5, y + 12);
        }
        ctx.closePath();
        ctx.fill();

        ctx.font = '600 10px Inter, sans-serif';
        ctx.textAlign = 'center';
        const labelText = `${label} ${Math.round(points[idx].ele)} m`;
        const textWidth = ctx.measureText(labelText).width;

        ctx.fillStyle = color;
        ctx.beginPath();
        ctx.roundRect(x - textWidth / 2 - 6, y + offset - 8, textWidth + 12, 16, 8);
        ctx.fill();

        ctx.fillStyle = '#fff';
        ctx.fillText(labelText, x, y + offset + 4);
    });
}


