/* TrailScope module: gpx.js — generated by JS modularization build. */
const GPX_MAX_TRACK_POINTS = 200000;
const GPX_MAX_WAYPOINTS = 20000;

function parseGPXPoint(element) {
    const lat = parseFloat(element.getAttribute('lat'));
    const lon = parseFloat(element.getAttribute('lon'));
    if (!Number.isFinite(lat) || !Number.isFinite(lon)) return null;

    let ele = null;
    for (let child = element.firstElementChild; child; child = child.nextElementSibling) {
        if (child.localName === 'ele') {
            const value = parseFloat(child.textContent);
            ele = Number.isFinite(value) ? value : null;
        }
    }

    return { lat, lon, ele, distance: 0, horizontalDistance: 0, gradient: 0, smoothedGradient: 0 };
}

function parseGPX(gpxText) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(gpxText, 'text/xml');
    if (doc.querySelector('parsererror')) throw new Error('GPX XML 无效');

    const points = [];
    let isRtept = false;

    let pointElements = doc.querySelectorAll('trkpt');
    if (pointElements.length === 0) {
        pointElements = doc.querySelectorAll('rtept');
        isRtept = pointElements.length > 0;
    }
    if (pointElements.length > GPX_MAX_TRACK_POINTS) throw new Error('GPX 轨迹点数量过多');
    for (let i = 0; i < pointElements.length; i++) {
        const point = parseGPXPoint(pointElements[i]);
        if (point) points.push(point);
    }

    const waypointElements = doc.querySelectorAll('wpt');
    if (waypointElements.length > GPX_MAX_WAYPOINTS) throw new Error('GPX 航路点数量过多');
    const waypoints = [];
    for (let i = 0; i < waypointElements.length; i++) {
        const wpt = waypointElements[i];
        const lat = parseFloat(wpt.getAttribute('lat'));
        const lon = parseFloat(wpt.getAttribute('lon'));
        if (!Number.isFinite(lat) || !Number.isFinite(lon)) continue;

        let name = '未命名航路点';
        let ele = null;
        let desc = '';
        for (let child = wpt.firstElementChild; child; child = child.nextElementSibling) {
            if (child.localName === 'name') name = child.textContent;
            else if (child.localName === 'ele') {
                const value = parseFloat(child.textContent);
                ele = Number.isFinite(value) ? value : null;
            } else if (child.localName === 'desc') desc = child.textContent;
        }
        waypoints.push({ lat, lon, name, ele, desc });
    }

    return { points, waypoints, isRtept };
}

const KML_MAX_TRACK_POINTS = 200000;
const KML_MAX_WAYPOINTS = 20000;

function kmlElementsByName(root, name) {
    return Array.from(root.getElementsByTagName('*')).filter(element => element.localName === name);
}

function kmlFirstElement(root, name) {
    return kmlElementsByName(root, name)[0] || null;
}

function kmlElementText(root, name) {
    const element = kmlFirstElement(root, name);
    return element ? element.textContent.trim() : '';
}

function kmlDescriptionText(value) {
    return value
        .replace(/<br\s*\/?>(?=\S)/gi, ' ')
        .replace(/<\/p\s*>/gi, ' ')
        .replace(/<script[\s\S]*?<\/script>/gi, ' ')
        .replace(/<style[\s\S]*?<\/style>/gi, ' ')
        .replace(/<[^>]*>/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

function kmlCoordinateTuple(text) {
    const values = text.trim().split(/[\,\s]+/);
    const lon = parseFloat(values[0]);
    const lat = parseFloat(values[1]);
    const ele = values.length > 2 && values[2].trim() !== '' ? parseFloat(values[2]) : null;
    if (!Number.isFinite(lat) || !Number.isFinite(lon)) return null;
    return { lat, lon, ele: Number.isFinite(ele) ? ele : null };
}

function kmlCoordinatesElement(root) {
    return kmlFirstElement(root, 'coordinates');
}

function kmlTrackPointsFromTrack(track) {
    const coords = kmlElementsByName(track, 'coord');
    return coords.map(coordElement => {
        const tuple = kmlCoordinateTuple(coordElement.textContent);
        return tuple;
    }).filter(Boolean);
}

function kmlLineStringPoints(lineString) {
    const coordinatesElement = kmlCoordinatesElement(lineString);
    if (!coordinatesElement) return [];
    return coordinatesElement.textContent.trim().split(/\s+/).map(kmlCoordinateTuple).filter(Boolean);
}

function parseKML(kmlText) {
    if (typeof kmlText !== 'string' || kmlText.length > 32 * 1024 * 1024) {
        throw new Error('KML file is too large');
    }

    const parser = new DOMParser();
    const doc = parser.parseFromString(kmlText, 'text/xml');
    if (kmlElementsByName(doc, 'parsererror').length > 0 || !doc.documentElement) {
        throw new Error('Invalid KML XML');
    }

    const points = [];
    const tracks = kmlElementsByName(doc, 'Track');
    if (tracks.length > 0) {
        tracks.forEach(track => {
            points.push(...kmlTrackPointsFromTrack(track));
        });
    } else {
        kmlElementsByName(doc, 'LineString').forEach(lineString => {
            points.push(...kmlLineStringPoints(lineString));
        });
    }
    if (points.length > KML_MAX_TRACK_POINTS) throw new Error('KML contains too many track points');

    const waypoints = [];
    kmlElementsByName(doc, 'Placemark').forEach(placemark => {
        const point = kmlFirstElement(placemark, 'Point');
        if (!point) return;
        const coordinatesElement = kmlCoordinatesElement(point);
        const tuple = coordinatesElement ? kmlCoordinateTuple(coordinatesElement.textContent.trim().split(/\s+/)[0]) : null;
        if (!tuple) return;

        const desc = kmlElementText(placemark, 'description');
        const nameText = kmlElementText(placemark, 'name');
        const name = nameText || kmlDescriptionText(desc) || '未命名航路点';
        waypoints.push({ ...tuple, name, desc });
    });
    if (waypoints.length > KML_MAX_WAYPOINTS) throw new Error('KML contains too many waypoints');

    return { points, waypoints, isRtept: false };
}

function processTrack(points, waypoints) {
    if (points.length < 2) return null;

    let hasElevation = points.some(p => p.ele !== null);
    if (!hasElevation) {
        points.forEach((p, i) => {
            p.ele = 800 + Math.sin(i * 0.05) * 200 + Math.sin(i * 0.15) * 100 + Math.random() * 20;
        });
    } else {
        for (let i = 0; i < points.length;) {
            if (points[i].ele !== null) {
                i++;
                continue;
            }

            const runStart = i;
            while (i < points.length && points[i].ele === null) i++;
            const nextEle = i < points.length ? points[i].ele : null;
            let prevEle = runStart > 0 ? points[runStart - 1].ele : null;
            for (let j = runStart; j < i; j++) {
                if (prevEle !== null && nextEle !== null) {
                    points[j].ele = (prevEle + nextEle) / 2;
                } else if (prevEle !== null) {
                    points[j].ele = prevEle;
                } else if (nextEle !== null) {
                    points[j].ele = nextEle;
                }
                prevEle = points[j].ele;
            }
        }
    }

    let totalDistance = 0;
    let totalHorizontalDistance = 0;
    let maxElevation = -Infinity;
    let minElevation = Infinity;

    let uphillDistance = 0;
    let downhillDistance = 0;
    let flatDistance = 0;
    let uphillMaxGradient = 0;
    let downhillMaxGradient = 0;
    let uphillAvgGradient = 0;
    let downhillAvgGradient = 0;
    let uphillGradientSum = 0;
    let downhillGradientSum = 0;
    let uphillCount = 0;
    let downhillCount = 0;

    points[0].distance = 0;
    points[0].horizontalDistance = 0;
    points[0].gradient = 0;

    for (let i = 1; i < points.length; i++) {
        const horizontalDist = haversine(points[i - 1].lat, points[i - 1].lon, points[i].lat, points[i].lon);
        const elevDiff = points[i].ele - points[i - 1].ele;

        const horizontalMeters = horizontalDist * 1000;
        const dist3D = Math.sqrt(horizontalMeters * horizontalMeters + elevDiff * elevDiff) / 1000;

        totalDistance += dist3D;
        totalHorizontalDistance += horizontalDist;
        points[i].distance = totalDistance;
        points[i].horizontalDistance = totalHorizontalDistance;

        if (points[i].ele > maxElevation) maxElevation = points[i].ele;
        if (points[i].ele < minElevation) minElevation = points[i].ele;

        const gradient = horizontalDist > 0 ? (elevDiff / (horizontalDist * 1000)) * 100 : 0;
        points[i].gradient = gradient;

        if (gradient > 1) {
            uphillDistance += dist3D;
            uphillGradientSum += gradient;
            uphillCount++;
        } else if (gradient < -1) {
            downhillDistance += dist3D;
            downhillGradientSum += gradient;
            downhillCount++;
        } else {
            flatDistance += dist3D;
        }
    }

    uphillAvgGradient = uphillCount > 0 ? uphillGradientSum / uphillCount : 0;
    downhillAvgGradient = downhillCount > 0 ? downhillGradientSum / downhillCount : 0;

    const windowSize = Math.min(5, Math.floor(points.length / 10));
    if (windowSize > 1) {
        for (let i = 0; i < points.length; i++) {
            let sum = 0,
                count = 0;
            for (let j = Math.max(0, i - windowSize); j <= Math.min(points.length - 1, i + windowSize); j++) {
                sum += points[j].gradient;
                count++;
            }
            points[i].smoothedGradient = sum / count;
        }
    } else {
        points.forEach(p => p.smoothedGradient = p.gradient);
    }

    uphillMaxGradient = 0;
    downhillMaxGradient = 0;

    for (let i = 1; i < points.length; i++) {
        if (points[i].smoothedGradient > 0) {
            uphillMaxGradient = Math.max(uphillMaxGradient, points[i].smoothedGradient);
        } else if (points[i].smoothedGradient < 0) {
            downhillMaxGradient = Math.min(downhillMaxGradient, points[i].smoothedGradient);
        }
    }

    const mode = elevationMode || 'raw';
    const totalElev = ElevationCalculator.computeTotal(points, mode);

    const avgGradient = totalHorizontalDistance > 0 ? (totalElev.ascent / (totalHorizontalDistance * 1000)) * 100 : 0;

    const matchedWaypoints = waypoints.map(wp => {
        const nearestIdx = findNearestPointIndex(points, wp.lat, wp.lon);
        return {
            ...wp,
            trackIdx: nearestIdx,
            distance: points[nearestIdx].distance,
            elevation: wp.ele || points[nearestIdx].ele
        };
    });

    matchedWaypoints.sort((a, b) => a.distance - b.distance);

    const maxZoom = Math.max(1, totalDistance / 1);

    return {
        points,
        waypoints: matchedWaypoints,
        totalDistance,
        totalHorizontalDistance,
        totalAscent: totalElev.ascent,
        totalDescent: totalElev.descent,
        maxElevation,
        minElevation,
        elevationRange: maxElevation - minElevation,
        uphillDistance,
        downhillDistance,
        flatDistance,
        uphillMaxGradient,
        downhillMaxGradient,
        uphillAvgGradient,
        downhillAvgGradient,
        avgGradient,
        maxZoomLevel: maxZoom
    };
}
function getGradientLabel(gradient) {
    const absGrad = Math.abs(gradient);
    if (absGrad <= 5) return '平缓';
    if (absGrad <= 10) return '缓坡';
    if (absGrad <= 15) return '中坡';
    if (absGrad <= 25) return '陡坡';
    if (absGrad <= 35) return '很陡';
    return '极陡';
}


