/* TrailScope module: init.js — generated by JS modularization build. */
document.addEventListener('DOMContentLoaded', () => {
    chartCanvas = document.getElementById('elevationChart');
    chartCtx = chartCanvas.getContext('2d');

    if (IS_MOBILE) {
        const chartWrapper = document.getElementById('chartWrapper');
        if (chartWrapper) {
            chartWrapper.classList.add('mobile-hide-zoom');
        }
        document.getElementById('zoomInfo').classList.add('hidden');
        const infoDiv = document.querySelector('.text-xs.text-trail-mid\\/50.ml-auto');
        if (infoDiv) {
            infoDiv.innerHTML = '<i class="fa-solid fa-circle-info"></i> 双指缩放 · 手指滑动查看详情 · 点击外部取消标记';
        }
    }

    setElevationMode('raw');

    document.getElementById('fileInput').addEventListener('change', (e) => {
        handleFile(e.target.files[0]);
    });

    const uploadZone = document.getElementById('uploadZone');

    uploadZone.addEventListener('dragover', (e) => {
        e.preventDefault();
        uploadZone.classList.add('dragover');
    });

    uploadZone.addEventListener('dragleave', () => {
        uploadZone.classList.remove('dragover');
    });

    uploadZone.addEventListener('drop', (e) => {
        e.preventDefault();
        uploadZone.classList.remove('dragover');
        handleFile(e.dataTransfer.files[0]);
    });

    setupChartInteraction();

    let resizeTimer;
    window.addEventListener('resize', () => {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(() => {
            if (trackData && !document.getElementById('fullscreenProfile')) {
                drawChart();
                if (leafletMap) leafletMap.invalidateSize();
            }
        }, 200);
    });

    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            const href = this.getAttribute('href');

            if (href === '#upload') {
                e.preventDefault();
                const target = document.querySelector(href);
                if (target) {
                    const nav = document.querySelector('nav');
                    const navHeight = nav ? nav.offsetHeight : 0;
                    const targetPosition = target.getBoundingClientRect().top + window.pageYOffset -
                        navHeight - 10;
                    window.scrollTo({
                        top: targetPosition,
                        behavior: 'smooth'
                    });
                }
                return;
            }

            if (!trackData) {
                e.preventDefault();
                return;
            }

            e.preventDefault();
            const target = document.querySelector(href);
            if (target) {
                const nav = document.querySelector('nav');
                const navHeight = nav ? nav.offsetHeight : 0;
                const targetPosition = target.getBoundingClientRect().top + window.pageYOffset - navHeight -
                    10;
                window.scrollTo({
                    top: targetPosition,
                    behavior: 'smooth'
                });
            }
        });
    });

    // 初始化航路点按钮
    updateWaypointButton();

    // 联动按钮状态
    const initLinkageBtn = document.getElementById('mapLinkageBtn');
    if (initLinkageBtn) {
        if (mapLinkageEnabled) {
            initLinkageBtn.classList.add('active-linkage');
            initLinkageBtn.title = '禁用地图联动';
        } else {
            initLinkageBtn.classList.remove('active-linkage');
            initLinkageBtn.title = '启用地图联动';
        }
    }
});
console.log('设备类型:', DEVICE_TYPE, IS_MOBILE ? '手机端' : '电脑端');
console.log('爬升/下降模式:', elevationMode);
console.log('地图联动状态:', mapLinkageEnabled ? '启用' : '禁用');
console.log('航路点显示模式:', waypointDisplayMode);


