/* TrailScope module: interaction.js — generated by JS modularization build. */
function setupChartInteraction() {
    const canvas = chartCanvas;
    const tooltip = canvas._tooltip || document.getElementById('chartTooltip');

    // 鼠标事件
    canvas.addEventListener('mousemove', function(e) {
        if (IS_MOBILE) return;
        if (!trackData || !canvas._scale) return;

        const rect = canvas.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;

        const { xScale, yScale, padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

        if (isDragging) {
            const dx = x - dragStartX;
            const visibleRange = dragStartViewEnd - dragStartViewStart;
            const distShift = -(dx / chartW) * visibleRange;

            let newViewStart = dragStartViewStart + distShift;
            let newViewEnd = dragStartViewEnd + distShift;

            if (newViewStart < 0) {
                newViewStart = 0;
                newViewEnd = visibleRange;
            }
            if (newViewEnd > trackData.totalDistance) {
                newViewEnd = trackData.totalDistance;
                newViewStart = trackData.totalDistance - visibleRange;
            }

            zoomCenter = (newViewStart + newViewEnd) / 2 / trackData.totalDistance;
            drawChart();
            return;
        }

        if (x < padding.left || x > W - padding.right || y < padding.top || y > padding.top + chartH) {
            tooltip.classList.remove('visible');
            hoveredPointIdx = -1;
            updateMapCurrentPoint(-1);
            drawChart();
            return;
        }

        const points = trackData.points;
        const distRatio = (x - padding.left) / chartW;
        const targetDist = viewStart + distRatio * (viewEnd - viewStart);

        let nearestIdx = 0;
        let minDiff = Infinity;
        for (let i = 0; i < points.length; i++) {
            const diff = Math.abs(points[i].distance - targetDist);
            if (diff < minDiff) {
                minDiff = diff;
                nearestIdx = i;
            }
        }

        hoveredPointIdx = nearestIdx;
        const pt = points[nearestIdx];

        // 航路点悬停：只有在显示航路点（非 hide-all）时检测
        let waypointHover = null;
        if (waypointDisplayMode !== 'hide-all') {
            for (let i = 0; i < trackData.waypoints.length; i++) {
                const wp = trackData.waypoints[i];
                if (Math.abs(wp.distance - pt.distance) < (trackData.totalDistance / points.length) * 3) {
                    waypointHover = wp;
                    break;
                }
            }
        }

        if (waypointHover) {
            tooltip.innerHTML = `
                <div style="font-weight: 700; margin-bottom: 4px; color: #d4a017;">📍 ${waypointHover.name}</div>
                <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
              `;
        } else {
            tooltip.innerHTML = `
                <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
              `;
        }

        tooltip.classList.add('visible');

        const tooltipRect = tooltip.getBoundingClientRect();
        let tooltipX = e.clientX - rect.left + 12;
        let tooltipY = e.clientY - rect.top - tooltipRect.height - 12;

        if (tooltipX + tooltipRect.width > W) {
            tooltipX = e.clientX - rect.left - tooltipRect.width - 12;
        }
        if (tooltipY < 0) {
            tooltipY = e.clientY - rect.top + 12;
        }

        tooltip.style.left = tooltipX + 'px';
        tooltip.style.top = tooltipY + 'px';

        updateMapCurrentPoint(nearestIdx);
        drawChart();
    });

    canvas.addEventListener('mouseleave', function() {
        if (IS_MOBILE) return;
        tooltip.classList.remove('visible');
        hoveredPointIdx = -1;
        updateMapCurrentPoint(-1);
        drawChart();
    });

    canvas.addEventListener('click', function(e) {
        if (IS_MOBILE) return;
        if (!trackData || !canvas._scale || isDragging) return;
        // 只有在非 hide-all 状态且显示名称时才响应点击显示航路点信息
        if (waypointDisplayMode !== 'show-names') return;

        const rect = canvas.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;

        const { xScale, yScale, padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

        for (let i = 0; i < trackData.waypoints.length; i++) {
            const wp = trackData.waypoints[i];
            if (wp.distance < viewStart || wp.distance > viewEnd) continue;

            const wpX = xScale(wp.distance);
            const wpY = yScale(wp.elevation);
            const dist = Math.sqrt((x - wpX) ** 2 + (y - wpY) ** 2);

            if (dist < 12) {
                showWaypointInfo(wp);
                return;
            }
        }
    });

    canvas.addEventListener('mousedown', function(e) {
        if (IS_MOBILE) return;
        if (!trackData || !canvas._scale) return;

        if (zoomLevel > 1) {
            const rect = canvas.getBoundingClientRect();
            const x = e.clientX - rect.left;
            const y = e.clientY - rect.top;

            const { padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

            if (x >= padding.left && x <= W - padding.right && y >= padding.top && y <= padding.top + chartH) {
                isDragging = true;
                dragStartX = x;
                dragStartViewStart = viewStart;
                dragStartViewEnd = viewEnd;
                canvas.style.cursor = 'grabbing';
                e.preventDefault();
            }
        }
    });

    canvas.addEventListener('mouseup', function() {
        if (IS_MOBILE) return;
        isDragging = false;
        canvas.style.cursor = 'crosshair';
    });

    canvas.addEventListener('mouseleave', function() {
        if (IS_MOBILE) return;
        isDragging = false;
        canvas.style.cursor = 'crosshair';
    });

    canvas.addEventListener('wheel', function(e) {
        if (IS_MOBILE) return;
        e.preventDefault();
        if (!trackData || !canvas._scale) return;

        const rect = canvas.getBoundingClientRect();
        const mouseX = e.clientX - rect.left;
        const { padding, chartW, viewStart, viewEnd } = canvas._scale;

        const mouseRatio = Math.max(0, Math.min(1, (mouseX - padding.left) / chartW));
        const mouseDist = viewStart + mouseRatio * (viewEnd - viewStart);

        const factor = e.deltaY > 0 ? 0.9 : 1.1;
        let newZoom = Math.max(1, Math.min(trackData.maxZoomLevel, zoomLevel * factor));

        if (newZoom === zoomLevel) return;

        zoomLevel = newZoom;
        const newVisibleRange = trackData.totalDistance / zoomLevel;

        let newViewStart = mouseDist - mouseRatio * newVisibleRange;
        let newViewEnd = newViewStart + newVisibleRange;

        if (newViewStart < 0) {
            newViewStart = 0;
            newViewEnd = Math.min(trackData.totalDistance, newVisibleRange);
        }
        if (newViewEnd > trackData.totalDistance) {
            newViewEnd = trackData.totalDistance;
            newViewStart = Math.max(0, trackData.totalDistance - newVisibleRange);
        }

        zoomCenter = (newViewStart + newViewEnd) / 2 / trackData.totalDistance;
        zoomCenter = Math.max(0, Math.min(1, zoomCenter));

        updateZoomInfo();
        drawChart();
    }, { passive: false });

    // 触摸事件（手机端）
    if (IS_MOBILE) {
        canvas.addEventListener('touchstart', handleTouchStartMobile, { passive: false });
        canvas.addEventListener('touchmove', handleTouchMoveMobile, { passive: false });
        canvas.addEventListener('touchend', handleTouchEndMobile, { passive: false });
        canvas.addEventListener('touchcancel', handleTouchCancelMobile, { passive: false });
        canvas.style.touchAction = 'none';

        document.addEventListener('click', function(e) {
            const chartWrapper = document.getElementById('chartWrapper');
            const canvasEl = chartCanvas;
            if (chartWrapper && canvasEl && !chartWrapper.contains(e.target) && !canvasEl.contains(e
                .target)) {
                clearMobileVLine();
            }
        });

        document.addEventListener('touchstart', function(e) {
            const chartWrapper = document.getElementById('chartWrapper');
            const canvasEl = chartCanvas;
            if (chartWrapper && canvasEl && !chartWrapper.contains(e.target) && !canvasEl.contains(e
                .target)) {
                clearMobileVLine();
            }
        }, { passive: true });
    }

    // 手机端触摸处理函数
    function handleTouchStartMobile(e) {
        if (!trackData || !canvas._scale) return;
        e.preventDefault();

        const rect = canvas.getBoundingClientRect();
        const touches = e.touches;

        if (touches.length === 1) {
            const touch = touches[0];
            const x = touch.clientX - rect.left;
            const y = touch.clientY - rect.top;

            const { padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

            if (x >= padding.left && x <= W - padding.right && y >= padding.top && y <= padding.top + chartH) {
                touchState.isTouching = true;
                touchState.startX = x;
                touchState.startY = y;
                touchState.lastX = x;
                touchState.lastY = y;
                touchState.startViewStart = viewStart;
                touchState.startViewEnd = viewEnd;
                touchState.hasMoved = false;
                touchState.isDragging = false;
                touchState.isPinching = false;
                touchState.touchStartTime = Date.now();
                touchState.isTap = true;

                updateMobileVLine(x, y);
            }
        } else if (touches.length === 2) {
            touchState.isPinching = true;
            touchState.startPinchDist = Math.hypot(
                touches[0].clientX - touches[1].clientX,
                touches[0].clientY - touches[1].clientY
            );
            touchState.startZoomLevel = zoomLevel;
        }
    }

    function handleTouchMoveMobile(e) {
        if (!trackData || !canvas._scale) return;
        e.preventDefault();

        const rect = canvas.getBoundingClientRect();
        const touches = e.touches;

        if (touches.length === 1 && touchState.isTouching && !touchState.isPinching) {
            const touch = touches[0];
            const x = touch.clientX - rect.left;
            const y = touch.clientY - rect.top;

            const dx = x - touchState.startX;
            const dy = y - touchState.startY;
            const moveDist = Math.sqrt(dx * dx + dy * dy);

            touchState.hasMoved = true;

            const { padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

            if (moveDist > 5) {
                touchState.isDragging = true;
                touchState.isTap = false;
            }

            updateMobileVLine(x, y);
            touchState.lastX = x;
            touchState.lastY = y;
        } else if (touches.length === 2 && touchState.isPinching) {
            e.preventDefault();
            pinchZoomMobile(touches);
        }
    }

    function handleTouchEndMobile(e) {
        if (!trackData || !canvas._scale) return;
        e.preventDefault();

        // 只有显示名称时才处理点击航路点
        if (waypointDisplayMode === 'show-names' && touchState.isTouching && !touchState.isDragging && touchState
            .isTap && !touchState.isPinching) {
            const x = touchState.startX;
            const y = touchState.startY;

            const { xScale, yScale, padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

            for (let i = 0; i < trackData.waypoints.length; i++) {
                const wp = trackData.waypoints[i];
                if (wp.distance < viewStart || wp.distance > viewEnd) continue;

                const wpX = xScale(wp.distance);
                const wpY = yScale(wp.elevation);
                const dist = Math.sqrt((x - wpX) ** 2 + (y - wpY) ** 2);

                if (dist < 16) {
                    showWaypointInfo(wp);
                    break;
                }
            }
        }

        if (touchState.isTouching && touchState.hasMoved) {
            touchState.vlineActive = true;
            const tooltip = canvas._tooltip || document.getElementById('chartTooltip');
            if (touchState.vlineIdx >= 0 && touchState.vlineIdx < trackData.points.length) {
                const pt = trackData.points[touchState.vlineIdx];
                const points = trackData.points;

                let waypointHover = null;
                if (waypointDisplayMode !== 'hide-all') {
                    for (let i = 0; i < trackData.waypoints.length; i++) {
                        const wp = trackData.waypoints[i];
                        if (Math.abs(wp.distance - pt.distance) < (trackData.totalDistance / points.length) *
                            3) {
                            waypointHover = wp;
                            break;
                        }
                    }
                }

                if (waypointHover) {
                    tooltip.innerHTML = `
                        <div style="font-weight: 700; margin-bottom: 4px; color: #d4a017;">📍 ${waypointHover.name}</div>
                        <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                        <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                        <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
                      `;
                } else {
                    tooltip.innerHTML = `
                        <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                        <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                        <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
                      `;
                }
                tooltip.classList.add('visible');
                const canvasRect = canvas.getBoundingClientRect();
                const { chartW, W, padding, viewStart, viewEnd } = canvas._scale;
                const vlineX = (pt.distance - viewStart) / (viewEnd - viewStart) * chartW + padding.left;
                let tx = vlineX + 12;
                let ty = tooltip.offsetHeight + 12;
                if (tx + tooltip.offsetWidth > W) tx = vlineX - tooltip.offsetWidth - 12;
                if (tx < 0) tx = 4;
                tooltip.style.left = tx + 'px';
                tooltip.style.top = ty + 'px';
                updateMapCurrentPoint(touchState.vlineIdx);
                drawChart();
            }
        }

        touchState.isTouching = false;
        touchState.isDragging = false;
        touchState.isPinching = false;
        touchState.isTap = false;

        canvas.style.cursor = 'crosshair';
    }

    // ★★★ 双指缩放：以两指中心为锚点，按手指距离相对起始距离的比例缩放 ★★★
    function pinchZoomMobile(touches) {
        if (!trackData || !canvas._scale) return;

        const dist = Math.hypot(
            touches[0].clientX - touches[1].clientX,
            touches[0].clientY - touches[1].clientY
        );
        if (touchState.startPinchDist <= 0 || dist <= 0) return;

        const rect = canvas.getBoundingClientRect();
        const centerX = (touches[0].clientX + touches[1].clientX) / 2 - rect.left;

        const { padding, chartW, viewStart, viewEnd } = canvas._scale;
        const anchorRatio = Math.max(0, Math.min(1, (centerX - padding.left) / chartW));
        const anchorDist = viewStart + anchorRatio * (viewEnd - viewStart);

        const newZoom = Math.max(1, Math.min(trackData.maxZoomLevel, touchState.startZoomLevel * (dist / touchState.startPinchDist)));
        if (newZoom === zoomLevel) return;

        zoomLevel = newZoom;
        const newVisibleRange = trackData.totalDistance / zoomLevel;
        let newViewStart = anchorDist - anchorRatio * newVisibleRange;
        let newViewEnd = newViewStart + newVisibleRange;

        if (newViewStart < 0) {
            newViewStart = 0;
            newViewEnd = Math.min(trackData.totalDistance, newVisibleRange);
        }
        if (newViewEnd > trackData.totalDistance) {
            newViewEnd = trackData.totalDistance;
            newViewStart = Math.max(0, trackData.totalDistance - newVisibleRange);
        }

        zoomCenter = (newViewStart + newViewEnd) / 2 / trackData.totalDistance;
        zoomCenter = Math.max(0, Math.min(1, zoomCenter));

        updateZoomInfo();
        drawChart();
    }

    function handleTouchCancelMobile(e) {
        e.preventDefault();
        clearMobileVLine();
        touchState.isTouching = false;
        touchState.isDragging = false;
        touchState.isPinching = false;
        touchState.isTap = false;
        touchState.hasMoved = false;
        touchState.vlineActive = false;
        canvas.style.cursor = 'crosshair';
    }

    function updateMobileVLine(x, y) {
        if (!trackData || !canvas._scale) return;

        const { xScale, yScale, padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;
        const tooltip = canvas._tooltip || document.getElementById('chartTooltip');

        if (x < padding.left || x > W - padding.right || y < padding.top || y > padding.top + chartH) {
            tooltip.classList.remove('visible');
            touchState.vlineActive = false;
            touchState.vlineIdx = -1;
            updateMapCurrentPoint(-1);
            drawChart();
            return;
        }

        const points = trackData.points;
        const distRatio = (x - padding.left) / chartW;
        const targetDist = viewStart + distRatio * (viewEnd - viewStart);

        let nearestIdx = 0;
        let minDiff = Infinity;
        for (let i = 0; i < points.length; i++) {
            const diff = Math.abs(points[i].distance - targetDist);
            if (diff < minDiff) {
                minDiff = diff;
                nearestIdx = i;
            }
        }

        touchState.vlineIdx = nearestIdx;
        touchState.vlineActive = true;

        const pt = points[nearestIdx];

        let waypointHover = null;
        if (waypointDisplayMode !== 'hide-all') {
            for (let i = 0; i < trackData.waypoints.length; i++) {
                const wp = trackData.waypoints[i];
                if (Math.abs(wp.distance - pt.distance) < (trackData.totalDistance / points.length) * 3) {
                    waypointHover = wp;
                    break;
                }
            }
        }

        if (waypointHover) {
            tooltip.innerHTML = `
                <div style="font-weight: 700; margin-bottom: 4px; color: #d4a017;">📍 ${waypointHover.name}</div>
                <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
              `;
        } else {
            tooltip.innerHTML = `
                <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
              `;
        }

        tooltip.classList.add('visible');

        const vlineX = (pt.distance - viewStart) / (viewEnd - viewStart) * chartW + padding.left;
        let tx = vlineX + 12;
        let ty = tooltip.offsetHeight + 12;
        if (tx + tooltip.offsetWidth > W) tx = vlineX - tooltip.offsetWidth - 12;
        if (tx < 0) tx = 4;
        tooltip.style.left = tx + 'px';
        tooltip.style.top = ty + 'px';

        updateMapCurrentPoint(nearestIdx);
        drawChart();
    }

    function clearMobileVLine() {
        const tooltip = document.getElementById('chartTooltip');
        if (tooltip) tooltip.classList.remove('visible');
        touchState.vlineActive = false;
        touchState.vlineIdx = -1;
        touchState.hasMoved = false;
        updateMapCurrentPoint(-1);
        drawChart();
    }

    window.clearMobileVLine = clearMobileVLine;
}


