/* TrailScope module: interaction.js — generated by JS modularization build. */
function setupChartInteraction() {
    const canvas = chartCanvas;
    const tooltip = canvas._tooltip || document.getElementById('chartTooltip');
    if (canvas._chartInteractionBound) {
        if (canvas._clearMobileVLine) window.clearMobileVLine = canvas._clearMobileVLine;
        return;
    }
    canvas._chartInteractionBound = true;

    let hoverFrame = 0;
    let pendingHover = null;
    let touchFrame = 0;
    let pendingTouch = null;
    let wheelFrame = 0;
    let pendingWheel = null;
    let lastMobileVlineIdx = -1;
    let lastMobileVlineMode = null;
    let tooltipWidth = 0;
    let tooltipHeight = 0;
    let hoverDisplayMode = null;
    // ★★★ gpx.studio 运作模式（Chart.js tooltip 锚定数据点）：tooltip 居中于悬停点上方、
    // 随最近数据点离散步进移动（不逐像素跟随鼠标）；水平方向整体收拢在绘图区内；
    // 点上方放不下（越过绘图区顶缘）时翻到点下方，下方越界再收进绘图区底缘 ★★★
    function setTooltipAnchored(px, py) {
        const scale = canvas._scale;
        if (!scale) return;
        const plotLeft = scale.padding.left;
        const plotRight = scale.W - scale.padding.right;
        const plotBottom = scale.padding.top + scale.chartH;
        let tx = px - tooltipWidth / 2;
        if (tx + tooltipWidth > plotRight) tx = plotRight - tooltipWidth;
        if (tx < plotLeft) tx = plotLeft;
        let ty = py - tooltipHeight - 12;
        if (ty < scale.padding.top) ty = py + 12;
        if (ty + tooltipHeight > plotBottom) ty = Math.max(scale.padding.top, plotBottom - tooltipHeight);
        tooltip.style.left = tx + 'px';
        tooltip.style.top = ty + 'px';
    }

    // ★★★ 移动端 vline 模式 tooltip 定位：钉在图表上部、横向跟随指示线。
    // 右侧→左侧翻转阈值按容器可视宽度（W - padding.right）计算：canvas 因“加宽右留白”
    // 比容器宽 padding.right，且 chart-wrapper overflow-x: clip 会裁掉超出容器右缘的部分——
    // 若按画布宽 W 判定，手指右滑贴边时 tooltip 右半先被裁掉（用户报告的“折叠”），后才翻转 ★★★
    function positionMobileTooltip(pt) {
        const scale = canvas._scale;
        if (!scale) return;
        const vlineX = (pt.distance - scale.viewStart) / (scale.viewEnd - scale.viewStart) * scale.chartW + scale.padding.left;
        const visibleW = scale.W - scale.padding.right;
        let tx = vlineX + 12;
        let ty = tooltipHeight + 12;
        if (tx + tooltipWidth > visibleW) tx = vlineX - tooltipWidth - 12;
        if (tx < 0) tx = 4;
        tooltip.style.left = tx + 'px';
        tooltip.style.top = ty + 'px';
    }

    function updateDesktopHover(clientX, clientY) {
        if (canvas !== chartCanvas || !trackData || !canvas._scale) return;

        const rect = canvas.getBoundingClientRect();
        const x = clientX - rect.left;
        const y = clientY - rect.top;
        const { padding, chartW, chartH, W, viewStart, viewEnd, xScale, yScale } = canvas._scale;

        if (isDragging) {
            // gpx.studio 模式：拖拽平移期间 tooltip 隐藏，松开后下一次鼠标移动恢复
            tooltip.classList.remove('visible');
            const dx = x - dragStartX;
            const visibleRange = dragStartViewEnd - dragStartViewStart;
            const distShift = -(dx / chartW) * visibleRange;
            let newViewStart = dragStartViewStart + distShift;
            let newViewEnd = dragStartViewEnd + distShift;
            if (newViewStart < 0) {
                newViewStart = 0;
                newViewEnd = visibleRange;
            }
            if (newViewEnd > trackData.totalDistance) {
                newViewEnd = trackData.totalDistance;
                newViewStart = trackData.totalDistance - visibleRange;
            }
            zoomCenter = (newViewStart + newViewEnd) / 2 / trackData.totalDistance;
            drawChart();
            return;
        }

        if (x < padding.left || x > W - padding.right || y < padding.top || y > padding.top + chartH) {
            tooltip.classList.remove('visible');
            hoveredPointIdx = -1;
            updateMapCurrentPoint(-1);
            clearChartHoverOverlay(canvas);
            return;
        }

        const targetDist = viewStart + ((x - padding.left) / chartW) * (viewEnd - viewStart);
        const nearestIdx = findNearestPointIndexByDistance(trackData.points, targetDist);
        const pointChanged = nearestIdx !== hoveredPointIdx ||
            hoverDisplayMode !== waypointDisplayMode || currentMarkerPointIdx !== nearestIdx;
        const pt = trackData.points[nearestIdx];

        if (pointChanged) {
            hoveredPointIdx = nearestIdx;
            hoverDisplayMode = waypointDisplayMode;
            const threshold = trackData.totalDistance / trackData.points.length * 3;
            const waypointHover = waypointDisplayMode === 'hide-all'
                ? null
                : findFirstWaypointNearDistance(trackData.waypoints, pt.distance, threshold);
            if (waypointHover) {
                tooltip.innerHTML = `
                    <div style="font-weight: 700; margin-bottom: 4px; color: #d4a017;">📍 ${waypointHover.name}</div>
                    <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                    <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                    <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
                  `;
            } else {
                tooltip.innerHTML = `
                    <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                    <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                    <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
                  `;
            }
            tooltip.classList.add('visible');
            const tooltipRect = tooltip.getBoundingClientRect();
            tooltipWidth = tooltipRect.width;
            tooltipHeight = tooltipRect.height;
            updateMapCurrentPoint(nearestIdx);
            refreshChartHoverOverlay();
            // gpx.studio 模式：tooltip 锚定在悬停点上方（非鼠标光标位置）
            setTooltipAnchored(xScale(pt.distance), yScale(pt.ele));
        }
    }

    canvas.addEventListener('mousemove', function(e) {
        if (IS_MOBILE) return;
        pendingHover = { clientX: e.clientX, clientY: e.clientY };
        if (!hoverFrame) {
            hoverFrame = requestAnimationFrame(() => {
                hoverFrame = 0;
                const nextHover = pendingHover;
                pendingHover = null;
                if (nextHover) updateDesktopHover(nextHover.clientX, nextHover.clientY);
            });
        }
    });

    canvas.addEventListener('mouseleave', function() {
        if (IS_MOBILE) return;
        if (hoverFrame) cancelAnimationFrame(hoverFrame);
        hoverFrame = 0;
        pendingHover = null;
        if (wheelFrame) cancelAnimationFrame(wheelFrame);
        wheelFrame = 0;
        pendingWheel = null;
        hoverDisplayMode = null;
        tooltip.classList.remove('visible');
        updateMapCurrentPoint(-1);
        clearChartHoverOverlay(canvas);
    });

    canvas.addEventListener('click', function(e) {
        if (IS_MOBILE) return;
        if (!trackData || !canvas._scale || isDragging) return;
        // 只有在非 hide-all 状态且显示名称时才响应点击显示航路点信息
        if (waypointDisplayMode !== 'show-names') return;

        const rect = canvas.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;

        const { xScale, yScale, padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

        for (let i = 0; i < trackData.waypoints.length; i++) {
            const wp = trackData.waypoints[i];
            if (wp.distance < viewStart || wp.distance > viewEnd) continue;

            const wpX = xScale(wp.distance);
            const wpY = yScale(wp.elevation);
            const dist = Math.sqrt((x - wpX) ** 2 + (y - wpY) ** 2);

            if (dist < 12) {
                showWaypointInfo(wp);
                return;
            }
        }
    });

    canvas.addEventListener('mousedown', function(e) {
        if (IS_MOBILE) return;
        if (!trackData || !canvas._scale) return;

        if (zoomLevel > 1) {
            const rect = canvas.getBoundingClientRect();
            const x = e.clientX - rect.left;
            const y = e.clientY - rect.top;

            const { padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

            if (x >= padding.left && x <= W - padding.right && y >= padding.top && y <= padding.top + chartH) {
                isDragging = true;
                dragStartX = x;
                dragStartViewStart = viewStart;
                dragStartViewEnd = viewEnd;
                canvas.style.cursor = 'grabbing';
                e.preventDefault();
            }
        }
    });

    canvas.addEventListener('mouseup', function() {
        if (IS_MOBILE) return;
        isDragging = false;
        // 拖拽平移结束后强制下一次鼠标移动重设内容并重新锚定 tooltip
        hoverDisplayMode = null;
        canvas.style.cursor = 'crosshair';
    });

    canvas.addEventListener('mouseleave', function() {
        if (IS_MOBILE) return;
        isDragging = false;
        canvas.style.cursor = 'crosshair';
    });

    function handleWheelZoom(e) {
        const rect = canvas.getBoundingClientRect();
        const mouseX = e.clientX - rect.left;
        const { padding, chartW, viewStart, viewEnd } = canvas._scale;

        const mouseRatio = Math.max(0, Math.min(1, (mouseX - padding.left) / chartW));
        const mouseDist = viewStart + mouseRatio * (viewEnd - viewStart);

        const factor = e.deltaY > 0 ? 0.9 : 1.1;
        let newZoom = Math.max(1, Math.min(trackData.maxZoomLevel, zoomLevel * factor));

        if (newZoom === zoomLevel) return;

        zoomLevel = newZoom;
        const newVisibleRange = trackData.totalDistance / zoomLevel;

        let newViewStart = mouseDist - mouseRatio * newVisibleRange;
        let newViewEnd = newViewStart + newVisibleRange;

        if (newViewStart < 0) {
            newViewStart = 0;
            newViewEnd = Math.min(trackData.totalDistance, newVisibleRange);
        }
        if (newViewEnd > trackData.totalDistance) {
            newViewEnd = trackData.totalDistance;
            newViewStart = Math.max(0, trackData.totalDistance - newVisibleRange);
        }

        zoomCenter = (newViewStart + newViewEnd) / 2 / trackData.totalDistance;
        zoomCenter = Math.max(0, Math.min(1, zoomCenter));

        updateZoomInfo();
        drawChart();
    }

    canvas.addEventListener('wheel', function(e) {
        if (IS_MOBILE) return;
        e.preventDefault();
        if (!trackData || !canvas._scale) return;

        // ★★★ 与 mousemove 相同：只保留最新一次 wheel 事件，下一帧只执行一次 drawChart，
        // 触控板惯性滚动每秒上百次事件时避免每次同步全量重绘 ★★★
        pendingWheel = e;
        if (!wheelFrame) {
            wheelFrame = requestAnimationFrame(() => {
                wheelFrame = 0;
                const nextWheel = pendingWheel;
                pendingWheel = null;
                if (nextWheel && trackData && canvas._scale) handleWheelZoom(nextWheel);
            });
        }
    }, { passive: false });

    // 触摸事件（手机端）
    if (IS_MOBILE) {
        canvas.addEventListener('touchstart', handleTouchStartMobile, { passive: false });
        canvas.addEventListener('touchmove', handleTouchMoveMobile, { passive: false });
        canvas.addEventListener('touchend', handleTouchEndMobile, { passive: false });
        canvas.addEventListener('touchcancel', handleTouchCancelMobile, { passive: false });
        canvas.style.touchAction = 'none';
        canvas._clearMobileVLine = clearMobileVLine;

        if (!window.__trailScopeMobileOutsideListenersBound) {
            const clearOutside = (e) => {
                const chartWrapper = document.getElementById('chartWrapper');
                const canvasEl = chartCanvas;
                if (chartWrapper && canvasEl && !chartWrapper.contains(e.target) && !canvasEl.contains(e.target)) {
                    window.clearMobileVLine?.();
                }
            };
            document.addEventListener('click', clearOutside);
            document.addEventListener('touchstart', clearOutside, { passive: true });
            window.__trailScopeMobileOutsideListenersBound = true;
        }
        window.clearMobileVLine = clearMobileVLine;
    }

    // 手机端触摸处理函数
    function handleTouchStartMobile(e) {
        if (!trackData || !canvas._scale) return;
        e.preventDefault();

        const rect = canvas.getBoundingClientRect();
        const touches = e.touches;

        if (touches.length === 1) {
            const touch = touches[0];
            const x = touch.clientX - rect.left;
            const y = touch.clientY - rect.top;

            const { padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

            if (x >= padding.left && x <= W - padding.right && y >= padding.top && y <= padding.top + chartH) {
                touchState.isTouching = true;
                touchState.startX = x;
                touchState.startY = y;
                touchState.lastX = x;
                touchState.lastY = y;
                touchState.startViewStart = viewStart;
                touchState.startViewEnd = viewEnd;
                touchState.hasMoved = false;
                touchState.isDragging = false;
                touchState.isPinching = false;
                touchState.touchStartTime = Date.now();
                touchState.isTap = true;
                lastMobileVlineIdx = -1;
                lastMobileVlineMode = null;

                updateMobileVLine(x, y);
            }
        } else if (touches.length === 2) {
            touchState.isPinching = true;
            touchState.startPinchDist = Math.hypot(
                touches[0].clientX - touches[1].clientX,
                touches[0].clientY - touches[1].clientY
            );
            touchState.startZoomLevel = zoomLevel;
        }
    }

    function processSingleTouchMove(x, y) {
        if (!trackData || !canvas._scale || !touchState.isTouching || touchState.isPinching) return;

        const dx = x - touchState.startX;
        const dy = y - touchState.startY;
        const moveDist = Math.sqrt(dx * dx + dy * dy);
        touchState.hasMoved = true;

        if (moveDist > 5) {
            touchState.isDragging = true;
            touchState.isTap = false;
        }

        updateMobileVLine(x, y);
        touchState.lastX = x;
        touchState.lastY = y;
    }

    function handleTouchMoveMobile(e) {
        if (!trackData || !canvas._scale) return;
        e.preventDefault();

        const touches = e.touches;
        if (touches.length === 1 && touchState.isTouching && !touchState.isPinching) {
            const rect = canvas.getBoundingClientRect();
            const touch = touches[0];
            const x = touch.clientX - rect.left;
            const y = touch.clientY - rect.top;
            pendingTouch = { x, y };
            if (!touchFrame) {
                touchFrame = requestAnimationFrame(() => {
                    touchFrame = 0;
                    const nextTouch = pendingTouch;
                    pendingTouch = null;
                    if (nextTouch) processSingleTouchMove(nextTouch.x, nextTouch.y);
                });
            }
        } else if (touches.length === 2 && touchState.isPinching) {
            e.preventDefault();
            pinchZoomMobile(touches);
        }
    }

    function handleTouchEndMobile(e) {
        if (!trackData || !canvas._scale) return;
        e.preventDefault();

        if (touchFrame) {
            cancelAnimationFrame(touchFrame);
            touchFrame = 0;
            const nextTouch = pendingTouch;
            pendingTouch = null;
            if (nextTouch) processSingleTouchMove(nextTouch.x, nextTouch.y);
        }

        // 只有显示名称时才处理点击航路点
        if (waypointDisplayMode === 'show-names' && touchState.isTouching && !touchState.isDragging && touchState
            .isTap && !touchState.isPinching) {
            const x = touchState.startX;
            const y = touchState.startY;

            const { xScale, yScale, padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;

            for (let i = 0; i < trackData.waypoints.length; i++) {
                const wp = trackData.waypoints[i];
                if (wp.distance < viewStart || wp.distance > viewEnd) continue;

                const wpX = xScale(wp.distance);
                const wpY = yScale(wp.elevation);
                const dist = Math.sqrt((x - wpX) ** 2 + (y - wpY) ** 2);

                if (dist < 16) {
                    showWaypointInfo(wp);
                    break;
                }
            }
        }


        touchState.isTouching = false;
        touchState.isDragging = false;
        touchState.isPinching = false;
        touchState.isTap = false;

        canvas.style.cursor = 'crosshair';
    }

    // ★★★ 双指缩放：以两指中心为锚点，按手指距离相对起始距离的比例缩放 ★★★
    function pinchZoomMobile(touches) {
        if (!trackData || !canvas._scale) return;

        const dist = Math.hypot(
            touches[0].clientX - touches[1].clientX,
            touches[0].clientY - touches[1].clientY
        );
        if (touchState.startPinchDist <= 0 || dist <= 0) return;

        const rect = canvas.getBoundingClientRect();
        const centerX = (touches[0].clientX + touches[1].clientX) / 2 - rect.left;

        const { padding, chartW, viewStart, viewEnd } = canvas._scale;
        const anchorRatio = Math.max(0, Math.min(1, (centerX - padding.left) / chartW));
        const anchorDist = viewStart + anchorRatio * (viewEnd - viewStart);

        const newZoom = Math.max(1, Math.min(trackData.maxZoomLevel, touchState.startZoomLevel * (dist / touchState.startPinchDist)));
        if (newZoom === zoomLevel) return;

        zoomLevel = newZoom;
        const newVisibleRange = trackData.totalDistance / zoomLevel;
        let newViewStart = anchorDist - anchorRatio * newVisibleRange;
        let newViewEnd = newViewStart + newVisibleRange;

        if (newViewStart < 0) {
            newViewStart = 0;
            newViewEnd = Math.min(trackData.totalDistance, newVisibleRange);
        }
        if (newViewEnd > trackData.totalDistance) {
            newViewEnd = trackData.totalDistance;
            newViewStart = Math.max(0, trackData.totalDistance - newVisibleRange);
        }

        zoomCenter = (newViewStart + newViewEnd) / 2 / trackData.totalDistance;
        zoomCenter = Math.max(0, Math.min(1, zoomCenter));

        updateZoomInfo();
        drawChart();
    }

    function handleTouchCancelMobile(e) {
        e.preventDefault();
        clearMobileVLine();
        touchState.isTouching = false;
        touchState.isDragging = false;
        touchState.isPinching = false;
        touchState.isTap = false;
        touchState.hasMoved = false;
        touchState.vlineActive = false;
        canvas.style.cursor = 'crosshair';
    }

    function updateMobileVLine(x, y) {
        if (!trackData || !canvas._scale) return;

        const { xScale, yScale, padding, chartW, chartH, W, H, viewStart, viewEnd } = canvas._scale;
        const tooltip = canvas._tooltip || document.getElementById('chartTooltip');

        if (x < padding.left || x > W - padding.right || y < padding.top || y > padding.top + chartH) {
            tooltip.classList.remove('visible');
            touchState.vlineActive = false;
            touchState.vlineIdx = -1;
            lastMobileVlineIdx = -1;
            lastMobileVlineMode = null;
            updateMapCurrentPoint(-1);
            clearChartHoverOverlay(canvas);
            return;
        }

        const points = trackData.points;
        const distRatio = (x - padding.left) / chartW;
        const targetDist = viewStart + distRatio * (viewEnd - viewStart);

        const nearestIdx = findNearestPointIndexByDistance(points, targetDist);
        const pointChanged = nearestIdx !== lastMobileVlineIdx || lastMobileVlineMode !== waypointDisplayMode;

        touchState.vlineIdx = nearestIdx;
        touchState.vlineActive = true;

        const pt = points[nearestIdx];
        if (!pointChanged) {
            positionMobileTooltip(pt);
            return;
        }
        lastMobileVlineIdx = nearestIdx;
        lastMobileVlineMode = waypointDisplayMode;

        const threshold = trackData.totalDistance / points.length * 3;
        const waypointHover = waypointDisplayMode === 'hide-all'
            ? null
            : findFirstWaypointNearDistance(trackData.waypoints, pt.distance, threshold);

        if (waypointHover) {
            tooltip.innerHTML = `
                <div style="font-weight: 700; margin-bottom: 4px; color: #d4a017;">📍 ${waypointHover.name}</div>
                <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
              `;
        } else {
            tooltip.innerHTML = `
                <div>距离：<span style="font-weight: 600;">${pt.distance.toFixed(2)} km</span></div>
                <div>海拔：<span style="font-weight: 600; color: ${getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation)};">${Math.round(pt.ele)} m</span></div>
                <div>坡度：<span style="font-weight: 600; color: ${getGradientColor(pt.smoothedGradient)};">${pt.smoothedGradient > 0 ? '+' : ''}${pt.smoothedGradient.toFixed(1)}% （${getGradientLabel(pt.smoothedGradient)}）</span></div>
              `;
        }

        tooltip.classList.add('visible');
        tooltipWidth = tooltip.offsetWidth;
        tooltipHeight = tooltip.offsetHeight;
        positionMobileTooltip(pt);

        updateMapCurrentPoint(nearestIdx);
        refreshChartHoverOverlay();
    }

    function clearMobileVLine() {
        if (touchFrame) cancelAnimationFrame(touchFrame);
        touchFrame = 0;
        pendingTouch = null;
        const tooltip = document.getElementById('chartTooltip');
        if (tooltip) tooltip.classList.remove('visible');
        touchState.vlineActive = false;
        touchState.vlineIdx = -1;
        touchState.hasMoved = false;
        lastMobileVlineIdx = -1;
        lastMobileVlineMode = null;
        updateMapCurrentPoint(-1);
        clearChartHoverOverlay(canvas);
    }

    canvas._clearMobileVLine = clearMobileVLine;
    // ★★★ gpx.studio 模式：图表重绘（滚轮缩放/窗口尺寸/主题/配色等）后，
    // tooltip 重新锚定到当前悬停点的新像素位置；drawChart 重绘末尾调用 ★★★
    canvas._positionAnchoredTooltip = () => {
        if (IS_MOBILE) return;
        if (!tooltip.classList.contains('visible')) return;
        if (!trackData || !canvas._scale) return;
        if (hoveredPointIdx < 0 || hoveredPointIdx >= trackData.points.length) return;
        const { xScale, yScale, viewStart, viewEnd } = canvas._scale;
        const pt = trackData.points[hoveredPointIdx];
        if (pt.distance < viewStart || pt.distance > viewEnd) return;
        setTooltipAnchored(xScale(pt.distance), yScale(pt.ele));
    };
    canvas._destroyChartInteraction = () => {
        if (hoverFrame) cancelAnimationFrame(hoverFrame);
        if (touchFrame) cancelAnimationFrame(touchFrame);
        hoverFrame = 0;
        touchFrame = 0;
        pendingHover = null;
        pendingTouch = null;
    };
    window.clearMobileVLine = clearMobileVLine;
}


