/* TrailScope module: map-sources.js — generated by JS modularization build. */
const mapSources = {
    osm: {
        name: 'OpenStreetMap',
        url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        subdomains: 'abc',
        maxZoom: 19,
        attribution: '© OpenStreetMap contributors'
    },
    ESRIWorldImagery: {
        name: 'ESRI 卫星图',
        url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        subdomains: '',
        maxZoom: 19,
        attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
    },
    opentopomap: {
        name: 'OpenTopoMap',
        url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
        subdomains: 'abc',
        maxZoom: 17,
        attribution: '© OpenTopoMap'
    },
    opencyclemap: {
        name: 'OpenCycleMap',
        url: 'https://api.thunderforest.com/cycle/{z}/{x}/{y}{r}.png?apikey=8008601e01cf4f2aaf9a8ad4a3867e4a',
        subdomains: '',
        maxZoom: 18,
        attribution: '© Thunderforest'
    },
    TFOutdoor: {
        name: '户外徒步路线图',
        url: 'https://api.thunderforest.com/outdoors/{z}/{x}/{y}{r}.png?apikey=8008601e01cf4f2aaf9a8ad4a3867e4a',
        subdomains: '',
        maxZoom: 18,
        attribution: '© Thunderforest'
    },
    TFLandscape: {
        name: '户外等高线地图',
        url: 'https://api.thunderforest.com/landscape/{z}/{x}/{y}.png?apikey=8008601e01cf4f2aaf9a8ad4a3867e4a',
        subdomains: '',
        maxZoom: 18,
        attribution: '© Thunderforest'
    },
    TFAtlas: {
        name: '全球地图',
        url: 'https://api.thunderforest.com/atlas/{z}/{x}/{y}{r}.png?apikey=8008601e01cf4f2aaf9a8ad4a3867e4a',
        subdomains: '',
        maxZoom: 18,
        attribution: '© Thunderforest'
    },
    cyclosm: {
        name: 'CyclOSM',
        url: 'https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png',
        subdomains: 'abc',
        maxZoom: 20,
        attribution: '© CyclOSM'
    },
    openhikingmap: {
        name: 'OpenHikingMap',
        url: 'https://tile.openmaps.fr/openhikingmap/{z}/{x}/{y}.png',
        subdomains: '',
        maxZoom: 18,
        attribution: '<a href="https://github.com/sletuffe/OpenTopoMap">&copy; OpenTopoMap-R</a> <a href="https://openmaps.fr/donate">❤️ Donation</a> <a href="http://www.openstreetmap.org/copyright">&copy; OpenStreetMap</a>'
    },
    MapyOutdoor: {
        name: 'Mapy 户外地图',
        url: 'https://api.mapy.com/v1/maptiles/outdoor/256/{z}/{x}/{y}?apikey=dRyLZyNVqHzMf0pNCC4RGg7wrT9uNTbDQ3gJi98K1D4',
		minZoom: 0,
        maxZoom: 19,
        attribution: '<a href="https://api.mapy.com/copyright" target="_blank">&copy; Seznam.cz a.s. a další</a>'
    },
    MapyAerial: {
        name: 'Mapy 卫星图',
        url: 'https://api.mapy.com/v1/maptiles/aerial/256/{z}/{x}/{y}?apikey=dRyLZyNVqHzMf0pNCC4RGg7wrT9uNTbDQ3gJi98K1D4',
		minZoom: 0,
        maxZoom: 19,
        attribution: '<a href="https://api.mapy.com/copyright" target="_blank">&copy; Seznam.cz a.s. a další</a>'
    },
    amaproad: {
        name: '高德路网图',
        url: 'https://webrd0{s}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z}',
        subdomains: ['1', '2', '3', '4'],
        maxZoom: 18,
        attribution: '© 高德地图'
    },
    amapsatellite: {
        name: '高德卫星图',
        url: 'https://webst0{s}.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}',
        subdomains: ['1', '2', '3', '4'],
        maxZoom: 18,
        attribution: '© 高德地图'
    },
    gaode_hybrid: {
        name: '高德混合图',
        maxZoom: 18,
        attribution: '© 高德地图',
    },
	tiandituluwang: {
		name: '天地图路网图',
		maxZoom: 18,
		attribution: '© 天地图'
	},
	tianditusatellite: {
		name: '天地图卫星图',
		maxZoom: 18,
		attribution: '© 天地图'
	},
	ESRIWorldTopoMap: {
		name: 'ESRI 地形图',
		maxZoom: 18,
		attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
	}
};

/* 图源分组（combobox 渲染顺序与归类）；混合属性图源（卫星/混合）可同时出现在
   卫星图与路网图两组，与原生 select 的 option 列表互不影响（select 仍是状态源） */
const MAP_SOURCE_GROUPS = [
    { label: '地形图', keys: ['openhikingmap', 'opentopomap', 'opencyclemap', 'cyclosm', 'MapyOutdoor', 'TFOutdoor', 'TFLandscape', 'ESRIWorldTopoMap'] },
    { label: '卫星图', keys: ['tianditusatellite', 'amapsatellite', 'gaode_hybrid', 'MapyAerial', 'ESRIWorldImagery'] },
    { label: '路网图', keys: ['osm', 'tiandituluwang', 'tianditusatellite', 'amaproad', 'gaode_hybrid', 'TFAtlas'] }
];
const MAP_SOURCE_COMBOBOX_STRINGS = {
    searchPlaceholder: '搜索图源',
    recentLabel: '最近选择',
    emptyLabel: '无匹配图源'
};


