/* TrailScope module: map.js — generated by JS modularization build. */
function initMap() {
    if (leafletMap) return;

    leafletMap = L.map('leafletMap', {
        zoomControl: false,
        attributionControl: false,
        scrollWheelZoom: true
    }).setView([30.185, 102.065], 13);

    changeMapSource('amaproad');

    leafletMap.on('click', function() {
        hideWaypointInfoOverlay();
        if (IS_MOBILE) {
            clearMobileVLine();
        }
    });
}
function changeMapSource(source) {
    if (!leafletMap) return;

    if (!source) {
        source = document.getElementById('mapSourceSelect').value;
    }

    currentMapSource = source;
    useGCJ02Display = (source === 'amaproad' || source === 'amapsatellite' || source === 'gaode_hybrid');
    const config = mapSources[source];

    if (!config) return;

    const center = leafletMap.getCenter();
    const zoom = leafletMap.getZoom();

    if (currentTileLayer) {
        leafletMap.removeLayer(currentTileLayer);
        currentTileLayer = null;
    }

    if (source === 'gaode_hybrid') {
        const roadLayer = L.tileLayer(
            'https://wprd0{s}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&style=8&x={x}&y={y}&z={z}', { subdomains: ['1',
                    '2', '3', '4'
                ], maxZoom: 18,
                attribution: '© 高德地图' }
        );
        const satelliteLayer = L.tileLayer(
            'https://wprd0{s}.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}', { subdomains: ['1',
                    '2', '3', '4'
                ], maxZoom: 18,
                attribution: '© 高德地图' }
        );
        satelliteLayer.setZIndex(5);
        roadLayer.setZIndex(10);
        const group = L.layerGroup([roadLayer, satelliteLayer]);
        group.addTo(leafletMap);
        currentTileLayer = group;
    } else if (source === 'tiandituweixing') {
		const tiandituroadLayer = L.tileLayer(
            'http://t{s}.tianditu.gov.cn/cia_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=cia&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=50fdf5d2464091ca4951c7c2d7e017c4',
			{ subdomains: ['0', '1', '2', '3', '4', '5', '6', '7'],
			tilesize: 256,
			maxZoom: 18,
            attribution: '© 天地图' }
        );
        const tianditusatelliteLayer = L.tileLayer(
            'http://t{s}.tianditu.gov.cn/img_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=img&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=50fdf5d2464091ca4951c7c2d7e017c4',
			{ subdomains: ['0', '1', '2', '3', '4', '5', '6', '7'],
			tilesize: 256,
			maxZoom: 18,
            attribution: '© 天地图' }
        );
		tianditusatelliteLayer.setZIndex(5);
        tiandituroadLayer.setZIndex(10);
        const group = L.layerGroup([tiandituroadLayer, tianditusatelliteLayer]);
        group.addTo(leafletMap);
		currentTileLayer = group;
    } else if (source === 'tiandituluwang') {
		const tiandituroadLayer = L.tileLayer(
            'http://t{s}.tianditu.gov.cn/cva_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=cva&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=50fdf5d2464091ca4951c7c2d7e017c4',
			{ subdomains: ['0', '1', '2', '3', '4', '5', '6', '7'],
			tilesize: 256,
			maxZoom: 18,
            attribution: '© 天地图' }
        );
        const tianditumapLayer = L.tileLayer(
            'http://t{s}.tianditu.gov.cn/vec_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=vec&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=50fdf5d2464091ca4951c7c2d7e017c4',
			{ subdomains: ['0', '1', '2', '3', '4', '5', '6', '7'],
			tilesize: 256,
			maxZoom: 18,
            attribution: '© 天地图' }
        );
		tianditumapLayer.setZIndex(5);
        tiandituroadLayer.setZIndex(10);
        const group = L.layerGroup([tiandituroadLayer, tianditumapLayer]);
        group.addTo(leafletMap);
		currentTileLayer = group;
    } else if (source === 'tianditudixing') {
		const tiandituroadLayer = L.tileLayer(
            'http://t{s}.tianditu.gov.cn/cta_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=cta&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=50fdf5d2464091ca4951c7c2d7e017c4',
			{ subdomains: ['0', '1', '2', '3', '4', '5', '6', '7'],
			tilesize: 256,
			maxZoom: 14,
            attribution: '© 天地图' }
        );
        const tiandituterrainLayer = L.tileLayer(
            'http://t{s}.tianditu.gov.cn/ter_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ter&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=50fdf5d2464091ca4951c7c2d7e017c4',
			{ subdomains: ['0', '1', '2', '3', '4', '5', '6', '7'],
			tilesize: 256,
			maxZoom: 14,
            attribution: '© 天地图' }
        );
		tiandituterrainLayer.setZIndex(5);
        tiandituroadLayer.setZIndex(10);
        const group = L.layerGroup([tiandituroadLayer, tiandituterrainLayer]);
        group.addTo(leafletMap);
		currentTileLayer = group;
	} else {
        const tileOptions = {
            maxZoom: config.maxZoom,
            attribution: config.attribution
        };
        if (config.subdomains) {
            tileOptions.subdomains = config.subdomains;
        }
        if (config.customHeaders) {
            tileOptions.customHeaders = config.customHeaders;
        }
        let newLayer;
        if (config.customHeaders) {
            newLayer = new L.TileLayerHeaders(config.url, tileOptions);
        } else {
            newLayer = L.tileLayer(config.url, tileOptions);
        }
        newLayer.addTo(leafletMap);
        currentTileLayer = newLayer;
    }

    const maxZoom = config.maxZoom || 18;
    leafletMap.setView(center, Math.min(zoom, maxZoom));

    document.getElementById('mapSourceSelect').value = source;
    const fsMapSource = document.getElementById('fullscreenMapSourceSelect');
    if (fsMapSource) fsMapSource.value = source;

    if (trackData) drawMap(true);
}
function drawMap(skipFit = false) {
    if (!trackData || !leafletMap) return;

    trackLayers.forEach(layer => leafletMap.removeLayer(layer));
    trackLayers = [];

    waypointMarkers.forEach(marker => leafletMap.removeLayer(marker));
    waypointMarkers = [];

    if (currentMarker) {
        leafletMap.removeLayer(currentMarker);
        currentMarker = null;
    }

    segmentHighlightLayers.forEach(layer => leafletMap.removeLayer(layer));
    segmentHighlightLayers = [];

    const points = trackData.points;

    for (let i = 1; i < points.length; i++) {
        let color;
        if (colorMode === 'elevation') {
            color = getElevationColor(points[i].ele, trackData.minElevation, trackData.maxElevation);
        } else {
            const avgGrad = (points[i].smoothedGradient + points[i - 1].smoothedGradient) / 2;
            color = getGradientColor(avgGrad);
        }

        const segment = L.polyline([
            displayLatLng(points[i - 1]),
            displayLatLng(points[i])
        ], {
            color: color,
            weight: 4,
            opacity: 0.9
        }).addTo(leafletMap);

        trackLayers.push(segment);
    }

    const startIcon = L.divIcon({
        className: '',
        html: '<div class="custom-marker start-marker"><i class="fa-solid fa-flag"></i></div>',
        iconSize: [24, 24],
        iconAnchor: [12, 12]
    });

    const startMarker = L.marker(displayLatLng(points[0]), { icon: startIcon })
        .bindTooltip('起点', { permanent: false })
        .addTo(leafletMap);
    trackLayers.push(startMarker);

    const endIcon = L.divIcon({
        className: '',
        html: '<div class="custom-marker end-marker"><i class="fa-solid fa-flag-checkered"></i></div>',
        iconSize: [24, 24],
        iconAnchor: [12, 12]
    });

    const endMarker = L.marker(displayLatLng(points[points.length - 1]), { icon: endIcon })
        .bindTooltip('终点', { permanent: false })
        .addTo(leafletMap);
    trackLayers.push(endMarker);

    // ★★★ 只有在非 hide-all 状态下才绘制航路点 ★★★
    if (waypointDisplayMode !== 'hide-all') {
        const showNames = (waypointDisplayMode === 'show-names');
        trackData.waypoints.forEach((wp) => {
            const wpIcon = L.divIcon({
                className: '',
                html: '<div class="custom-marker"><i class="fa-solid fa-map-pin" style="font-size: 10px;"></i></div>',
                iconSize: [20, 20],
                iconAnchor: [10, 10]
            });

            const marker = L.marker(displayWaypointLatLng(wp), { icon: wpIcon })
                .addTo(leafletMap);

            // 只有显示名称时才绑定弹出窗（显示名称信息）
            if (showNames) {
                const popupContent = `
                    <div class="waypoint-popup-content">
                      <strong>${wp.name}</strong><br/>
                      <span class="waypoint-info-line">距离：${wp.distance.toFixed(2)} km</span><br/>
                      <span class="waypoint-info-line">海拔：${Math.round(wp.elevation)} m</span><br/>
                    </div>
                  `;
                marker.bindPopup(popupContent, {
                    closeButton: false,
                    offset: [0, -10],
                    autoClose: false,
                    closeOnClick: false
                });

                marker.on('mouseover', function(e) {
                    if (!isWaypointInfoPinned) {
                        marker.openPopup();
                    }
                });

                marker.on('mouseout', function(e) {
                    if (!isWaypointInfoPinned) {
                        marker.closePopup();
                    }
                });

                marker.on('click', function(e) {
                    L.DomEvent.stopPropagation(e);
                    if (isWaypointInfoPinned && selectedWaypointMarker === marker) {
                        marker.closePopup();
                        isWaypointInfoPinned = false;
                        selectedWaypointMarker = null;
                    } else {
                        marker.openPopup();
                        isWaypointInfoPinned = true;
                        selectedWaypointMarker = marker;
                    }
                });
            }

            waypointMarkers.push(marker);
        });
    }

    if (!skipFit) {
        fitMapToTrack();
    }
}
function updateMapCurrentPoint(pointIdx) {
    if (!trackData || !leafletMap) return;

    if (pointIdx < 0 || pointIdx >= trackData.points.length) {
        if (currentMarker) {
            leafletMap.removeLayer(currentMarker);
            currentMarker = null;
        }
        document.getElementById('mapInfoOverlay').classList.add('hidden');
        return;
    }

    const pt = trackData.points[pointIdx];

    if (currentMarker) {
        leafletMap.removeLayer(currentMarker);
        currentMarker = null;
    }
    const currentIcon = L.divIcon({
        className: '',
        html: '<div class="custom-marker current-marker"></div>',
        iconSize: [18, 18],
        iconAnchor: [9, 9]
    });
    currentMarker = L.marker(displayLatLng(pt), { icon: currentIcon })
        .addTo(leafletMap);

    const overlay = document.getElementById('mapInfoOverlay');
    overlay.classList.remove('hidden');
    document.getElementById('mapInfoDist').textContent = pt.distance.toFixed(2) + ' km';
    const eleSpan = document.getElementById('mapInfoEle');
    eleSpan.textContent = Math.round(pt.ele) + ' m';
    eleSpan.style.color = getElevationColor(pt.ele, trackData.minElevation, trackData.maxElevation);
    const gradSpan = document.getElementById('mapInfoGrad');
    const gradLabel = getGradientLabel(pt.smoothedGradient);
    gradSpan.textContent = (pt.smoothedGradient > 0 ? '+' : '') + pt.smoothedGradient.toFixed(1) + '% （' + gradLabel +
        '）';
    gradSpan.style.color = getGradientColor(pt.smoothedGradient);

    if (mapLinkageEnabled) {
        const displayPos = displayLatLng(pt);
        leafletMap.panTo(displayPos, { animate: false });
        if (document.getElementById('mapContainer').classList.contains('map-fullscreen-chart')) {
            const profile = document.querySelector('.fullscreen-profile');
            if (profile) {
                const mapRect = leafletMap.getContainer().getBoundingClientRect();
                const profileRect = profile.getBoundingClientRect();
                if (profileRect.height > 0 && profileRect.top > mapRect.top) {
                    // 将"当前位置"点放到地图顶部与剖面图顶部之间的中点（手机竖屏与桌面全屏自适应）
                    const desiredY = (mapRect.top + profileRect.top) / 2;
                    const viewportCenterY = mapRect.top + mapRect.height / 2;
                    leafletMap.panBy([0, viewportCenterY - desiredY], { animate: false });
                }
            }
        }
    }
}
function updateMapSegmentLabel(segmentIdx, segments) {
    const segLabel = document.getElementById('mapSegmentLabel');
    const prevBtn = document.getElementById('prevSegmentBtn');
    const nextBtn = document.getElementById('nextSegmentBtn');

    if (segmentMode === 'waypoint') {
        const seg = segments[segmentIdx];
        const startName = seg.name || '起点';
        const endName = seg.endName || '终点';
        segLabel.textContent = `${startName} → ${endName}`;
    } else {
        segLabel.textContent = `第 ${segmentIdx + 1}/${segments.length} 段`;
    }

    prevBtn.disabled = segmentIdx === 0;
    nextBtn.disabled = segmentIdx === segments.length - 1;
}


