/* TrailScope module: state.js — generated by JS modularization build. */
let trackData = null;
let chartCanvas = null;
let chartCtx = null;
let leafletMap = null;
let currentTileLayer = null;
let currentFilteredTileLayers = [];
let trackLayers = [];
let currentMarker = null;
let currentMarkerPointIdx = -1;
let waypointMarkers = [];
let segmentHighlightLayers = [];
let showAnnotations = true;
let waypointDisplayMode = 'show-names'; // 默认显示名称
let segmentMode = 'auto';
let hoveredPointIdx = -1;
let selectedWaypoint = null;
let activeSegmentIdx = -1;
let currentMapSource = 'tiandituluwang';
let colorMode = 'gradient';
let isRteptTrack = false;
let selectedWaypointMarker = null;
let isWaypointInfoPinned = false;
let weatherData = null;
let advancedPanelOpen = false;
let elevationMode = 'raw';
let mapLinkageEnabled = false;
let currentPage = 1;
let pageSize = 10;
let totalSegments = 0;
let allSegments = [];
let cachedSegmentsTrack = null;
let cachedSegmentsMode = null;
let cachedSegmentsElevationMode = null;
let cachedSegmentsPointCount = -1;
let fileLoadGeneration = 0;
let initialRenderTimer = null;
let zoomLevel = 1;
let maxZoomLevel = 1;
let zoomCenter = 0.5;
let isDragging = false;
let dragStartX = 0;
let dragStartCenter = 0;
let dragStartViewStart = 0;
let dragStartViewEnd = 0;
let touchState = {
    isTouching: false,
    isDragging: false,
    startX: 0,
    startY: 0,
    startViewStart: 0,
    startViewEnd: 0,
    lastX: 0,
    lastY: 0,
    isPinching: false,
    startPinchDist: 0,
    startZoomLevel: 1,
    pinchCenterX: 0,
    pinchCenterY: 0,
    hasMoved: false,
    touchStartTime: 0,
    isTap: false,
    vlineActive: false,
    vlineX: 0,
    vlineIdx: -1,
    vlineTooltipVisible: false
};


