/* TrailScope module: ui.js — generated by JS modularization build. */
function updatePaginationControls() {
    const totalPages = Math.ceil(totalSegments / pageSize);

    document.getElementById('pageInfo').textContent = `第 ${currentPage}/${totalPages} 页`;

    document.getElementById('firstPageBtn').disabled = currentPage === 1;
    document.getElementById('prevPageBtn').disabled = currentPage === 1;
    document.getElementById('nextPageBtn').disabled = currentPage === totalPages;
    document.getElementById('lastPageBtn').disabled = currentPage === totalPages;

    document.getElementById('pageSizeInfo').innerHTML = ` 段，共 ${totalSegments} 段`;

    const pageSizeSelect = document.getElementById('pageSizeSelect');
    const currentValue = pageSizeSelect.value;

    pageSizeSelect.innerHTML = '';

    const baseOptions = [10, 20, 25, 50, 100, 200, 250, 500, 1000];

    baseOptions.forEach(opt => {
        if (opt <= totalSegments || opt === 10) {
            const option = document.createElement('option');
            option.value = opt;
            option.textContent = opt;
            pageSizeSelect.appendChild(option);
        }
    });

    const allOption = document.createElement('option');
    allOption.value = totalSegments;
    allOption.textContent = '全部';
    pageSizeSelect.appendChild(allOption);

    let valueToSet = currentValue;
    let found = false;
    for (let i = 0; i < pageSizeSelect.options.length; i++) {
        if (pageSizeSelect.options[i].value === currentValue) {
            found = true;
            break;
        }
    }
    if (!found) {
        valueToSet = pageSizeSelect.options[0] ? pageSizeSelect.options[0].value : '10';
    }
    pageSizeSelect.value = valueToSet;

    pageSize = parseInt(pageSizeSelect.value);
}
function updateUI() {
    if (!trackData) return;

    document.getElementById('analysis').classList.remove('hidden');
    document.getElementById('emptyState').classList.add('hidden');
    document.getElementById('analysis').classList.add('fade-in');

    document.getElementById('statDistance').textContent = trackData.totalDistance.toFixed(2);
    document.getElementById('statAscent').textContent = Math.round(trackData.totalAscent);
    document.getElementById('statDescent').textContent = Math.round(trackData.totalDescent);
    document.getElementById('statMaxElev').textContent = Math.round(trackData.maxElevation);

    if (!leafletMap) {
        initMap();
    }

    const renderData = trackData;
    if (initialRenderTimer) clearTimeout(initialRenderTimer);
    initialRenderTimer = setTimeout(() => {
        initialRenderTimer = null;
        if (trackData !== renderData) return;
        drawChart();
        drawMap();
    }, 100);

    const diff = assessDifficulty(trackData);
    document.getElementById('difficultyScore').textContent = diff.overall;
    document.getElementById('difficultyLabel').textContent = diff.label;
    document.getElementById('difficultyLabel').style.background = diff.color + '22';
    document.getElementById('difficultyLabel').style.color = diff.color;

    const circumference = 2 * Math.PI * 48;
    const offset = circumference - (diff.overall / 100) * circumference;
    document.getElementById('difficultyRing').style.strokeDashoffset = offset;

    document.getElementById('distScore').textContent = Math.round(diff.distScore);
    document.getElementById('ascentScore').textContent = Math.round(diff.ascentScore);
    document.getElementById('gradScore').textContent = Math.round(diff.gradScore);

    setTimeout(() => {
        document.getElementById('distBar').style.width = diff.distScore + '%';
        document.getElementById('ascentBar').style.width = diff.ascentScore + '%';
        document.getElementById('gradBar').style.width = diff.gradScore + '%';
    }, 300);

    const time = estimateTime(trackData);
    document.getElementById('estTime').innerHTML = time.totalHours.toFixed(1) +
        ' <span class="text-base font-normal text-trail-mid/60">小时</span>';
    document.getElementById('walkTime').textContent = time.walkHours.toFixed(1) + 'h';
    document.getElementById('restTime').textContent = time.restHours.toFixed(1) + 'h';
    document.getElementById('avgPace').textContent = time.avgPace.toFixed(0);
    document.getElementById('calories').textContent = time.calories;

    const fitnessLevel = Math.min(5, Math.ceil(diff.overall / 20));
    const fitnessDescs = [
        '无需特殊体能要求，适合户外新手',
        '基本体能，适合偶尔运动的人',
        '中等体能，需要有一定的运动基础',
        '良好体能，需要经常锻炼',
        '优秀体能，仅适合经验丰富的户外徒步爱好者'
    ];
    document.getElementById('fitnessDesc').textContent = fitnessDescs[fitnessLevel - 1];

    const fitnessDots = document.querySelectorAll('.fitness-dot');
    fitnessDots.forEach((dot, i) => {
        setTimeout(() => {
            if (i < fitnessLevel) {
                const colors = ['#5c7a52', '#7a9471', '#d4a017', '#cd762a', '#c54b3c'];
                dot.style.background = colors[i];
                dot.style.transition = 'background 0.3s';
            }
        }, i * 100);
    });

    const risk = assessRisks(trackData);
    const riskList = document.getElementById('riskList');
    riskList.innerHTML = '';

    if (risk.risks.length === 0) {
        riskList.innerHTML = `
            <div class="flex items-center gap-3 p-3 rounded-xl bg-trail-moss/10">
              <i class="fa-solid fa-circle-check text-trail-moss"></i>
              <p class="text-sm text-trail-mid">未检测到显著风险，路线相对安全</p>
            </div>
          `;
    } else {
        risk.risks.forEach(r => {
            const colors = {
                high: { bg: 'rgba(197, 75, 60, 0.1)', text: '#c54b3c', border: 'rgba(197, 75, 60, 0.2)' },
                medium: { bg: 'rgba(212, 160, 23, 0.1)', text: '#d4a017', border: 'rgba(212, 160, 23, 0.2)' },
                low: { bg: 'rgba(122, 148, 113, 0.1)', text: '#7a9471', border: 'rgba(122, 148, 113, 0.2)' }
            };
            const c = colors[r.level];

            const item = document.createElement('div');
            item.className = 'flex items-start gap-3 p-3 rounded-xl';
            item.style.background = c.bg;
            item.style.border = `1px solid ${c.border}`;
            item.innerHTML = `
                      <i class="fa-solid ${r.icon} mt-0.5 w-5 text-center flex-shrink-0" style="color: ${c.text}"></i>
                      <div class="flex-1">
                        <p class="text-sm font-semibold text-trail-dark">${r.title}</p>
                        <p class="text-xs text-trail-mid/70 mt-0.5">${r.desc}</p>
                      </div>
                    `;
            riskList.appendChild(item);
        });
    }

    document.getElementById('riskLevel').textContent = risk.riskLevel;
    document.getElementById('riskLevel').style.color = risk.riskPercent > 60 ? '#c54b3c' : (risk.riskPercent > 30 ?
        '#d4a017' : '#7a9471');
    setTimeout(() => {
        document.getElementById('riskIndicator').style.left = `calc(${risk.riskPercent}% - 2px)`;
    }, 300);

    const equipment = generateEquipmentRecommendation(trackData, diff, risk);

    const essentialContainer = document.getElementById('essentialEquipment');
    essentialContainer.innerHTML = equipment.essential.map(item => `
          <div class="equipment-item">
            <span class="equipment-icon text-trail-moss"><i class="fa-solid ${item.icon}"></i></span>
            <div class="equipment-content">
              <p class="equipment-name">${item.name}</p>
              <p class="equipment-desc">${item.desc}</p>
            </div>
          </div>
        `).join('');

    const recommendedContainer = document.getElementById('recommendedEquipment');
    recommendedContainer.innerHTML = equipment.recommended.map(item => `
          <div class="equipment-item">
            <span class="equipment-icon text-accent-amber"><i class="fa-solid ${item.icon}"></i></span>
            <div class="equipment-content">
              <p class="equipment-name">${item.name}</p>
              <p class="equipment-desc">${item.desc}</p>
            </div>
          </div>
        `).join('');

    const suppliesContainer = document.getElementById('suppliesRecommendation');
    suppliesContainer.innerHTML = equipment.supplies.map(item => `
          <div class="equipment-item">
            <span class="equipment-icon text-accent-blue"><i class="fa-solid ${item.icon}"></i></span>
            <div class="equipment-content">
              <p class="equipment-name">${item.name}</p>
              <p class="equipment-desc">${item.desc}</p>
            </div>
          </div>
        `).join('');

    updateSegments();

    const dist = calculateGradientDistribution(trackData);
    const distContainer = document.getElementById('gradientDistribution');
    distContainer.innerHTML = `
          <div>
            <div class="flex items-center gap-2 mb-3">
              <i class="fa-solid fa-arrow-trend-up text-accent-red text-sm"></i>
              <span class="text-sm font-semibold text-trail-dark">上坡分布</span>
              <span class="text-xs text-trail-mid/50">(${trackData.uphillDistance.toFixed(1)}km)</span>
            </div>
            <div class="space-y-3">
              ${dist.uphill.map(d => `
                <div class="tech-tip">
                  <div class="flex items-center justify-between mb-1">
                    <div class="flex items-center gap-2">
                      <div class="w-3 h-3 rounded" style="background: ${d.color}"></div>
                      <span class="text-xs text-trail-mid">${d.name}</span>
                    </div>
                    <span class="text-xs font-medium text-trail-dark">${d.percentage.toFixed(1)}%</span>
                  </div>
                  <div class="h-1.5 rounded-full bg-trail-sage/10 overflow-hidden mb-1">
                    <div class="h-full rounded-full transition-all duration-700" style="width: 0%; background: ${d.color}" data-target="${d.percentage}"></div>
                  </div>
                  <div class="text-xs text-trail-mid/60 pl-5">${d.tip}</div>
                </div>
              `).join('')}
            </div>
          </div>
          <div>
            <div class="flex items-center gap-2 mb-3">
              <i class="fa-solid fa-arrow-trend-down text-accent-blue text-sm"></i>
              <span class="text-sm font-semibold text-trail-dark">下坡分布</span>
              <span class="text-xs text-trail-mid/50">(${trackData.downhillDistance.toFixed(1)}km)</span>
            </div>
            <div class="space-y-3">
              ${dist.downhill.map(d => `
                <div class="tech-tip">
                  <div class="flex items-center justify-between mb-1">
                    <div class="flex items-center gap-2">
                      <div class="w-3 h-3 rounded" style="background: ${d.color}"></div>
                      <span class="text-xs text-trail-mid">${d.name}</span>
                    </div>
                    <span class="text-xs font-medium text-trail-dark">${d.percentage.toFixed(1)}%</span>
                  </div>
                  <div class="h-1.5 rounded-full bg-trail-sage/10 overflow-hidden mb-1">
                    <div class="h-full rounded-full transition-all duration-700" style="width: 0%; background: ${d.color}" data-target="${d.percentage}"></div>
                  </div>
                  <div class="text-xs text-trail-mid/60 pl-5">${d.tip}</div>
                </div>
              `).join('')}
            </div>
          </div>
        `;

    setTimeout(() => {
        distContainer.querySelectorAll('[data-target]').forEach(bar => {
            bar.style.width = bar.dataset.target + '%';
        });
    }, 300);

    const summaryContainer = document.getElementById('routeSummary');
    const summaryItems = [
        { label: '起点海拔', value: Math.round(trackData.points[0].ele) + ' m', icon: 'fa-flag' },
        { label: '终点海拔', value: Math.round(trackData.points[trackData.points.length - 1].ele) + ' m',
            icon: 'fa-flag-checkered' },
        { label: '最高海拔', value: Math.round(trackData.maxElevation) + ' m', icon: 'fa-mountain' },
        { label: '最低海拔', value: Math.round(trackData.minElevation) + ' m', icon: 'fa-arrow-down' },
        { label: '海拔落差', value: Math.round(trackData.elevationRange) + ' m', icon: 'fa-arrows-up-down' },
        { label: '平均坡度', value: trackData.avgGradient.toFixed(2) + '%', icon: 'fa-percentage' },
        { label: '上坡距离', value: trackData.uphillDistance.toFixed(1) + ' km', icon: 'fa-arrow-trend-up' },
        { label: '下坡距离', value: trackData.downhillDistance.toFixed(1) + ' km',
            icon: 'fa-arrow-trend-down' },
        { label: '平路距离', value: trackData.flatDistance.toFixed(1) + ' km', icon: 'fa-minus' },
        { label: '最大上坡', value: trackData.uphillMaxGradient.toFixed(1) + '%', icon: 'fa-angle-up' },
        { label: '最大下坡', value: trackData.downhillMaxGradient.toFixed(1) + '%', icon: 'fa-angle-down' },
        { label: '航路点数', value: trackData.waypoints.length + ' 个', icon: 'fa-map-pin' },
        { label: '路线类型', value: trackData.totalAscent > trackData.totalDescent ? '以上坡为主' : (trackData
                .totalDescent > trackData.totalAscent ? '以下坡为主' : '往返型'), icon: 'fa-shuffle' }
    ];

    summaryContainer.innerHTML = summaryItems.map(item => `
          <div class="flex items-center justify-between py-2 border-b border-trail-sage/10 last:border-0">
            <div class="flex items-center gap-3">
              <div class="w-8 h-8 rounded-lg bg-trail-sage/10 flex items-center justify-center">
                <i class="fa-solid ${item.icon} text-xs text-trail-moss"></i>
              </div>
              <span class="text-trail-mid/70">${item.label}</span>
            </div>
            <span class="font-semibold text-trail-dark">${item.value}</span>
          </div>
        `).join('');
}
function updateSegments() {
    allSegments = analyzeSegments(trackData, segmentMode);
    totalSegments = allSegments.length;

    document.getElementById('segmentTotalCount').textContent = `轨迹共 ${totalSegments} 段，`;

    const totalPages = Math.ceil(totalSegments / pageSize);
    if (currentPage > totalPages) currentPage = 1;

    const startIndex = (currentPage - 1) * pageSize;
    const endIndex = Math.min(startIndex + pageSize, totalSegments);
    const pageSegments = allSegments.slice(startIndex, endIndex);

    const tbody = document.getElementById('segmentTable');
    tbody.innerHTML = '';

    const typeConfig = {
        climb: { label: '爬升', color: '#c54b3c', bg: 'rgba(197, 75, 60, 0.1)', icon: 'fa-arrow-trend-up' },
        descent: { label: '下降', color: '#3a6b8a', bg: 'rgba(58, 107, 138, 0.1)', icon: 'fa-arrow-trend-down' },
        mixed: { label: '混合', color: '#8b7355', bg: 'rgba(139, 115, 85, 0.1)', icon: 'fa-arrows-up-down' },
        flat: { label: '平路', color: '#7a9471', bg: 'rgba(122, 148, 113, 0.1)', icon: 'fa-minus' }
    };

    pageSegments.forEach((seg, pageIdx) => {
        const globalIdx = startIndex + pageIdx;
        const tc = typeConfig[seg.type] || typeConfig.flat;
        const diffColor = seg.difficulty < 30 ? '#7a9471' : (seg.difficulty < 60 ? '#d4a017' : '#c54b3c');

        const row = document.createElement('tr');
        row.className = 'segment-row border-b border-trail-sage/10';
        if (globalIdx === activeSegmentIdx) {
            row.classList.add('active');
        }
        row.innerHTML = `
            <td class="py-3 px-2 text-center">
              <span class="segment-number inline-flex items-center justify-center w-6 h-6 rounded-lg bg-trail-sage/15 text-xs font-bold text-trail-mid" data-segment-idx="${globalIdx}">${globalIdx + 1}</span>
            </td>
            <td class="py-3 px-2 text-center">
              <span class="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium" style="background: ${tc.bg}; color: ${tc.color}">
                <i class="fa-solid ${tc.icon} text-xs"></i>
                ${tc.label}
              </span>
            </td>
            <td class="py-3 px-2 text-center font-medium text-trail-dark">${seg.distance.toFixed(2)} km</td>
            <td class="py-3 px-2 text-center text-accent-red">${Math.round(seg.ascent)}m</td>
            <td class="py-3 px-2 text-center text-accent-blue">${Math.round(seg.descent)}m</td>
            <td class="py-3 px-2 text-center font-medium" style="color: ${getUphillColor(Math.max(0, seg.uphillAvg))};">+${seg.uphillAvg.toFixed(1)}%</td>
            <td class="py-3 px-2 text-center font-medium" style="color: ${getDownhillColor(Math.min(0, seg.downhillAvg))};">-${seg.downhillAvg.toFixed(1)}%</td>
            <td class="py-3 px-2 text-center font-medium" style="color: ${getUphillColor(Math.max(0, seg.maxUphillGrad))};">+${seg.maxUphillGrad.toFixed(1)}%</td>
            <td class="py-3 px-2 text-center font-medium" style="color: ${getDownhillColor(Math.min(0, seg.maxDownhillGrad))};">${seg.maxDownhillGrad.toFixed(1)}%</td>
            <td class="py-3 px-2 text-center font-medium text-trail-dark">${seg.time.toFixed(1)}h</td>
            <td class="py-3 px-2 text-center">
              <div class="inline-flex items-center gap-2">
                <div class="w-12 h-1.5 rounded-full bg-trail-sage/15 overflow-hidden">
                  <div class="h-full rounded-full" style="width: ${seg.difficulty}%; background: ${diffColor}"></div>
                </div>
              </div>
            </td>
          `;

        row.addEventListener('click', () => {
            selectSegment(globalIdx);
        });

        tbody.appendChild(row);
    });

    setupSegmentNumberTooltips();

    if (totalSegments > 10) {
        document.getElementById('paginationContainer').classList.remove('hidden');
        updatePaginationControls();
    } else {
        document.getElementById('paginationContainer').classList.add('hidden');
    }
}
function showSegmentTooltip(segIdx, e) {
    const segments = analyzeSegments(trackData, segmentMode);

    if (segIdx >= 0 && segIdx < segments.length) {
        const seg = segments[segIdx];
        let tooltipText = '';

        if (segmentMode === 'waypoint') {
            const startName = seg.name || '起点';
            const endName = seg.endName || '终点';
            tooltipText = `${startName}，${seg.startDist.toFixed(2)} km → ${endName}，${seg.endDist.toFixed(2)} km`;
        } else {
            tooltipText = `${seg.startDist.toFixed(2)} km → ${seg.endDist.toFixed(2)} km`;
        }

        const tooltip = document.getElementById('segmentTooltip');
        tooltip.textContent = tooltipText;
        tooltip.classList.add('visible');

        moveSegmentTooltip(e);
    }
}
function readFileContent(file, asArrayBuffer) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = event => resolve(event.target.result);
        reader.onerror = () => reject(new Error('文件读取失败'));
        if (asArrayBuffer) {
            reader.readAsArrayBuffer(file);
        } else {
            reader.readAsText(file);
        }
    });
}

async function parseUploadedFile(file, extension) {
    if (extension === 'kmz') {
        const arrayBuffer = await readFileContent(file, true);
        return parseKML(await extractKMLFromKMZ(arrayBuffer));
    }
    const text = await readFileContent(file, false);
    return extension === 'kml' ? parseKML(text) : parseGPX(text);
}

async function handleFile(file) {
    if (!file) return;

    const loadGeneration = ++fileLoadGeneration;
    const extension = file.name.toLowerCase().split('.').pop();
    if (!['gpx', 'kml', 'kmz'].includes(extension)) {
        showToast('请上传 .gpx、.kml 或 .kmz 格式文件', 'error');
        return;
    }
    if (file.size > 32 * 1024 * 1024) {
        showToast('轨迹文件过大，最大支持 32 MB', 'error');
        return;
    }

    document.getElementById('fileName').textContent = file.name;
    document.getElementById('fileInfo').classList.remove('hidden');

    try {
        const { points, waypoints, isRtept } = await parseUploadedFile(file, extension);
        if (loadGeneration !== fileLoadGeneration) return;
        if (points.length < 2) {
            showToast(`${extension.toUpperCase()} 文件中没有找到足够的轨迹点`, 'error');
            return;
        }

        const nextTrackData = processTrack(points, waypoints);
        if (loadGeneration !== fileLoadGeneration) return;
        clearRenderedTrackLayers();
        resetSegmentAnalysisCache();
        trackData = nextTrackData;
        document.getElementById('clearFileBtn').classList.remove('hidden');
        zoomLevel = 1;
        zoomCenter = 0.5;
        activeSegmentIdx = -1;
        currentPage = 1;
        document.getElementById('clearHighlightBtn').classList.add('hidden');
        hideMapSegmentInfo();

        hideWaypointInfoOverlay();

        if (isRtept) {
            document.getElementById('warningText').classList.remove('hidden');
        } else {
            document.getElementById('warningText').classList.add('hidden');
        }

        if (IS_MOBILE) {
            clearMobileVLine();
        }

        waypointDisplayMode = 'show-names';
        updateWaypointButton();

        updateUI();
        showToast('轨迹分析完成！', 'success');
    } catch (err) {
        if (loadGeneration !== fileLoadGeneration) return;
        console.error(err);
        showToast('解析轨迹文件失败：' + err.message, 'error');
    }
}
function clearFile() {
    fileLoadGeneration++;
    if (initialRenderTimer) {
        clearTimeout(initialRenderTimer);
        initialRenderTimer = null;
    }
    resetSegmentAnalysisCache();
    document.getElementById('fileInput').value = '';
    document.getElementById('fileName').textContent = 'GPX / KML / KMZ 文件未加载或为空';
    document.getElementById('clearFileBtn').classList.add('hidden');
    document.getElementById('warningText').classList.add('hidden');
    trackData = null;
    document.getElementById('analysis').classList.add('hidden');
    document.getElementById('emptyState').classList.remove('hidden');
    document.getElementById('waypointInfo').classList.add('hidden');
    document.getElementById('clearHighlightBtn').classList.add('hidden');
    activeSegmentIdx = -1;
    currentPage = 1;
    hideMapSegmentInfo();

    document.getElementById('mapInfoOverlay').classList.add('hidden');
    document.getElementById('mapInfoDist').textContent = '—';
    const eleSpan = document.getElementById('mapInfoEle');
    eleSpan.textContent = '—';
    eleSpan.style.color = '';
    const gradSpan = document.getElementById('mapInfoGrad');
    gradSpan.textContent = '—';
    gradSpan.style.color = '';

    hideWaypointInfoOverlay();

    if (IS_MOBILE) {
        clearMobileVLine();
    }

    clearRenderedTrackLayers();

    // 重置状态
    waypointDisplayMode = 'show-names';
    updateWaypointButton();
}
function toggleAnnotations() {
    showAnnotations = !showAnnotations;
    document.getElementById('annotationLabel').textContent = showAnnotations ? '隐藏标注' : '显示标注';
    const fullLabel = document.getElementById('fullscreenAnnotationLabel');
    if (fullLabel) fullLabel.textContent = showAnnotations ? '隐藏标注' : '显示标注';
    drawChart();
}
function exportChart() {
    if (!trackData) return;

    const link = document.createElement('a');
    link.download = 'elevation-profile.png';
    link.href = chartCanvas.toDataURL();
    link.click();
    showToast('图表已导出', 'success');
}
function loadDemoData() {
    const loadGeneration = ++fileLoadGeneration;
    fetch('./demo.gpx')
        .then(response => {
            if (!response.ok) {
                throw new Error('demo.gpx 加载失败');
            }
            return response.text();
        })
        .then(gpxText => {
            if (loadGeneration !== fileLoadGeneration) return;
            try {
                const { points, waypoints, isRtept } = parseGPX(gpxText);

                if (points.length < 2) {
                    showToast('demo.gpx 中没有找到足够的轨迹点', 'error');
                    return;
                }

                const nextTrackData = processTrack(points, waypoints);
                if (loadGeneration !== fileLoadGeneration) return;
                resetSegmentAnalysisCache();
                trackData = nextTrackData;

                document.getElementById('clearFileBtn').classList.remove('hidden');

                zoomLevel = 1;
                zoomCenter = 0.5;
                activeSegmentIdx = -1;
                currentPage = 1;

                document.getElementById('clearHighlightBtn').classList.add('hidden');
                hideMapSegmentInfo();
                hideWaypointInfoOverlay();

                if (IS_MOBILE) {
                    clearMobileVLine();
                }

                if (isRtept) {
                    document.getElementById('warningText').classList.remove('hidden');
                } else {
                    document.getElementById('warningText').classList.add('hidden');
                }

                document.getElementById('fileName').textContent = 'demo.gpx';
                document.getElementById('fileInfo').classList.remove('hidden');

                // 重置状态
                waypointDisplayMode = 'show-names';
                updateWaypointButton();

                updateUI();

                showToast('已加载示例徒步轨迹', 'success');

            } catch (err) {
                console.error(err);
                showToast('解析 demo.gpx 失败：' + err.message, 'error');
            }
        })
        .catch(err => {
            console.error(err);
            showToast(err.message, 'error');
        });
}
function updateFullscreenButton(fullscreen) {
    const btn = document.getElementById('mapFullscreenBtn');
    if (!btn) return;
    btn.title = fullscreen ? '退出地图全屏模式' : '地图全屏模式';
    btn.innerHTML = fullscreen ?
        '<i class="fa-solid fa-minimize"></i>' :
        '<i class="fa-solid fa-maximize"></i>';
}
function toggleMapLinkage() {
    mapLinkageEnabled = !mapLinkageEnabled;

    const btn = document.getElementById('mapLinkageBtn');
    if (btn) {
        if (mapLinkageEnabled) {
            btn.classList.add('active-linkage');
            btn.title = '禁用地图联动';
        } else {
            btn.classList.remove('active-linkage');
            btn.title = '启用地图联动';
        }
    }

    const fsBtn = document.getElementById('fullscreenMapLinkageBtn');
    if (fsBtn) {
        if (mapLinkageEnabled) {
            fsBtn.classList.add('active-linkage');
            fsBtn.title = '禁用地图联动';
        } else {
            fsBtn.classList.remove('active-linkage');
            fsBtn.title = '启用地图联动';
        }
    }

    if (!mapLinkageEnabled) {
        if (currentMarker) {
            leafletMap.removeLayer(currentMarker);
            currentMarker = null;
            currentMarkerPointIdx = -1;
        }
    } else {
        if (hoveredPointIdx >= 0) {
            updateMapCurrentPoint(hoveredPointIdx);
        } else if (touchState.vlineIdx >= 0) {
            updateMapCurrentPoint(touchState.vlineIdx);
        } else {
            updateMapCurrentPoint(-1);
        }
    }
}
function enterMapFullscreen() {
    const map = document.getElementById('mapContainer');

    if (map.classList.contains('map-fullscreen-chart')) {
        exitMapFullscreen();
        return;
    }

    // ★★★ 保存进入全屏前的地图中心点与缩放级别（切换后保持不变，仅调整锚定位置） ★★★
    if (leafletMap) {
        fullscreenSavedCenter = leafletMap.getCenter();
        fullscreenSavedZoom = leafletMap.getZoom();
    }

    normalChartCanvas = document.getElementById('elevationChart');

    map.classList.add('map-fullscreen-chart');

    if (IS_MOBILE && isPortraitViewport()) {
        map.classList.add('portrait-mode');
    }

    document.getElementById('mapLocationLegend')?.classList.add('hidden');
    document.getElementById('mapSourceControl')?.classList.add('hidden');

    const toolbar = document.createElement('div');
    toolbar.className = 'fullscreen-chart-toolbar';
    toolbar.id = 'fullscreenChartToolbar';

    const linkageBtnClass = mapLinkageEnabled ? 'map-control-btn active-linkage' : 'map-control-btn';
    const linkageBtnTitle = mapLinkageEnabled ? '禁用地图联动' : '启用地图联动';

    toolbar.innerHTML = `
          <div class="flex items-center gap-2 justify-between w-full">
            <div class="flex items-center gap-2 ml-auto">
              <select id="fullscreenColorModeSelect" class="color-mode-select" title="切换颜色模式" onchange="document.getElementById('colorModeSelect').value=this.value; changeColorMode();">
                <option value="gradient">坡度分析</option>
                <option value="elevation">海拔分析</option>
              </select>
              <select id="fullscreenMapSourceSelect" class="map-source-select" title="切换图源" onchange="document.getElementById('mapSourceSelect').value=this.value; changeMapSource();">
                <option value="tiandituluwang" selected>天地图路网图</option>
                <option value="tiandituweixing">天地图卫星图</option>
                <option value="tianditudixing">天地图地形图</option>
                <option value="amaproad">高德路网图</option>
                <option value="amapsatellite">高德卫星图</option>
                <option value="gaode_hybrid">高德混合图</option>
                <option value="googlesatellite">谷歌卫星图</option>
                <option value="googlehybrid">谷歌混合图</option>
                <option value="osm">OpenStreetMap</option>
                <option value="openhikingmap">OpenHikingMap</option>
                <option value="windy">Windy</option>
                <option value="opentopomap">OpenTopoMap</option>
                <option value="opencyclemap">OpenCycleMap</option>
                <option value="cyclosm">CyclOSM</option>
              </select>
            </div>
          </div>
        `;
    map.appendChild(toolbar);

    const panel = document.createElement('div');
    panel.className = 'fullscreen-profile';
    panel.id = 'fullscreenProfile';
    panel.innerHTML = `
          <div class="flex items-center justify-between gap-2 mb-2">
            <div id="fullscreenProfileLegend" class="flex-1"></div>
            <div class="flex items-center gap-2 flex-shrink-0">
              <button onclick="toggleAnnotations()" class="btn-sm-uniform bg-trail-dark text-trail-cream hover:bg-trail-mid">
                <i class="fa-solid fa-eye"></i> <span id="fullscreenAnnotationLabel">${showAnnotations ? '隐藏标注' : '显示标注'}</span>
              </button>
              <!-- ★★★ 全屏模式下的三状态按钮 ★★★ -->
              <button onclick="toggleWaypointDisplay()" id="fullscreenWaypointToggleBtn" class="btn-sm-uniform bg-trail-dark text-trail-cream hover:bg-trail-mid">
                <i class="fa-solid fa-tag"></i> <span id="fullscreenWaypointToggleLabel">隐藏航路点名称</span>
              </button>
            </div>
          </div>
          <div class="relative flex-1 chart-area">
            <canvas id="fullscreenElevationChart"></canvas>
            <div id="fullscreenChartTooltip" class="tooltip"></div>
          </div>
        `;
    map.appendChild(panel);

    // 更新全屏按钮文字
    const fsToggleBtn = document.getElementById('fullscreenWaypointToggleBtn');
    const fsToggleLabel = document.getElementById('fullscreenWaypointToggleLabel');
    if (fsToggleBtn && fsToggleLabel) {
        let icon, text;
        if (waypointDisplayMode === 'show-names') {
            icon = 'fa-tag';
            text = '隐藏航路点名称';
        } else if (waypointDisplayMode === 'hide-names') {
            icon = 'fa-eye-slash';
            text = '隐藏所有航路点';
        } else {
            icon = 'fa-tag';
            text = '显示航路点名称';
        }
        fsToggleBtn.innerHTML = `<i class="fa-solid ${icon}"></i> <span id="fullscreenWaypointToggleLabel">${text}</span>`;
    }

    const legendHtml = `
          <div class="flex items-center gap-4 flex-wrap" style="display: flex; align-items: center; gap: 12px; flex-wrap: wrap;">
            <div id="fs-gradientLegend" class="flex items-center gap-4">
              <div class="flex items-center gap-2">
                <span class="font-medium text-trail-mid/70 text-xs">上坡：</span>
                <div class="w-24 h-3 rounded grad-bar-up"></div>
                <span class="text-xs text-trail-mid/70">缓→陡</span>
              </div>
              <div class="flex items-center gap-2">
                <span class="font-medium text-trail-mid/70 text-xs">下坡：</span>
                <div class="w-24 h-3 rounded grad-bar-down"></div>
                <span class="text-xs text-trail-mid/70">缓→陡</span>
              </div>
            </div>
            <div id="fs-elevationLegend" class="hidden flex items-center gap-2">
              <span class="font-medium text-trail-mid/70 text-xs">海拔：</span>
              <div class="w-24 h-3 rounded grad-bar-elevation"></div>
              <span class="text-xs text-trail-mid/70">低→高</span>
            </div>
            <div class="flex items-center gap-3" style="display: flex; align-items: center; gap: 10px; margin-left: 4px;">
              <div class="flex items-center gap-1.5">
                <div class="w-2.5 h-2.5 rounded-full" style="background: #c54b3c; flex-shrink: 0;"></div>
                <span class="text-xs text-trail-mid/70">当前位置</span>
              </div>
              <div class="flex items-center gap-1.5">
                <div class="w-2.5 h-2.5 rounded-full" style="background: #5c7a52; flex-shrink: 0;"></div>
                <span class="text-xs text-trail-mid/70">起点</span>
              </div>
              <div class="flex items-center gap-1.5">
                <div class="w-2.5 h-2.5 rounded-full" style="background: #c54b3c; flex-shrink: 0;"></div>
                <span class="text-xs text-trail-mid/70">终点</span>
              </div>
            </div>
          </div>
        `;

    document.getElementById('fullscreenProfileLegend').innerHTML = legendHtml;

    document.getElementById('fullscreenColorModeSelect').value = colorMode;
    document.getElementById('fullscreenMapSourceSelect').value = currentMapSource;

    if (colorMode === 'elevation') {
        const fsGrad = document.getElementById('fs-gradientLegend');
        const fsElev = document.getElementById('fs-elevationLegend');
        if (fsGrad) fsGrad.classList.add('hidden');
        if (fsElev) fsElev.classList.remove('hidden');
    }

    fullscreenChartCanvas = document.getElementById('fullscreenElevationChart');
    fullscreenChartCanvas._tooltip = document.getElementById('fullscreenChartTooltip');

    chartCanvas = fullscreenChartCanvas;
    chartCtx = chartCanvas.getContext('2d');

    setupChartInteraction();

    // ★★★ 先同步完成图表绘制与地图重排，再请求原生全屏：
    // 点击处理返回后的第一帧就是已绘制好的全屏内容，避免先显示深色空壳再绘制导致的黑屏 ★★★
    resizeActiveChartCanvas();
    leafletMap?.invalidateSize();
    reAnchorMapView(true);
    updateFullscreenButton(true);

    map.requestFullscreen?.();

    // ★★★ 原生全屏生效后视口尺寸才最终稳定：延迟 300ms 按最终尺寸重新锚定
    // （reAnchorMapView 使用进入前保存的中心点，多次调用幂等） ★★★
    const entryGeneration = ++fullscreenEntryGeneration;
    if (fullscreenEntryTimer) clearTimeout(fullscreenEntryTimer);
    fullscreenEntryTimer = setTimeout(() => {
        fullscreenEntryTimer = null;
        if (entryGeneration !== fullscreenEntryGeneration ||
            !map.classList.contains('map-fullscreen-chart') ||
            !document.getElementById('fullscreenProfile') ||
            chartCanvas !== fullscreenChartCanvas) return;
        resizeActiveChartCanvas();
        leafletMap?.invalidateSize();
        reAnchorMapView(true);
        updateFullscreenButton(true);
    }, 300);
}


