/* TrailScope module: waypoints.js — generated by JS modularization build. */
function showWaypointInfo(wp) {
    const info = document.getElementById('waypointInfo');
    info.classList.remove('hidden');
    document.getElementById('wpName').textContent = wp.name;
    document.getElementById('wpDetails').textContent = trackData && trackData.hasValidElevation === false
        ? `距离 ${wp.distance.toFixed(2)} km${wp.desc ? ' · ' + wp.desc : ''}`
        : `距离 ${wp.distance.toFixed(2)} km · 海拔 ${Math.round(wp.elevation)} m${wp.desc ? ' · ' + wp.desc : ''}`;
}
function updateWaypointButton() {
    const btn = document.getElementById('waypointToggleBtn');
    const label = document.getElementById('waypointToggleLabel');
    const fsBtn = document.getElementById('fullscreenWaypointToggleBtn');
    const fsLabel = document.getElementById('fullscreenWaypointToggleLabel');

    let icon, text;
    if (waypointDisplayMode === 'show-names') {
        icon = 'fa-tag';
        text = '隐藏航路点名称';
    } else if (waypointDisplayMode === 'hide-names') {
        icon = 'fa-eye-slash';
        text = '隐藏所有航路点';
    } else {
        icon = 'fa-tag';
        text = '显示航路点名称';
    }

    if (btn) btn.innerHTML = `<i class="fa-solid ${icon}"></i> <span id="waypointToggleLabel">${text}</span>`;
    if (fsBtn) fsBtn.innerHTML = `<i class="fa-solid ${icon}"></i> <span id="fullscreenWaypointToggleLabel">${text}</span>`;
}



